if(TRUE)
    file(GLOB_RECURSE LWESP_WIFI_SOURCES ${MICROPY_MODULES_PORT_DIR}/lwesp/src/lwesp/*.c)
    list(APPEND MICROPY_SOURCE_MODULES_PORT ${LWESP_WIFI_SOURCES})
    list(APPEND MICROPY_SOURCE_MODULES_PORT ${MICROPY_MODULES_PORT_DIR}/lwesp/src/api/lwesp_netconn.c)
    list(APPEND MICROPY_SOURCE_MODULES_PORT ${MICROPY_MODULES_PORT_DIR}/lwesp/test.c)
   
    file(GLOB_RECURSE LWESP_WIFI_SOURCES ${MICROPY_MODULES_PORT_DIR}/lwesp/port/micropython/src/*.c)
    list(APPEND MICROPY_SOURCE_MODULES_PORT ${LWESP_WIFI_SOURCES})
    
    list(APPEND MICROPY_INC_MODULES_PORT ${MICROPY_MODULES_PORT_DIR}/lwesp/src/include)
    
    list(APPEND MICROPY_INC_MODULES_PORT ${MICROPY_MODULES_PORT_DIR}/lwesp/port/micropython/include)
    if(ESP_PLATFORM) 
    file(GLOB_RECURSE LWESP_WIFI_SOURCES ${MICROPY_MODULES_PORT_DIR}/lwesp/port/esp32/src/*.c)
    list(APPEND MICROPY_SOURCE_MODULES_PORT ${LWESP_WIFI_SOURCES})

    list(APPEND MICROPY_INC_MODULES_PORT ${MICROPY_MODULES_PORT_DIR}/lwesp/port/esp32/include)
    endif()
endif()
