/*
 * Copyright (C) 2020 Alibaba Group Holding Limited
 */

#ifndef SYSCALL_NO_H
#define SYSCALL_NO_H

/* --------------- base api ---------------*/
#define AOS_BASIC_BASE                 (0x10)
/*common*/
#define SYS_AOS_HANDLE_DELETE        (AOS_BASIC_BASE + 0)
#define SYS_AOS_HANDLE_CLOSE         (AOS_BASIC_BASE + 1)
#define SYS_AOS_HANDLE_VALID         (AOS_BASIC_BASE + 2)
/*semphore*/
#define SYS_AOS_SEM_NEW              (AOS_BASIC_BASE + 3)
#define SYS_AOS_SEM_OPEN             (AOS_BASIC_BASE + 4)
#define SYS_AOS_SEM_POST             (AOS_BASIC_BASE + 5)
#define SYS_AOS_SEM_POST_ALL         (AOS_BASIC_BASE + 6)
#define SYS_AOS_SEM_WAIT             (AOS_BASIC_BASE + 7)
#define SYS_AOS_SEM_GETVALUE         (AOS_BASIC_BASE + 8)
#define SYS_AOS_SEM_UNLINK           (AOS_BASIC_BASE + 9)
/*mutex*/
#define SYS_AOS_MUTEX_NEW            (AOS_BASIC_BASE + 10)
#define SYS_AOS_MUTEX_LOCK           (AOS_BASIC_BASE + 11)
#define SYS_AOS_MUTEX_UNLOCK         (AOS_BASIC_BASE + 12)
/*event*/
#define SYS_AOS_EVENT_OPEN           (AOS_BASIC_BASE + 13)
#define SYS_AOS_EVENT_NEW            (AOS_BASIC_BASE + 14)
#define SYS_AOS_EVENT_SET            (AOS_BASIC_BASE + 15)
#define SYS_AOS_EVENT_GET            (AOS_BASIC_BASE + 16)
#define SYS_AOS_EVENT_UNLINK         (AOS_BASIC_BASE + 17)
/*queue*/
#define SYS_AOS_QUEUE_OPEN           (AOS_BASIC_BASE + 18)
#define SYS_AOS_QUEUE_NEW            (AOS_BASIC_BASE + 19)
#define SYS_AOS_QUEUE_SEND           (AOS_BASIC_BASE + 20)
#define SYS_AOS_QUEUE_RECV           (AOS_BASIC_BASE + 21)
#define SYS_AOS_QUEUE_UNLINK         (AOS_BASIC_BASE + 22)
#define SYS_AOS_QUEUE_GET_COUNT      (AOS_BASIC_BASE + 23)
/*timer*/
#define SYS_AOS_TIMER_NEW_EXT        (AOS_BASIC_BASE + 24)
#define SYS_AOS_TIMER_START          (AOS_BASIC_BASE + 25)
#define SYS_AOS_TIMER_STOP           (AOS_BASIC_BASE + 26)
#define SYS_AOS_TIMER_CHANGE         (AOS_BASIC_BASE + 27)
#define SYS_AOS_TIMER_CHANGE_ONCE    (AOS_BASIC_BASE + 28)
/*futex*/
#define SYS_AOS_FUTEX                (AOS_BASIC_BASE + 29)
/* info */
#define SYS_AOS_VERSION_STR_GET      (AOS_BASIC_BASE + 30)
#define SYS_AOS_GET_CALENDAR         (AOS_BASIC_BASE + 31)
#define SYS_AOS_SET_CALENDAR         (AOS_BASIC_BASE + 32)
#define SYS_AOS_GET_UTC_OFFSET       (AOS_BASIC_BASE + 33)
#define SYS_AOS_SET_UTC_OFFSET       (AOS_BASIC_BASE + 34)
#define SYS_AOS_REBOOT               (AOS_BASIC_BASE + 35)
#define SYS_AOS_NOW_MS               (AOS_BASIC_BASE + 36)
#define SYS_AOS_GET_HZ               (AOS_BASIC_BASE + 37)
#define SYS_AOS_IPC_COPY             (AOS_BASIC_BASE + 38)
#define SYS_AOS_PRINT                (AOS_BASIC_BASE + 39)
/* irq */
#define SYS_AOS_IRQ_REG              (AOS_BASIC_BASE + 40)
#define SYS_AOS_IRQ_UNREG            (AOS_BASIC_BASE + 41)
#define SYS_AOS_IRQ_IPI_SEND         (AOS_BASIC_BASE + 42)
#define SYS_AOS_IRQ_ENABLE           (AOS_BASIC_BASE + 43)
#define SYS_AOS_IRQ_DISABLE          (AOS_BASIC_BASE + 44)
#define SYS_AOS_IRQ_IS_ACTIVE        (AOS_BASIC_BASE + 45)
#define SYS_AOS_IRQ_SET_PRIORITY     (AOS_BASIC_BASE + 46)
#define SYS_AOS_IRQ_SET_PENDING      (AOS_BASIC_BASE + 47)
#define SYS_AOS_IRQ_CLEAR_PENDING    (AOS_BASIC_BASE + 48)
#define SYS_AOS_IRQ_ALL_UNREG        (AOS_BASIC_BASE + 49)
#define SYS_AOS_IRQ_GET_ACTIVE       (AOS_BASIC_BASE + 50)
#define SYS_AOS_IRQ_END_INTERRUPT    (AOS_BASIC_BASE + 51)
#define SYS_AOS_IRQ_SET_TYPE         (AOS_BASIC_BASE + 52)
#define SYS_AOS_IRQ_SET_NMI          (AOS_BASIC_BASE + 53)
#define SYS_AOS_IRQ_SET_AFFINITY     (AOS_BASIC_BASE + 54)
#define SYS_AOS_INT_LOCK             (AOS_BASIC_BASE + 55)
#define SYS_AOS_INT_UNLOCK           (AOS_BASIC_BASE + 56)
/* iomap */
#define SYS_AOS_IOMAP_MAP            (AOS_BASIC_BASE + 57)
#define SYS_AOS_IOMAP_UNMAP          (AOS_BASIC_BASE + 58)
#define SYS_AOS_IOMAP_VA2PA          (AOS_BASIC_BASE + 59)
#define SYS_AOS_IOMAP_PA2VA          (AOS_BASIC_BASE + 60)
#define SYS_AOS_MEMMAP_MAP           (AOS_BASIC_BASE + 61)
/* sys info get api */
#define SYS_AOS_MEM_INFO_GET         (AOS_BASIC_BASE + 62)
/*end at 0x43 */
/* ------------------- process & task ------------------*/
#define K_TASK_BASE                   (0x50)

#define SYS_KRHINO_CUR_TASK_GET        (K_TASK_BASE + 0)
#define SYS_KRHINO_TASK_SLEEP          (K_TASK_BASE + 1)
#define SYS_KRHINO_TASK_SUSPEND        (K_TASK_BASE + 2)
#define SYS_KRHINO_TASK_RESUME         (K_TASK_BASE + 3)
#define SYS_KRHINO_TASK_WAIT_ABORT     (K_TASK_BASE + 4)
#define SYS_KRHINO_TASK_YIELD          (K_TASK_BASE + 5)
#define SYS_KRHINO_TASK_PRI_CHANGE     (K_TASK_BASE + 6)
#define SYS_KRHINO_TASK_INFO_SET       (K_TASK_BASE + 7)
#define SYS_KRHINO_TASK_INFO_GET       (K_TASK_BASE + 8)
#define SYS_KRHINO_TASK_NAME_SET       (K_TASK_BASE + 9)
#define SYS_KRHINO_TASK_NAME_GET       (K_TASK_BASE + 10)
#define SYS_KRHINO_TASK_TIME_SLICE_SET (K_TASK_BASE + 11)
#define SYS_KRHINO_TASK_TIME_SLICE_GET (K_TASK_BASE + 12)
#define SYS_KRHINO_UTASK_CREATE        (K_TASK_BASE + 13)
#define SYS_KRHINO_UTASK_DEL           (K_TASK_BASE + 14)
#define SYS_KRHINO_UTASK_COUPLE_DATA   (K_TASK_BASE + 15)
#define SYS_KRHINO_TASK_PTCB_SET       (K_TASK_BASE + 16)
#define SYS_KRHINO_TASK_PTCB_GET       (K_TASK_BASE + 17)
#define SYS_KRHINO_TASK_PRI_GET        (K_TASK_BASE + 18)
#define SYS_KRHINO_TASK_ID_GET         (K_TASK_BASE + 19)

#define SYS_KRHINO_SCHED_POLICY_SET           (K_TASK_BASE + 20)
#define SYS_KRHINO_SCHED_POLICY_GET           (K_TASK_BASE + 21)
#define SYS_KRHINO_SCHED_GET_PRIORITY_MAX     (K_TASK_BASE + 22)
#define SYS_KRHINO_SCHED_GET_PRIORITY_MIN     (K_TASK_BASE + 23)

#define SYS_KRHINO_UPROCESS_CREATE  (K_TASK_BASE + 24)
#define SYS_KRHINO_UPROCESS_EXIT    (K_TASK_BASE + 25)
#define SYS_KRHINO_UPROCESS_LOAD    (K_TASK_BASE + 26)
#define SYS_KRHINO_UPROCESS_RAMLOAD (K_TASK_BASE + 27)
#define SYS_KRHINO_UPROCESS_UNLOAD  (K_TASK_BASE + 28)
#define SYS_KRHINO_UPROCESS_ID_GET  (K_TASK_BASE + 29)
/*end at 0x6d */
/* ------------------- IPC -------------------*/
#define U_IPC_BASE                  (0x70)
#define SYS_KRHINO_MSG_GET          (U_IPC_BASE + 0)
#define SYS_KRHINO_MSG_SND          (U_IPC_BASE + 1)
#define SYS_KRHINO_MSG_RECV         (U_IPC_BASE + 2)
#define SYS_KRHINO_MSG_DEL          (U_IPC_BASE + 3)

#define SYS_KRHINO_IPC_STREAM       (U_IPC_BASE + 4)
#define SYS_KRHINO_IPC_MSG          (U_IPC_BASE + 5)
#define SYS_KRHINO_IPC_FIFO         (U_IPC_BASE + 6)
#define SYS_KRHINO_IPC_SEND         (U_IPC_BASE + 7)
#define SYS_KRHINO_IPC_SENDTO       (U_IPC_BASE + 8)
#define SYS_KRHINO_IPC_SEND_OWNER   (U_IPC_BASE + 9)
#define SYS_KRHINO_IPC_RECV         (U_IPC_BASE + 10)
#define SYS_KRHINO_IPC_CYCLE        (U_IPC_BASE + 11)
#define SYS_KRHINO_IPC_DEL          (U_IPC_BASE + 12)
#define SYS_KRHINO_IPC_SETOPT       (U_IPC_BASE + 13)
#define SYS_KRHINO_IPC_GETOPT       (U_IPC_BASE + 14)
#define SYS_KRHINO_IPC_PERF         (U_IPC_BASE + 15)
/*end at 0x7f */

/* -------------------signal-----------------*/
#define SIGNAL_BASE                  (0x80)
#define SYS_SIGNAL_RETURN            (SIGNAL_BASE + 0)
#define SYS_SIGNAL_KILL              (SIGNAL_BASE + 1)
#define SYS_SIGNAL_TKILL             (SIGNAL_BASE + 2)
#define SYS_SIGNAL_PENDING           (SIGNAL_BASE + 3)
#define SYS_SIGNAL_PROCMASK          (SIGNAL_BASE + 4)
#define SYS_SIGNAL_ACTION            (SIGNAL_BASE + 5)
/*end at 0x85*/

/* ------------------- vfs ------------------*/
#define VFS_BASE             (0x90)
#define SYS_VFS_OPEN        (VFS_BASE + 0)
#define SYS_VFS_CLOSE       (VFS_BASE + 1)
#define SYS_VFS_READ        (VFS_BASE + 2)
#define SYS_VFS_WRITE       (VFS_BASE + 3)
#define SYS_VFS_IOCTL       (VFS_BASE + 4)
#define SYS_VFS_LSEEK       (VFS_BASE + 5)
#define SYS_VFS_FSYNC       (VFS_BASE + 6)
#define SYS_VFS_SYNC        (VFS_BASE + 7)
#define SYS_VFS_STAT        (VFS_BASE + 8)
#define SYS_VFS_FSTAT       (VFS_BASE + 9)
#define SYS_VFS_MMAP        (VFS_BASE + 10)
#define SYS_VFS_MUNMAP      (VFS_BASE + 11)
#define SYS_VFS_LINK        (VFS_BASE + 12)
#define SYS_VFS_UNLINK      (VFS_BASE + 13)
#define SYS_VFS_REMOVE      (VFS_BASE + 14)
#define SYS_VFS_RENAME      (VFS_BASE + 15)
#define SYS_VFS_OPENDIR     (VFS_BASE + 16)
#define SYS_VFS_DIRFD       (VFS_BASE + 17)
#define SYS_VFS_CLOSEDIR    (VFS_BASE + 18)
#define SYS_VFS_READDIR     (VFS_BASE + 19)
#define SYS_VFS_MKDIR       (VFS_BASE + 20)
#define SYS_VFS_RMDIR       (VFS_BASE + 21)
#define SYS_VFS_REWINDDIR   (VFS_BASE + 22)
#define SYS_VFS_TELLDIR     (VFS_BASE + 23)
#define SYS_VFS_SEEKDIR     (VFS_BASE + 24)
#define SYS_VFS_STATFS      (VFS_BASE + 25)
#define SYS_VFS_ACCESS      (VFS_BASE + 26)
#define SYS_VFS_CHDIR       (VFS_BASE + 27)
#define SYS_VFS_GETCWD      (VFS_BASE + 28)
#define SYS_VFS_PATHCONF    (VFS_BASE + 29)
#define SYS_VFS_FPATHCONF   (VFS_BASE + 30)
#define SYS_VFS_UTIME       (VFS_BASE + 31)
#define SYS_VFS_FCNTL       (VFS_BASE + 32)
/* multiplexing io */
#define SYS_EPOLL_CREATE1    (VFS_BASE + 33)
#define SYS_EPOLL_CTL        (VFS_BASE + 34)
#define SYS_EPOLL_WAIT       (VFS_BASE + 35)
#define SYS_AOS_POLL         (VFS_BASE + 36)
#define SYS_AOS_SELECT       (VFS_BASE + 37)
/*end at 0xb5 */
/* -----------------  network  -----------------*/

#define NETWORK_BASE                (0xc0)

#define SYS_NETWORK_ACCEPT             (NETWORK_BASE + 0)
#define SYS_NETWORK_BIND               (NETWORK_BASE + 1)
#define SYS_NETWORK_SHUTDOWN           (NETWORK_BASE + 2)
#define SYS_NETWORK_GETPEERNAME        (NETWORK_BASE + 3)
#define SYS_NETWORK_GETSOCKNAME        (NETWORK_BASE + 4)
#define SYS_NETWORK_GETSOCKOPT         (NETWORK_BASE + 5)
#define SYS_NETWORK_SETSOCKET          (NETWORK_BASE + 6)
#define SYS_NETWORK_CLOSE              (NETWORK_BASE + 7)
#define SYS_NETWORK_CONNECT            (NETWORK_BASE + 8)
#define SYS_NETWORK_LISTEN             (NETWORK_BASE + 9)
#define SYS_NETWORK_RECV               (NETWORK_BASE + 10)
#define SYS_NETWORK_READ               (NETWORK_BASE + 11)
#define SYS_NETWORK_RECVFROM           (NETWORK_BASE + 12)
#define SYS_NETWORK_SEND               (NETWORK_BASE + 13)
#define SYS_NETWORK_SENDMSG            (NETWORK_BASE + 14)
#define SYS_NETWORK_SENDTO             (NETWORK_BASE + 15)
#define SYS_NETWORK_SOCKET             (NETWORK_BASE + 16)
#define SYS_NETWORK_WRITE              (NETWORK_BASE + 17)
#define SYS_NETWORK_WRITEV             (NETWORK_BASE + 18)
#define SYS_NETWORK_SELECT             (NETWORK_BASE + 19)
#define SYS_NETWORK_IOCTL              (NETWORK_BASE + 20)
#define SYS_NETWORK_FCNTL              (NETWORK_BASE + 21)
#define SYS_NETWORK_EVENTFD            (NETWORK_BASE + 22)
#define SYS_NETWORK_TRY_WAKEUP         (NETWORK_BASE + 23)
#define SYS_NETWORK_GETHOSTBYNAME      (NETWORK_BASE + 24)
#define SYS_NETWORK_GETHOSTBYNAME_R    (NETWORK_BASE + 25)
#define SYS_NETWORK_FREEADDRINFO       (NETWORK_BASE + 26)
#define SYS_NETWORK_GETADDRINOF        (NETWORK_BASE + 27)

#define SYS_NETMGR_SERVICE_INIT                   (NETWORK_BASE + 28)
#define SYS_NETMGR_SERVICE_DEINIT                 (NETWORK_BASE + 29)
#define SYS_NETMGR_GET_DEV                        (NETWORK_BASE + 30)
#define SYS_NETMGR_GET_IFCONFIG                   (NETWORK_BASE + 31)
#define SYS_NETMGR_SET_IFCONFIG                   (NETWORK_BASE + 32)
#define SYS_NETMGR_SET_AUTO_RECONNECT             (NETWORK_BASE + 33)
#define SYS_NETMGR_GET_CONFIG                     (NETWORK_BASE + 34)
#define SYS_NETMGR_DEL_CONFIG                     (NETWORK_BASE + 35)
#define SYS_NETMGR_GET_STATE                      (NETWORK_BASE + 36)
#define SYS_NETMGR_CONNECT                        (NETWORK_BASE + 37)
#define SYS_NETMGR_DISCONNECT                     (NETWORK_BASE + 38)
#define SYS_NETMGR_SAVE_CONFIG                    (NETWORK_BASE + 39)
#define SYS_NETMGR_SET_CONNECT_PARAMS             (NETWORK_BASE + 40)
#define SYS_NETMGR_SET_MSG_CB                     (NETWORK_BASE + 41)
#define SYS_NETMGR_DEL_MSG_CB                     (NETWORK_BASE + 42)
#define SYS_NETMGR_WIFI_START_MONITOR             (NETWORK_BASE + 43)
#define SYS_NETMGR_WIFI_STOP_MONITOR              (NETWORK_BASE + 44)
#define SYS_NETMGR_WIFI_SCAN_RESULT               (NETWORK_BASE + 45)
#define SYS_NETMGR_WIFI_START_MGNT_MONITOR        (NETWORK_BASE + 46)
#define SYS_NETMGR_WIFI_STOP_MGNT_MONITOR         (NETWORK_BASE + 47)
#define SYS_NETMGR_WIFI_REGISTER_MGNT_MONITOR_CB  (NETWORK_BASE + 48)
#define SYS_NETMGR_WIFI_SEND_80211_RAW_FRAME      (NETWORK_BASE + 49)
/* end at 0xf1 */
/* -----------------  utils  -----------------*/
#define UTILS_BASE                    (0x100)
/* cli */
#define SYS_CLI_REGISTER_CMD          (UTILS_BASE + 0)
#define SYS_CLI_UNREGISTER_CMD        (UTILS_BASE + 1)
#define SYS_CLI_REGISTER_CMDS         (UTILS_BASE + 2)
#define SYS_CLI_UNREGISTER_CMDS       (UTILS_BASE + 3)
#define SYS_CLI_TASK_SET_CONSOLE      (UTILS_BASE + 4)
/* kv */
#define SYS_KV_SET                    (UTILS_BASE + 5)
#define SYS_KV_GET                    (UTILS_BASE + 6)
#define SYS_KV_DEL                    (UTILS_BASE + 7)
/* debug */
#define SYS_BACKTRACE_NOW            (UTILS_BASE + 8)
#define SYS_DEBUG_FATAL_ERROR        (UTILS_BASE + 9)
#define SYS_DEBUG_CPU_STOP           (UTILS_BASE + 10)
#define SYS_DEBUG_MM_SET_HEAD        (UTILS_BASE + 11)
/* end at 0x113 */
/* ----------------- hal -----------------*/
#define HAL_BASE                 (0x120)
/* hal uart */
#define SYS_HAL_UART_INIT           (HAL_BASE + 0)
#define SYS_HAL_UART_SEND           (HAL_BASE + 1)
#define SYS_HAL_UART_RECV           (HAL_BASE + 2)
#define SYS_HAL_UART_RECV_II        (HAL_BASE + 3)
#define SYS_HAL_UART_FINALIZE       (HAL_BASE + 4)
/* hal flash */
#define SYS_HAL_FLASH_INFO_GET      (HAL_BASE + 5)
#define SYS_HAL_FLASH_ERASE         (HAL_BASE + 6)
#define SYS_HAL_FLASH_WRITE         (HAL_BASE + 7)
#define SYS_HAL_FLASH_READ          (HAL_BASE + 8)
#define SYS_HAL_FLASH_ENABLE_SECURE (HAL_BASE + 9)
#define SYS_HAL_FLASH_DIS_SECURE    (HAL_BASE + 10)
/* hal watchdog */
#define SYS_HAL_WDG_INIT            (HAL_BASE + 11)
#define SYS_HAL_WDG_RELOAD          (HAL_BASE + 12)
#define SYS_HAL_WDG_FINALIZE        (HAL_BASE + 13)
/* end at 0x133 */
#define MAX_SYSCALL_NO (SYS_HAL_WDG_FINALIZE)

#endif /* SYSCALL_NO_H */

