#define HARDWARE_REVISION   "V1.0"
#define MODEL               "ATSAME54-XPRO"

#ifdef BOOTLOADER
#define STDIO_UART 2
#define STDIO_UART_BUADRATE 921600
#else
#define STDIO_UART 2
#define STDIO_UART_BUADRATE 921600
#endif
