#ifndef __CONFIG_H__
#define __CONFIG_H__

#define QSPI_BASE_ADDR  (0x80040000)
#define DDR_RO_SIZE     (0x00600000)
#define PSRAM_BASE_ADDR (0x7E000000)
#define PSRAM_SIZE      (0x00800000)
#define PSRAM_END_MARK  (PSRAM_BASE_ADDR + PSRAM_SIZE)

//PSRAM_BLOCK_1
	//[REGN] DDR_DSP_RO
	//[DESC] DSP image load region
	//[SIZE] 1.5M
	#define MSA_BASE_ADDR   (PSRAM_BASE_ADDR)
	#define MSA_SIZE        (0x00180000)

	//[REGN] PS_CODE_IN_PSRAM & DDR_RW_DATA
	//[DESC] effective essential code running on PSRAM & RW data
	//[SIZE] 4M
	#define PS_CODE_IN_PSRAM_DDR_RW_DATA_TOTAL_SIZE (0x00400000 - 0x00080000)
	#define PS_CODE_IN_PSRAM_BASE  (MSA_BASE_ADDR + MSA_SIZE) 
	#define PS_CODE_IN_PSRAM_SIZE  (0x00100000)
	#define DDR_RW_DATA_BASE_ADDR  (PS_CODE_IN_PSRAM_BASE + PS_CODE_IN_PSRAM_SIZE)
	#define DDR_RW_DATA_SIZE       (PS_CODE_IN_PSRAM_DDR_RW_DATA_TOTAL_SIZE - PS_CODE_IN_PSRAM_SIZE)

	//[REGN] DDR_HEAP
	//[DESC] Os HEAP region
	//[SIZE] 1.5M
	#define DDR_HEAP_BASE_ADDR (PS_CODE_IN_PSRAM_BASE + PS_CODE_IN_PSRAM_DDR_RW_DATA_TOTAL_SIZE)
	#define DDR_HEAP_SIZE      (0x00180000)

//PSRAM_BLOCK_2
	//[REGN] NONCACHE_REGION
	//[DESC] ALL NONCACHE regions
	//[SIZE] 1M
	#define DDR_NONCACHE_AREA_TOTAL_SIZE     (0x00100000 + 0x00080000)
	#define DDR_NONCACHE_AREA_TOTAL_START    (PSRAM_BASE_ADDR + PSRAM_SIZE - DDR_NONCACHE_AREA_TOTAL_SIZE)
	#define DDR_NONCACHE_PS_UL_BASE_ADDR     (DDR_NONCACHE_AREA_TOTAL_START)
	#define DDR_NONCACHE_PS_UL_SIZE          (0x00050000)
	#define DDR_NONCACHE_PS_DL_BASE_ADDR     (DDR_NONCACHE_PS_UL_BASE_ADDR + DDR_NONCACHE_PS_UL_SIZE)
	#define DDR_NONCACHE_PS_DL_SIZE          (0x00028000 + 0x00028000)
	#define PS_NONCACHE_DATA_BASE_ADDR       (DDR_NONCACHE_PS_DL_BASE_ADDR + DDR_NONCACHE_PS_DL_SIZE)
	#define PS_NONCACHE_DATA_SIZE            (0x00070000)
	#define DDR_NONCACHE_BASE_ADDR           (PS_NONCACHE_DATA_BASE_ADDR + PS_NONCACHE_DATA_SIZE)
	#define DDR_NONCACHE_SIZE                (0x00001000)
	#define D2_VECT_BASE_ADDR                (DDR_NONCACHE_BASE_ADDR + DDR_NONCACHE_SIZE)
	#define D2_VECT_SIZE                     (0x00000100)
	#define DDR_PRIVATE_RW_AREA_BASE_ADDR    (D2_VECT_BASE_ADDR + D2_VECT_SIZE)
	#define DDR_PRIVATE_RW_AREA_SIZE         (0x00001400 - D2_VECT_SIZE)
	#define DDR_NONCACHE_USB_BASE_ADDR       (DDR_PRIVATE_RW_AREA_BASE_ADDR + DDR_PRIVATE_RW_AREA_SIZE)
	#define DDR_NONCACHE_USB_SIZE            (DDR_NONCACHE_AREA_TOTAL_SIZE - (DDR_NONCACHE_USB_BASE_ADDR - DDR_NONCACHE_AREA_TOTAL_START))


#define ARBEL_DDR_BASE_ADDR     QSPI_BASE_ADDR
#define DDR_RW_BASE_ADDR        PSRAM_BASE_ADDR
#define DDR_RO_INIT_CODE_SIZE   (0x00001200)
#define DTCM_BASE_ADDR          (0xB0020000)
#define DTCM_SIZE               (0x00010000)

#define SQU_USB_POOL_ADDR       (0xD1001000)
#define SQU_USB_POOL_SIZE       (0x00002000)
#define SQU_USB_DQH_ADDR        (0xD100A000)
#define SQU_USB_DQH_SIZE        (0x00000800)
#define SQU_LTEBMBLOCK_BUF_ADDR (0xD100A800)
#define SQU_LTEBMBLOCK_BUF_SIZE (0x00001000)

#endif
