#ifndef __CONFIG_H__
#define __CONFIG_H__

#include "patition_addr_set.h"

#define QSPI_BASE_ADDR  (0x80040000)
#define DDR_RO_SIZE     (0x00930000)//quectel update    //(0x00800000)
#define PSRAM_BASE_ADDR (0x7E000000)
#define PSRAM_SIZE      (0x01000000)
#define PSRAM_END_MARK  (PSRAM_BASE_ADDR + PSRAM_SIZE)

//PSRAM_BLOCK_1
	//[REGN] DDR_DSP_RO
	//[DESC] DSP image load region
	//[SIZE] 1.5M
	#define MSA_BASE_ADDR   (PSRAM_BASE_ADDR)  // 0x7E000000
	#define DSP_EXP_PSRAM             (0x10000)
	#define MSA_SIZE        (0x00200000 + DSP_EXP_PSRAM)  // 0x210000

	#define KERNEL_RO_START  (MSA_BASE_ADDR + MSA_SIZE)  // 0x7E210000

	#define APP_CODE_START 	(KERNEL_RO_START+KERNEL_RO_SIZE)  // 0x7E955000

	#define KERNEL_RW_START  		(APP_CODE_START + APP_CODE_SIZE)  // 0x7E9A0000

	#define KERNEL_RO_APP_CODE_KERNEL_RW_TOTAL_SIZE (KERNEL_RO_SIZE + KERNEL_RW_SIZE + APP_CODE_SIZE)

	//[REGN] DDR_HEAP
	//[DESC] Os HEAP region
	//[SIZE] 1.5M
	#define KERNEL_HEAP_START 		(KERNEL_RO_START + KERNEL_RO_APP_CODE_KERNEL_RW_TOTAL_SIZE)  // 0x7EC6C000
	
//PSRAM_BLOCK_2
	//[REGN] NONCACHE_REGION
	//[DESC] ALL NONCACHE regions
	//[SIZE] 1M
	#define DDR_NONCACHE_AREA_TOTAL_SIZE     (0x160000-0x19000)  // 0x160000
	#define DDR_NONCACHE_AREA_TOTAL_START    (PSRAM_BASE_ADDR + PSRAM_SIZE - DDR_NONCACHE_AREA_TOTAL_SIZE)
	#define DDR_NONCACHE_PS_UL_BASE_ADDR     (DDR_NONCACHE_AREA_TOTAL_START)
	#define DDR_NONCACHE_PS_UL_SIZE          (0x00050000)
	#define DDR_NONCACHE_PS_DL_BASE_ADDR     (DDR_NONCACHE_PS_UL_BASE_ADDR + DDR_NONCACHE_PS_UL_SIZE)
	#define DDR_NONCACHE_PS_DL_SIZE          (0x00028000 + 0x00028000)
	#define PS_NONCACHE_DATA_BASE_ADDR       (DDR_NONCACHE_PS_DL_BASE_ADDR + DDR_NONCACHE_PS_DL_SIZE)
	#define PS_NONCACHE_DATA_SIZE            (0x00070000)
	#define DDR_NONCACHE_BASE_ADDR           (PS_NONCACHE_DATA_BASE_ADDR + PS_NONCACHE_DATA_SIZE)
	#define DDR_NONCACHE_SIZE                (0x00001000)
	#define D2_VECT_BASE_ADDR                (DDR_NONCACHE_BASE_ADDR + DDR_NONCACHE_SIZE)
	#define D2_VECT_SIZE                     (0x00000100)
	#define DDR_PRIVATE_RW_AREA_BASE_ADDR    (D2_VECT_BASE_ADDR + D2_VECT_SIZE)
	#define DDR_PRIVATE_RW_AREA_SIZE         (0x00001400 - D2_VECT_SIZE)
	#define DDR_NONCACHE_PTABLE_BASE_ADDR    (DDR_PRIVATE_RW_AREA_BASE_ADDR + DDR_PRIVATE_RW_AREA_SIZE)
	#define DDR_NONCACHE_PTABLE_SIZE         (0x00001000)
	#define DDR_NONCACHE_USB_BASE_ADDR       (DDR_NONCACHE_PTABLE_BASE_ADDR + DDR_NONCACHE_PTABLE_SIZE)
	#define DDR_NONCACHE_USB_SIZE            (DDR_NONCACHE_AREA_TOTAL_SIZE - (DDR_NONCACHE_USB_BASE_ADDR - DDR_NONCACHE_AREA_TOTAL_START))  // free: 0x37F80


#define ARBEL_DDR_BASE_ADDR     QSPI_BASE_ADDR
#define DDR_RW_BASE_ADDR        PSRAM_BASE_ADDR
#define DDR_RO_INIT_CODE_SIZE   (0x00001200)
#define DTCM_BASE_ADDR          (0xB0020000)
#define DTCM_SIZE               (0x00010000)

#define SQU_USB_POOL_ADDR       (0xD1001000)
#define SQU_USB_POOL_SIZE       (0x00002000)
#define SQU_USB_DQH_ADDR        (0xD100A000)
#define SQU_USB_DQH_SIZE        (0x00000800)
#define SQU_LTEBMBLOCK_BUF_ADDR (0xD100A800)
#define SQU_LTEBMBLOCK_BUF_SIZE (0x00001000)

#endif

