#ifndef __CONFIG_H__
#define __CONFIG_H__

#define QSPI_BASE_ADDR  (0x80040000)
#define DDR_RO_SIZE     (0x01D00000)
#define PSRAM_BASE_ADDR (0x7E000000)
#define PSRAM_SIZE      (0x01000000)
#define PSRAM_END_MARK  (PSRAM_BASE_ADDR + PSRAM_SIZE)


//PSRAM_BLOCK_1
	//[REGN] DDR_DSP_RO
	//[DESC] DSP image load region
	//[SIZE] DEPENDS
	#define MSA_BASE_ADDR   (PSRAM_BASE_ADDR)
	//DSP_BASE_SIZE
	#ifdef ENABLE_CAT1_LG
	#define DSP_BASE_SIZE        (0x001E0000)
	#else
	#define DSP_BASE_SIZE        (0x00180000)
	#endif
	//L1_WIFI_LOCATION
	#ifdef L1_WIFI_LOCATION
	#define L1_WIFI_LOCATION_COST_SIZE (0x00030000)
	#else
	#define L1_WIFI_LOCATION_COST_SIZE (0x00000000)
	#endif
	//DDR_DSP_RO
	#define MSA_SIZE (DSP_BASE_SIZE + L1_WIFI_LOCATION_COST_SIZE)

	//[REGN] PS_CODE_IN_PSRAM_BASE
	//[DESC] effective essential code execute on side PSRAM
	//[SIZE] 0x000C0000
	#define PS_CODE_IN_PSRAM_BASE  (MSA_BASE_ADDR + MSA_SIZE)
	#define PS_CODE_IN_PSRAM_SIZE  (0x000C0000)

//PSRAM_BLOCK_2
	//[REGN] DDR_RW_DATA & MMI_DATA & HEAP
	//[DESC] RW data and HEAP
	//[SIZE] DEPENDS
	#define DDR_RW_DATA_BASE_ADDR  (PS_CODE_IN_PSRAM_BASE + PS_CODE_IN_PSRAM_SIZE)
	#define DDR_HEAP_GUARD_SIZE    (0x00200000)


//PSRAM_BLOCK_3
	//[REGN] NONCACHE_REGION
	//[DESC] ALL NONCACHE regions
	//[SIZE] 1M
	#define DDR_NONCACHE_AREA_TOTAL_SIZE     (0x00100000 + 0x00080000)
	#define DDR_NONCACHE_AREA_TOTAL_START    (PSRAM_BASE_ADDR + PSRAM_SIZE - DDR_NONCACHE_AREA_TOTAL_SIZE)
	#define DDR_NONCACHE_PS_UL_BASE_ADDR     (DDR_NONCACHE_AREA_TOTAL_START)
	#define DDR_NONCACHE_PS_UL_SIZE          (0x00050000)
	#define DDR_NONCACHE_PS_DL_BASE_ADDR     (DDR_NONCACHE_PS_UL_BASE_ADDR + DDR_NONCACHE_PS_UL_SIZE)
	#define DDR_NONCACHE_PS_DL_SIZE          (0x00028000 + 0x00028000)
	#define PS_NONCACHE_DATA_BASE_ADDR       (DDR_NONCACHE_PS_DL_BASE_ADDR + DDR_NONCACHE_PS_DL_SIZE)
	#define PS_NONCACHE_DATA_SIZE            (0x00070000)
	#define DDR_NONCACHE_BASE_ADDR           (PS_NONCACHE_DATA_BASE_ADDR + PS_NONCACHE_DATA_SIZE)
	#define DDR_NONCACHE_SIZE                (0x00001000)
	#define DDR_NONCACHE_AC_SHARE_BASE_ADDR  (DDR_NONCACHE_BASE_ADDR + DDR_NONCACHE_SIZE)
	#define DDR_NONCACHE_AC_SHARE_SIZE       (0x00014000)
	#define DDR_NONCACHE_AUDIO_BASE_ADDR     (DDR_NONCACHE_AC_SHARE_BASE_ADDR + DDR_NONCACHE_AC_SHARE_SIZE)
	#define DDR_NONCACHE_AUDIO_SIZE          (0x00001000)
	#define DDR_NONCACHE_MEMLOG_BASE_ADDR    (DDR_NONCACHE_AUDIO_BASE_ADDR + DDR_NONCACHE_AUDIO_SIZE)
	#define DDR_NONCACHE_MEMLOG_SIZE         (0x00004000)
	#define DDR_NONCACHE_PTABLE_BASE_ADDR    (DDR_NONCACHE_MEMLOG_BASE_ADDR + DDR_NONCACHE_MEMLOG_SIZE)
	#define DDR_NONCACHE_PTABLE_SIZE         (0x1000)
	#define D2_VECT_BASE_ADDR                (DDR_NONCACHE_PTABLE_BASE_ADDR + DDR_NONCACHE_PTABLE_SIZE)
	#define D2_VECT_SIZE                     (0x00000100)
	#define DDR_PRIVATE_RW_AREA_BASE_ADDR    (D2_VECT_BASE_ADDR + D2_VECT_SIZE)
	#define DDR_PRIVATE_RW_AREA_SIZE         (0x00001400 - D2_VECT_SIZE)
	#define DDR_NONCACHE_USB_BASE_ADDR       (DDR_PRIVATE_RW_AREA_BASE_ADDR + DDR_PRIVATE_RW_AREA_SIZE)
	#define DDR_NONCACHE_USB_SIZE            (DDR_NONCACHE_AREA_TOTAL_SIZE - (DDR_NONCACHE_USB_BASE_ADDR - DDR_NONCACHE_AREA_TOTAL_START))


#define ARBEL_DDR_BASE_ADDR     QSPI_BASE_ADDR
#define DDR_RW_BASE_ADDR        PSRAM_BASE_ADDR
#define DDR_RO_INIT_CODE_SIZE   (0x00001200)
#define DTCM_BASE_ADDR          (0xB0020000)
#define DTCM_SIZE               (0x00010000)

#define SQU_USB_POOL_ADDR       (0xD1001000)
#define SQU_USB_POOL_SIZE       (0x00002000)
#define SQU_USB_DQH_ADDR        (0xD100A000)
#define SQU_USB_DQH_SIZE        (0x00000800)
#define SQU_LTEBMBLOCK_BUF_ADDR (0xD100A800)
#define SQU_LTEBMBLOCK_BUF_SIZE (0x00001000)

#endif
