/**
 *******************************************************************************
 * @file    eq_params.h
 * @brief   EQ parameters (type,f0,Q,sqrtA) for the follow EQ styles.
 *          The parameters's data format of (f0, Q, sqrtA) are Q16.0, Q6.10, and
 *          Q6.10 respectively.
 *
 * @author  Auto Generated by Parametric Equalizer Plot Software
 * @version V1.2.0
 *
 * $Created: 2015-06-04T15:38:44$:
 *
 * &copy; Shanghai Mountain View Silicon Technology Co.,Ltd. All rights reserved.
 *******************************************************************************
 */

#ifndef __EQ_PARAMS_H__
#define __EQ_PARAMS_H__

#ifdef  __cplusplus
extern "C" {
#endif//__cplusplus

#include "type.h"

#define EQ_STYLE_CNT         10 /* Count of total EQ style */
#define EQ_STYLE_SUM         EQ_STYLE_CNT
#define EQ_REG_START_ADDR    0x12
#define EQ_MAX_IIC_DATA_SIZE (2 + 2 + 2 * 4 * 10)

/**
 * @brief  Select the "Id"-th EQ style
 * @param  SamplingRate sample rate
 * @param  Id the selected EQ style ID, its defination as follow:
 *    @arg 0: CLASSICAL
 *    @arg 1: VOCAL BOOSTER
 *    @arg 2: FLAT
 *    @arg 3: BASS BOOSTER
 *    @arg 4: BASS REDUCER
 *    @arg 5: TREBLE BOOSTER
 *    @arg 6: TREBLE REDUCER
 *    @arg 7: POP
 *    @arg 8: ROCK
 *    @arg 9: JAZZ
 * @return NONE
 */
void EqStyleSelect(uint16_t SamplingRate, uint32_t Id);

/**
 * @brief EQ style parameters to IIC data
 *
 * @Id  the selected EQ style ID, @see EqStyleSelect
 * @Buf IIC data buffer, max length is EQ_MAX_IIC_DATA_SIZE
 *
 * @return IIC data length, unit in BYTE, max value is EQ_MAX_IIC_DATA_SIZE
 *
 * @note Usage example as follows
 *    //1. Get EQ mode
 *    uint16_t EqMode;//Big Endian
 *    I2cReadNByte(I2cHandle, SlaveAddr, EQ_REG_START_ADDR, &EqMode, 2);
 *
 *    //2. Disable EQ and Config EQ parameters
 *    Len = EqStyleConvert2I2CData(Id, Buf);
 *    I2cWriteNByte(I2cHandle, SlaveAddr, EQ_REG_START_ADDR, Buf, Len);
 *
 *    //3. Enable EQ in EqMode
 *    EqMode &= 0x00C0;
 *    EqMode |= *((uint16_t*)Buf);
 *    I2cWriteNByte(I2cHandle, SlaveAddr, EQ_REG_START_ADDR, &EqMode, 2);
 */
uint32_t EqStyleConvert2I2CData(uint32_t Id, uint8_t Buf[EQ_MAX_IIC_DATA_SIZE]);

#ifdef  __cplusplus
}
#endif//__cplusplus

#endif//__EQ_PARAMS_H__
