
## 第一部分： 基础信息
name: haas1000                                    # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: master                                   # <必选项> 组件版本号
description: driver & sdk for platform/mcu haas1000          # <必选项> 建议至少20字以上
type: chip                                          # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 核心模块                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - base
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - armv7m: master
  - rhino: master
  - libc_stub: master
  - osal_aos: master
  - i2c: master
  - spi: master
  - flash: master
  - gpio: master
  - uart: master
  - flash: master
  - pwm: master
  - adc: master
  - timer: master
  - watchdog: master
## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  cflag: >
        -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -g -Os
        -DSECURE_BOOT -DHAAS_OTA_ENABLED=1 -DHAAS_OTA_BIN_VER=\"HAAS_AOS_3.1\"
        -DCHIP=haas1000 -DKERNEL=RHINO -DCHIP_HAAS1000_ARCH_ENHANCE -DCHIP_HAAS1000 -DMIC_SAMPLERATE=48000 -DMIC_PERIOD_MS=48 -DFLASH_SIZE=0x1000000 -DCRASH_DUMP_SECTION_SIZE=0
        -DAUD_SECTION_SIZE=0 -DUSERDATA_SECTION_SIZE=0x1000 -DFACTORY_SECTION_SIZE=0x1000
        -DNV_REC_DEV_VER=2 -DREVISION_INFO=x -DCHIP_HAS_UART=3 -DRESAMPLE_ANY_SAMPLE_RATE -DCHIP_HAS_TRANSQ -DRTOS=1
        -DCQ_FUNC_ATTR= -DDEBUG=1 -DREL_TRACE_ENABLE -DLWIP_ETHERNETIF=1 -DLWIP_SUPPORT=0 -DPERSIST_DATA_SECTION_SIZE=0x1000 -std=gnu11 -fno-common -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer
  cxxflag: >
          -D_GLIBCXX_HAS_GTHREADS -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DCHIP=haas1000 -DKERNEL=RHINO -DCHIP_HAAS1000_ARCH_ENHANCE -DCHIP_HAAS1000 -DMIC_SAMPLERATE=48000 -DMIC_PERIOD_MS=48
          -DAUD_SECTION_SIZE=0 -DUSERDATA_SECTION_SIZE=0x1000 -DFACTORY_SECTION_SIZE=0x1000
          -DFLASH_SIZE=0x1000000  -DCRASH_DUMP_SECTION_SIZE=0
          -DSECURE_BOOT -DHAAS_OTA_ENABLED=1 -DHAAS_OTA_BIN_VER=\"HAAS_AOS_3.1\"
          -DNV_REC_DEV_VER=2 -DREVISION_INFO=x -DCHIP_HAS_UART=3 -DRESAMPLE_ANY_SAMPLE_RATE -DCHIP_HAS_TRANSQ -DRTOS=1
          -DCQ_FUNC_ATTR= -DDEBUG=1 -DREL_TRACE_ENABLE -DLWIP_ETHERNETIF=1 -DLWIP_SUPPORT=0 -DPERSIST_DATA_SECTION_SIZE=0x1000 -DCHIP_HAS_TRANSQ -DCHIP_HAS_UART=3 -DRTOS=1 -DDISABLE_CLI_MULTI_CONSOLE=0
          -std=gnu++11 -fsigned-char -fno-common -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fpermissive -DSNTP_PERIODIC_SYNC_INTERVAL_MS=3600000
          -g -Os
  ldflag: -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -nostartfiles --specs=nosys.specs -Wl,-Map="aos.map"
  asmflag: >
          -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -g -Os
          -DCHIP=haas1000 -DKERNEL=RHINO -DCHIP_HAAS1000_ARCH_ENHANCE -DCHIP_HAAS1000 -DMIC_SAMPLERATE=48000 -DMIC_PERIOD_MS=48
          -DMIC_PERIOD_MS=48 -c -x assembler-with-cpp
  postimage_script: release/auto_build_tool/build_bin.py

  include:
    - hal/2ndboot/
    - aos/
    - aos/arch/
    - drivers/platform/hal/
    - drivers/platform/cmsis/inc/
    - drivers/rtos/rhino/cmsis/
    - drivers/utils/hwtimer_list/
    - drivers/platform/hal/haas1000/
    - drivers/services/wifi_app/alsa_adapter
    - drivers/net/

  internal_include:
    - drivers/services/nv_section/include/
    - drivers/platform/drivers/bt/
    - drivers/services/wifi_app/audio_dec/
    - drivers/services/audioflinger/
    - drivers/net/lwip/src/include/netif/ppp/
    - drivers/net/
    - drivers/apps/common/
    - drivers/services/wifi_app/sniffer/
    - drivers/services/a7_dsp/
    - drivers/services/nvrecord/
    - drivers/platform/drivers/ana/
  libs:
    - mcuhaas1000
  libpath:
    - drivers

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - "hal/wdg.c"
  - "hal/spi.c"
  - "hal/uart.c"
  # "hal/i2s.c"
  # - "hal/usbd.c"
  - "hal/timer.c"
  - hal/wifi_port.c ? <AOS_COMP_WIFI>
  - "hal/adc.c"
  - "hal/pwm.c"
  - "hal/i2c.c"
  - "hal/sd.c"
  - "hal/flash.c"
  - "hal/gpio.c"
  - "csi/iic.c"
  - "csi/wdt.c"
  # - "hal/2ndboot/wdg.c"
  # - "hal/2ndboot/sys.c"
  # - "hal/2ndboot/uart.c"
  # - "hal/2ndboot/boot_ringbuffer.c"
  # - "hal/2ndboot/startup.c"
  # - "hal/2ndboot/flash.c"
  - "aos/hook_impl.c"
  #- "aos/my_cpp_test.cpp"
  - "aos/soc_init.c"
  - "aos/ota_port.c"
  - "aos/aos.c"
  - "drivers/utils/build_info/build_info.c"
  - "drivers/utils/boot_struct/boot_struct.c"
  - "aos/dsp/dsp.S"
  - hal/audio.c ? <CONFIG_A7_DSP_ENABLE>

## 第五部分：配置信息
# def_config:                              # 组件的可配置项
#   CONFIG_DEBUG: y
#   CONFIG_PARAM_NOT_CHECK: y
#   CONFIG_CLI: y
def_config:
  SWD_ENABLE_AS_DEFAULT: 1
#  CONFIG_CSI_V1: 1
#  CONFIG_CSI: "csi1.0"
  CONFIG_LWIP_VERSION: "lwip2.0.0"
  CONFIG_LWIP_V200: y
  __FPU_PRESENT: 1
  CMSIS_DSP_LIB: 1
  # hardware module numbers config - used in VFS drivers
  CONFIG_ADC_NUM: 2
  CONFIG_DAC_NUM: 0
  CONFIG_GPIO_NUM: 40
  CONFIG_U_I2C_CORE: 1
  CONFIG_U_I2C_DEV: 1
  CONFIG_I2C_NUM: 2
  CONFIG_PWM_NUM: 2
  CONFIG_QSPI_NUM: 0
  CONFIG_SPI_NUM: 2
  CONFIG_TIMER_NUM: 1
  CONFIG_UART_NUM: 3
  CONFIG_U_FLASH_DEV: 1
  CONFIG_U_WDG_DEV: 1
  CONFIG_U_WDG_CORE: 1
  SUPPORT_SET_DRIVER_TRACE_FLAG: 1

chip:
  arch_name: arm
  cpu_name: cortex-m4
  vendor_name: alibaba IoT
  ld_script: _haas1000_alios_sec_b.lds

hw_info:
  arch_name: arm
  cpu_name: cortex-m4
  toolchain_prefix: arm-none-eabi
  vendor_name: alibaba IoT
  ld_script: _haas1000_alios_sec_b.lds
  flash_program: release/aos_burn_tool/flash_program.py
  # program_data_files:
  #   - filename: release/write_flash_tool/ota_bin/littlefs.bin
  #     address: 0xB32000

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include"
    source:
      - hal/2ndboot/*.h
      - aos/*.h
      - aos/arch/*.h
      - drivers/platform/hal/*.h
      - drivers/platform/cmsis/inc/*.h
      - drivers/rtos/rhino/cmsis/*.h
      - drivers/utils/hwtimer_list/*.h
      - drivers/platform/hal/haas1000/*.h
      - drivers/services/wifi_app/alsa_adapter/*.h
  - dest: "lib"
    source:
      - drivers/libmcuhaas1000.a


## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
