console.log('system version is: ' + system.version())
console.log('system platform is: ' + system.platform())
console.log('system uptime is: ' + system.uptime())
console.log('system heapTotal is: ' + system.memory().heapTotal)
console.log('system heapUsed is: ' + system.memory().heapUsed)
