/**
 * Copyright (C) 2018 Alibaba.inc, All rights reserved.
 *
 * @file AGWakeupWord.h
 * @brief wakeup word definition
 * @author lifen.lf@alibaba-inc.com
 * @data 2018/04/07
 * @version 1.0
 */

#ifndef AG_WAKEUP_WORD_H
#define AG_WAKEUP_WORD_H

/**
 * \brief wakeup word type
 */
typedef enum {
    AG_WW_TYPE_GLOBAL=1,    /**< global type vaild all the time */
    AG_WW_TYPE_SCREENON,    /**< valid when screen on, only valid for display devices */
    AG_WW_TYPE_LOCAL,        /**< valid for some scence, depend on your design */
    AG_WW_TYPE_DYNAMIC        /**< valid for dynamic wakeup word settings */
} AGWakeupWordType;

/**
 * \brief wakeup word name, end with the phonetic of the wakeup word
 */
typedef enum {
    AG_WW_NAME_INVALID = 0,
    AG_WW_NAME_TIANMAOJINGLING=1,
    AG_WW_NAME_NIHAOTIANMAO,
    AG_WW_NAME_JINGLINGTUICHU,
    AG_WW_NAME_JINGLINGZANTING,
    AG_WW_NAME_SHENGYINDAYIDIAN,
    AG_WW_NAME_SHENGYINXIAOYIDIAN,
    AG_WW_NAME_XIAYISHOU,
    AG_WW_NAME_WOYAOKAN,
    AG_WW_NAME_WOYAOTING,
    AG_WW_NAME_XIAYIGE,
    AG_WW_NAME_SHANGYIYE,
    AG_WW_NAME_XIAYIYE,
    AG_WW_NAME_HUANYIPI,
    AG_WW_NAME_FANHUI,
    AG_WW_NAME_KANZHENGPIAN,
    AG_WW_NAME_ZANTING,
    AG_WW_NAME_BOFANG,
    AG_WW_NAME_QUANPING,
    AG_WW_NAME_KUAIJIN,
    AG_WW_NAME_KUAITUI,
    AG_WW_NAME_SHANGYIJI,
    AG_WW_NAME_XIAYIJI,
    AG_WW_NAME_DAKAI,
    AG_WW_NAME_SHANGYISHOU,
    AG_WW_NAME_SHANGYIGE,
    AG_WW_NAME_JINGLINGFANHUI,
    AG_WW_NAME_DAKAIDI,
    AG_WW_NAME_TIANJIASHOUCANG,
    AG_WW_NAME_QUXIAOSHOUCANG,
    AG_WW_NAME_ZANTINGBOFANG,
    AG_WW_NAME_JIXUBOFANG,
    AG_WW_NAME_ZENGDAYINLIANG,
    AG_WW_NAME_JIANXIAOYINLIANG,
    AG_WW_NAME_DADIANSHENG,
    AG_WW_NAME_XIAODIANSHENG,
    AG_WW_NAME_DAKAIDITU,
    AG_WW_NAME_DAKAIYINYUE,
    AG_WW_NAME_DAKAIDIANTAI,
    AG_WW_NAME_DAKAICAIDAN,
    AG_WW_NAME_FANGDADITU,
    AG_WW_NAME_SUOXIAODITU,
    AG_WW_NAME_GUANBILUKUANG,
    AG_WW_NAME_DAKAILUKUANG,
    AG_WW_NAME_HEIYEMOSHI,
    AG_WW_NAME_BAITIANMOSHI,
    AG_WW_NAME_CHETOUXIANGSHANG,
    AG_WW_NAME_ZHENGBEIXIANGSHANG,
    AG_WW_NAME_CHAKANQUANCHENG,
    AG_WW_NAME_TUICHUQUANCHENG,
    AG_WW_NAME_TUICHUDAOHANG,
    AG_WW_NAME_DIYIGE,
    AG_WW_NAME_DIERGE,
    AG_WW_NAME_DISANGE,
    AG_WW_NAME_DISIGE,
    AG_WW_NAME_DIWUGE,
    AG_WW_NAME_DILIUGE,
    AG_WW_NAME_DIQIGE,
    AG_WW_NAME_DIBAGE,
    AG_WW_NAME_DIJIUGE,
    AG_WW_NAME_DISHIGE,
    AG_WW_NAME_DIYITIAO,
    AG_WW_NAME_DIERTIAO,
    AG_WW_NAME_DISANTIAO,
    AG_WW_NAME_KAISHIDAOHANG,
    AG_WW_NAME_QUEDING,
    AG_WW_NAME_QUXIAO,
    AG_WW_NAME_DANQUXUNHUAN,
    AG_WW_NAME_SHUNXUXUNHUAN,
    AG_WW_NAME_SUIJIBOFANG,
    AG_WW_NAME_KAISHIBOFANG,
    AG_WW_NAME_FOR_ALL_DYNAMIC
} AGWakeupWordName;

#endif
