#
# Automatically generated file; DO NOT EDIT.
# Main Menu
#

#
# Configure Link Kit SDK for IoT Embedded Devices
#
FEATURE_SRCPATH="."
# FEATURE_WITH_FAC_JSON_FLOW is not set
# FEATURE_UTILS_LITE_CJSON is not set
# FEATURE_UTILS_JSON_PARSER is not set
# FEATURE_UTILS_HTTPC is not set
# FEATURE_UTILS_BASE64 is not set
FEATURE_UTILS_STRING=y
# FEATURE_UTILS_MD5 is not set
# FEATURE_UTILS_SHA1 is not set
FEATURE_UTILS_SHA256=y
# FEATURE_UTILS_EVENT is not set
FEATURE_MQTT_COMM_ENABLED=y
FEATURE_HAL_TCP=y

#
# MQTT Configurations
#
FEATURE_MQTT_DIRECT=y
# FEATURE_MQTT_SHADOW is not set
# FEATURE_MQTT_LOGPOST is not set
# FEATURE_DEVICE_MODEL_ENABLED is not set
# FEATURE_DYNAMIC_REGISTER is not set
# FEATURE_COAP_COMM_ENABLED is not set
# FEATURE_OTA_ENABLED is not set
# FEATURE_HTTP_COMM_ENABLED is not set
# FEATURE_SAL_ENABLED is not set
# FEATURE_HTTP2_COMM_ENABLED is not set
# FEATURE_SUPPORT_TLS is not set
# FEATURE_SUPPORT_ITLS is not set
