// Automatically generated by makemoduledefs.py.

#if (MICROPY_PY_AIAGENT)
    extern const struct _mp_obj_module_t aiagent_module;
    #define MODULE_DEF_MP_QSTR_AIAGENT { MP_ROM_QSTR(MP_QSTR_aiagent), MP_ROM_PTR(&aiagent_module) },
#else
    #define MODULE_DEF_MP_QSTR_AIAGENT
#endif

#if (MICROPY_PY_ALIYUNIOT)
    extern const struct _mp_obj_module_t mp_module_aliyunIoT;
    #define MODULE_DEF_MP_QSTR_ALIYUNIOT { MP_ROM_QSTR(MP_QSTR_aliyunIoT), MP_ROM_PTR(&mp_module_aliyunIoT) },
#else
    #define MODULE_DEF_MP_QSTR_ALIYUNIOT
#endif

#if (MICROPY_PY_AUDIO)
    extern const struct _mp_obj_module_t mp_module_audio;
    #define MODULE_DEF_MP_QSTR_AUDIO { MP_ROM_QSTR(MP_QSTR_audio), MP_ROM_PTR(&mp_module_audio) },
#else
    #define MODULE_DEF_MP_QSTR_AUDIO
#endif

#if (MICROPY_PY_BLE)
    extern const struct _mp_obj_module_t mp_module_ble;
    #define MODULE_DEF_MP_QSTR_BLE { MP_ROM_QSTR(MP_QSTR_ble), MP_ROM_PTR(&mp_module_ble) },
#else
    #define MODULE_DEF_MP_QSTR_BLE
#endif

#if (MICROPY_PY_BLECFG)
    extern const struct _mp_obj_module_t mp_module_blecfg;
    #define MODULE_DEF_MP_QSTR_BLECFG { MP_ROM_QSTR(MP_QSTR_blecfg), MP_ROM_PTR(&mp_module_blecfg) },
#else
    #define MODULE_DEF_MP_QSTR_BLECFG
#endif

#if (MICROPY_PY_DRIVER)
    extern const struct _mp_obj_module_t driver_module;
    #define MODULE_DEF_MP_QSTR_DRIVER { MP_ROM_QSTR(MP_QSTR_driver), MP_ROM_PTR(&driver_module) },
#else
    #define MODULE_DEF_MP_QSTR_DRIVER
#endif

#if (MICROPY_PY_HTTP)
    extern const struct _mp_obj_module_t mp_module_http;
    #define MODULE_DEF_MP_QSTR_HTTP { MP_ROM_QSTR(MP_QSTR_http), MP_ROM_PTR(&mp_module_http) },
#else
    #define MODULE_DEF_MP_QSTR_HTTP
#endif

#if (MICROPY_PY_KV)
    extern const struct _mp_obj_module_t mp_module_kv;
    #define MODULE_DEF_MP_QSTR_KV { MP_ROM_QSTR(MP_QSTR_kv), MP_ROM_PTR(&mp_module_kv) },
#else
    #define MODULE_DEF_MP_QSTR_KV
#endif

#if (MICROPY_PY_LVGL)
    extern const struct _mp_obj_module_t mp_module_lodepng;
    #define MODULE_DEF_MP_QSTR_LODEPNG { MP_ROM_QSTR(MP_QSTR_lodepng), MP_ROM_PTR(&mp_module_lodepng) },
#else
    #define MODULE_DEF_MP_QSTR_LODEPNG
#endif

#if (MICROPY_PY_LVGL)
    extern const struct _mp_obj_module_t mp_module_lvgl;
    #define MODULE_DEF_MP_QSTR_LVGL { MP_ROM_QSTR(MP_QSTR_lvgl), MP_ROM_PTR(&mp_module_lvgl) },
#else
    #define MODULE_DEF_MP_QSTR_LVGL
#endif

#if (MICROPY_PY_LVGL)
    extern const struct _mp_obj_module_t mp_module_lvgl_display;
    #define MODULE_DEF_MP_QSTR_LVGL_DISPLAY { MP_ROM_QSTR(MP_QSTR_lvgl_display), MP_ROM_PTR(&mp_module_lvgl_display) },
#else
    #define MODULE_DEF_MP_QSTR_LVGL_DISPLAY
#endif

#if (MICROPY_PY_MACHINE)
    extern const struct _mp_obj_module_t mp_module_machine;
    #define MODULE_DEF_MP_QSTR_MACHINE { MP_ROM_QSTR(MP_QSTR_machine), MP_ROM_PTR(&mp_module_machine) },
#else
    #define MODULE_DEF_MP_QSTR_MACHINE
#endif

#if (MICROPY_PY_MINICV)
    extern const struct _mp_obj_module_t minicv_module;
    #define MODULE_DEF_MP_QSTR_MINICV { MP_ROM_QSTR(MP_QSTR_minicv), MP_ROM_PTR(&minicv_module) },
#else
    #define MODULE_DEF_MP_QSTR_MINICV
#endif

#if (MICROPY_PY_MODBUS)
    extern const struct _mp_obj_module_t mp_module_modbus;
    #define MODULE_DEF_MP_QSTR_MODBUS { MP_ROM_QSTR(MP_QSTR_modbus), MP_ROM_PTR(&mp_module_modbus) },
#else
    #define MODULE_DEF_MP_QSTR_MODBUS
#endif

#if (MICROPY_PY_OSS)
    extern const struct _mp_obj_module_t oss_module;
    #define MODULE_DEF_MP_QSTR_OSS { MP_ROM_QSTR(MP_QSTR_oss), MP_ROM_PTR(&oss_module) },
#else
    #define MODULE_DEF_MP_QSTR_OSS
#endif

#if (MICROPY_PY_OTA)
    extern const struct _mp_obj_module_t mp_module_ota;
    #define MODULE_DEF_MP_QSTR_OTA { MP_ROM_QSTR(MP_QSTR_ota), MP_ROM_PTR(&mp_module_ota) },
#else
    #define MODULE_DEF_MP_QSTR_OTA
#endif

#if (MICROPY_PY_SNTP)
    extern const struct _mp_obj_module_t sntp_module;
    #define MODULE_DEF_MP_QSTR_SNTP { MP_ROM_QSTR(MP_QSTR_sntp), MP_ROM_PTR(&sntp_module) },
#else
    #define MODULE_DEF_MP_QSTR_SNTP
#endif

#if (MICROPY_PY_ARRAY)
    extern const struct _mp_obj_module_t mp_module_uarray;
    #define MODULE_DEF_MP_QSTR_UARRAY { MP_ROM_QSTR(MP_QSTR_uarray), MP_ROM_PTR(&mp_module_uarray) },
#else
    #define MODULE_DEF_MP_QSTR_UARRAY
#endif

#if (MICROPY_PY_UCAMERA)
    extern const struct _mp_obj_module_t ucamera_module;
    #define MODULE_DEF_MP_QSTR_UCAMERA { MP_ROM_QSTR(MP_QSTR_ucamera), MP_ROM_PTR(&ucamera_module) },
#else
    #define MODULE_DEF_MP_QSTR_UCAMERA
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_AIAGENT \
    MODULE_DEF_MP_QSTR_ALIYUNIOT \
    MODULE_DEF_MP_QSTR_AUDIO \
    MODULE_DEF_MP_QSTR_BLE \
    MODULE_DEF_MP_QSTR_BLECFG \
    MODULE_DEF_MP_QSTR_DRIVER \
    MODULE_DEF_MP_QSTR_HTTP \
    MODULE_DEF_MP_QSTR_KV \
    MODULE_DEF_MP_QSTR_LODEPNG \
    MODULE_DEF_MP_QSTR_LVGL \
    MODULE_DEF_MP_QSTR_LVGL_DISPLAY \
    MODULE_DEF_MP_QSTR_MACHINE \
    MODULE_DEF_MP_QSTR_MINICV \
    MODULE_DEF_MP_QSTR_MODBUS \
    MODULE_DEF_MP_QSTR_OSS \
    MODULE_DEF_MP_QSTR_OTA \
    MODULE_DEF_MP_QSTR_SNTP \
    MODULE_DEF_MP_QSTR_UARRAY \
    MODULE_DEF_MP_QSTR_UCAMERA \
// MICROPY_REGISTERED_MODULES
