/*******************************************************
 *         MVSilicon Audio Effects Parameters          *
 *   The File is Auto Generated by ACPWorkbench V6.0   *
 *              Firmware Version: 6.1                  *
 *                All Right Reserved                   *
 *******************************************************/

#ifndef __AUDIO_EFFECTS_H__
#define __AUDIO_EFFECTS_H__

#ifdef  __cplusplus
extern "C" {
#endif//__cplusplus

#define AUDIO_EFFECT_VERSION_DRC               (010307)
#define AUDIO_EFFECT_VERSION_VB                (030100)
#define AUDIO_EFFECT_VERSION_3D                (030000)
#define AUDIO_EFFECT_VERSION_PS                (010300)

#define AUDIO_EFFECT_PARAM_DRC_THRESHHOLD      (-0)
#define AUDIO_EFFECT_PARAM_DRC_RATIO           (1)
#define AUDIO_EFFECT_PARAM_DRC_ATTACK_TIME     (10)
#define AUDIO_EFFECT_PARAM_DRC_RELEASE_TIME    (60)
#define AUDIO_EFFECT_PARAM_DRC_CROSSOVER_FREQ  (0)
#define AUDIO_EFFECT_PARAM_VB_CUTOFF_FREQ      (100)
#define AUDIO_EFFECT_PARAM_VB_HIGH_FREQ        (1500)
#define AUDIO_EFFECT_PARAM_VB_LIMITER_EN       (1)
#define AUDIO_EFFECT_PARAM_VB_INTENSITY        (35)
#define AUDIO_EFFECT_PARAM_VB_PREGAIN          (32768)
#define AUDIO_EFFECT_PARAM_VB_POSTGAIN         (32768)
#define AUDIO_EFFECT_PARAM_3D_DEPTH            (60)
#define AUDIO_EFFECT_PARAM_3D_PREGAIN          (32768)
#define AUDIO_EFFECT_PARAM_3D_POSTGAIN         (32768)
#define AUDIO_EFFECT_PARAM_3D_MID_BOOST        (1)
#define AUDIO_EFFECT_PARAM_3D_BASS             (1)
#define AUDIO_EFFECT_PARAM_PS_SEMITONE_STEP    (0)
#define AUDIO_EFFECT_PARAM_PS_FRAME_SIZE       (400)

//DRC (Dynamic Range Compression) usage
//init_drc(&drc, channels, sample_rate, AUDIO_EFFECT_PARAM_DRC_THRESHHOLD, 0, AUDIO_EFFECT_PARAM_DRC_RATIO, AUDIO_EFFECT_PARAM_DRC_ATTACK_TIME, AUDIO_EFFECT_PARAM_DRC_RELEASE_TIME, AUDIO_EFFECT_PARAM_DRC_CROSSOVER_FREQ);
//apply_drc(&drc, pcm_in, pcm_out, pcm_size);

//VB (Virtual Bass) usage
//init_vb_nld_iir(&vb, channels, sample_rate, AUDIO_EFFECT_PARAM_VB_CUTOFF_FREQ, AUDIO_EFFECT_PARAM_VB_HIGH_FREQ, AUDIO_EFFECT_PARAM_VB_LIMITER_EN);
//apply_vb_nld_iir(&vb, pcm_in, pcm_out, pcm_size, AUDIO_EFFECT_PARAM_VB_INTENSITY, AUDIO_EFFECT_PARAM_VB_PREGAIN, AUDIO_EFFECT_PARAM_VB_POSTGAIN);

//3D usage
//init_3d(&threed, channels, sample_rate, AUDIO_EFFECT_PARAM_3D_BASS, AUDIO_EFFECT_PARAM_3D_MID_BOOST);
//apply_3d(&threed, pcm_in, pcm_out, pcm_size, AUDIO_EFFECT_PARAM_3D_DEPTH, AUDIO_EFFECT_PARAM_3D_PREGAIN, AUDIO_EFFECT_PARAM_3D_POSTGAIN);

//PS (Pitch Shifter) usage
//init_pitch_shifter(&ps, channels, sample_rate, AUDIO_EFFECT_PARAM_PS_SEMITONE_STEP, AUDIO_EFFECT_PARAM_PS_FRAME_SIZE);
//apply_pitch_shifter(&ps, pcm_in, pcm_out);

#ifdef  __cplusplus
}
#endif//__cplusplus

#endif//__AUDIO_EFFECTS_H__
