console.log('system versions().module is: ' + system.versions().module)
console.log('system version is: ' + system.version())
console.log('system appversion is: ' + system.appversion())
console.log('system getSystemInfo().userjsVersion is: ' + system.getSystemInfo().userjsVersion)
console.log('system getSystemInfo().appVersion is: ' + system.getSystemInfo().appVersion)
console.log('system getSystemInfo().kernelVersion is: ' + system.getSystemInfo().kernelVersion)
console.log('system getSystemInfo().systemVersion is: ' + system.getSystemInfo().systemVersion)
console.log('system getSystemInfo().buildTime is: ' + system.getSystemInfo().buildTime)
console.log('system getSystemInfo().hardwareVersion is: ' + system.getSystemInfo().hardwareVersion)
console.log('system platform is: ' + system.platform())
console.log('system uptime is: ' + system.uptime())
console.log('system heapTotal is: ' + system.memory().heapTotal)
console.log('system heapUsed is: ' + system.memory().heapUsed)
console.log('system heapFree is: ' + system.memory().heapFree)
console.log('system gc is: ' + system.gc())
console.log('system reboot: ' + system.reboot())