#ifndef __CSI_CONFIG_H__
#define __CSI_CONFIG_H__
#define CONFIG_ARCH_RV64 1
#define CONFIG_CPU_C910D 1
#define CONFIG_RV64_CORETIM 1
#define CONFIG_SYSTEM_SECURE 1
#define CONFIG_CHIP_SMARTH_RV64 1
#define CONFIG_BOARD_SMARTH_C910_EVB 1
#define CONFIG_BOARD_NAME_STR "smarth_c906_evb"
#define CONFIG_KERNEL_RHINO 1
#define CONFIG_HAVE_VIC 1
#define CONFIG_ARCH_INTERRUPTSTACK 4096
#define CONFIG_NEWLIB_WRAP 1
#define CONFIG_USER_DEFINED_LD_DIR_STR ""
#endif
