/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Mon Nov  5 09:56:33 2018. */

#include "lsoc.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t InfData_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, InfData, version, version, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, InfData, device, version, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, InfData, state, device, 0),
    PB_LAST_FIELD
};

const pb_field_t AtsCmdData_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, AtsCmdData, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t AtsFilData_fields[5] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, AtsFilData, cmd, cmd, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, AtsFilData, path, cmd, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, AtsFilData, attribute, path, 0),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, AtsFilData, signature, attribute, 0),
    PB_LAST_FIELD
};

const pb_field_t AtsNetData_fields[2] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, AtsNetData, cmd, cmd, 0),
    PB_LAST_FIELD
};

const pb_field_t AtsSysData_fields[2] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, AtsSysData, cmd, cmd, 0),
    PB_LAST_FIELD
};

const pb_field_t AtsDevData_fields[2] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, AtsDevData, cmd, cmd, 0),
    PB_LAST_FIELD
};

const pb_field_t AtsEndData_fields[4] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, AtsEndData, cmd, cmd, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, AtsEndData, total, cmd, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, AtsEndData, sum, total, 0),
    PB_LAST_FIELD
};

const pb_field_t MesCmdData_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, MesCmdData, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t MesFilData_fields[4] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, MesFilData, cmd, cmd, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, MesFilData, sum, cmd, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, MesFilData, mac, sum, 0),
    PB_LAST_FIELD
};

const pb_field_t MesNetData_fields[4] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, MesNetData, cmd, cmd, 0),
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , OTHER, MesNetData, sum, cmd, 0),
    PB_FIELD(  3, STRING  , SINGULAR, STATIC  , OTHER, MesNetData, mac, sum, 0),
    PB_LAST_FIELD
};

const pb_field_t MesEndData_fields[3] = {
    PB_FIELD(  1, UINT64  , SINGULAR, STATIC  , FIRST, MesEndData, cmd, cmd, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, MesEndData, total, cmd, 0),
    PB_LAST_FIELD
};

const pb_field_t Message_fields[11] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Message, domain, domain, 0),
    PB_FIELD(  2, UENUM   , SINGULAR, STATIC  , OTHER, Message, code, domain, 0),
    PB_FIELD(  3, UINT64  , SINGULAR, STATIC  , OTHER, Message, timestamp, code, 0),
    PB_ONEOF_FIELD(data,   4, MESSAGE , ONEOF, STATIC  , OTHER, Message, infData, timestamp, &InfData_fields),
    PB_ONEOF_FIELD(data,   5, MESSAGE , ONEOF, STATIC  , UNION, Message, atsCmdData, timestamp, &AtsCmdData_fields),
    PB_ONEOF_FIELD(data,   6, MESSAGE , ONEOF, STATIC  , UNION, Message, atsEndData, timestamp, &AtsEndData_fields),
    PB_ONEOF_FIELD(data,   7, MESSAGE , ONEOF, STATIC  , UNION, Message, atsFilData, timestamp, &AtsFilData_fields),
    PB_ONEOF_FIELD(data,  11, MESSAGE , ONEOF, STATIC  , UNION, Message, mesCmdData, timestamp, &MesCmdData_fields),
    PB_ONEOF_FIELD(data,  12, MESSAGE , ONEOF, STATIC  , UNION, Message, mesEndData, timestamp, &MesEndData_fields),
    PB_ONEOF_FIELD(data,  13, MESSAGE , ONEOF, STATIC  , UNION, Message, mesFilData, timestamp, &MesFilData_fields),
    PB_LAST_FIELD
};






/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Message, data.infData) < 65536 && pb_membersize(Message, data.atsCmdData) < 65536 && pb_membersize(Message, data.atsEndData) < 65536 && pb_membersize(Message, data.atsFilData) < 65536 && pb_membersize(Message, data.mesCmdData) < 65536 && pb_membersize(Message, data.mesEndData) < 65536 && pb_membersize(Message, data.mesFilData) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_InfData_AtsCmdData_AtsFilData_AtsNetData_AtsSysData_AtsDevData_AtsEndData_MesCmdData_MesFilData_MesNetData_MesEndData_Message)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Message, data.infData) < 256 && pb_membersize(Message, data.atsCmdData) < 256 && pb_membersize(Message, data.atsEndData) < 256 && pb_membersize(Message, data.atsFilData) < 256 && pb_membersize(Message, data.mesCmdData) < 256 && pb_membersize(Message, data.mesEndData) < 256 && pb_membersize(Message, data.mesFilData) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_InfData_AtsCmdData_AtsFilData_AtsNetData_AtsSysData_AtsDevData_AtsEndData_MesCmdData_MesFilData_MesNetData_MesEndData_Message)
#endif


/* @@protoc_insertion_point(eof) */
