REM Example cmake command.
cmake -DBASICMATH=OFF ^
-DCOMPLEXMATH=OFF ^
-DCONTROLLER=OFF ^
-DFASTMATH=OFF ^
-DFILTERING=ON ^
-DMATRIX=OFF ^
-DSTATISTICS=OFF ^
-DSUPPORT=OFF ^
-DTRANSFORM=OFF ^
-DCONFIGTABLE=ON ^
-DARM_LMS_NORM_Q15=ON ^
-DCMAKE_TOOLCHAIN_FILE=../../../../armcc.cmake ^
-DNEON=ON ^
-DARM_CPU="cortex-a5" ^
-G "Unix Makefiles" ..