/*
 * Copyright (C) 2019-2020 Alibaba Group Holding Limited
 */

#ifndef _SL_CONFIG_H_
#define _SL_CONFIG_H_

//#define AWSS_DISABLE_ENROLLEE
#define AWSS_DISABLE_REGISTRAR
#define AWSS_SUPPORT_APLIST
#define AWSS_SUPPORT_DEV_AP
#define AWSS_SUPPORT_SMARTCONFIG
#define AWSS_SUPPORT_SMARTCONFIG_MCAST
#define AWSS_SUPPORT_SMARTCONFIG_WPS
#define COAP_SERV_MULTITHREAD
#define DEVICE_MODEL_ENABLED
#define DEV_BIND_ENABLED
#define FORCE_SSL_VERIFY
// #define LOG_REPORT_TO_CLOUD
#define MQTT_AUTO_SUBSCRIBE
#define MQTT_COMM_ENABLED
#define MQTT_DIRECT
#define SDK_DEBUG_LEVEL_NONE
#define SUPPORT_TLS
#define WIFI_PROVISION_ENABLED
#define INFRA_AES
#define HAL_CRYPTO
#define CONFIG_RUNTIME_LOG_LEVEL 2
//#define CONFIG_BLDTIME_MUTE_DBGLOG 1
//#define AWSS_SUPPORT_AHA

#endif
