NAME := smpapp

$(NAME)_SOURCES := smpapp.c

GLOBAL_DEFINES += AOS_NO_WIFI  LOG_LOCAL_LEVEL=4 RHINO_CONFIG_CPU_NUM=2

GLOBAL_ASMFLAGS += -DRHINO_CONFIG_CPU_NUM=2

OS_MUTICORE_NUM := 2

$(NAME)_COMPONENTS := yloop cli

ifeq ($(BENCHMARKS),1)
$(NAME)_COMPONENTS  += benchmarks
GLOBAL_DEFINES      += CONFIG_CMD_BENCHMARKS
endif

GLOBAL_INCLUDES += ./