TARGET = libqrencode.a
MODULE = qrencode

MOD_SOURCES := \
		qrencode.c \
		qrinput.c \
		bitstream.c \
		qrspec.c \
		rsecc.c \
		split.c \
		mask.c \
		mqrspec.c \
		mmask.c 

MOD_INCLUDES := \
		. \
		../../ui/aui/libs/lvgl/


include $(TOOLS_DIR)/rules.mk
