NAME := board_rv32m1_vega

JTAG := jlink_jtag

HOST_ARCH           := RI5CY
HOST_MCU_FAMILY     := rv32m1

CONFIG_SYSINFO_PRODUCT_MODEL := ALI_AOS_RV32M1
CONFIG_SYSINFO_DEVICE_NAME := RV32M1
GLOBAL_CFLAGS += -DSYSINFO_PRODUCT_MODEL=\"$(CONFIG_SYSINFO_PRODUCT_MODEL)\"
GLOBAL_CFLAGS += -DSYSINFO_DEVICE_NAME=\"$(CONFIG_SYSINFO_DEVICE_NAME)\"
GLOBAL_CFLAGS += -DSYSINFO_ARCH=\"$(HOST_ARCH)\"
GLOBAL_CFLAGS += -DSYSINFO_MCU=\"$(HOST_MCU_FAMILY)\"
GLOBAL_CFLAGS += -DCONFIG_NO_TCPIP
GLOBAL_CFLAGS += -DTEST_CONFIG_STACK_SIZE=1024
GLOBAL_LDFLAGS +=

GLOBAL_INCLUDES += .
GLOBAL_INCLUDES += ../../platform/mcu/rv32m1/
GLOBAL_INCLUDES += ../../platform/mcu/rv32m1/drivers


$(NAME)_SOURCES     :=
$(NAME)_SOURCES     += ./board.c
$(NAME)_SOURCES     += ./clock_config.c
$(NAME)_SOURCES     += ./pin_mux.c

TEST_COMPONENTS += certificate
GLOBAL_CFLAGS += -DTEST_CONFIG_KV_ENABLED=0
GLOBAL_CFLAGS += -DTEST_CONFIG_YLOOP_ENABLED=1
