EXTRA_POST_BUILD_TARGETS += gen_standard_images

MOC_APP_BIN_OUTPUT_FILE := $(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=$(BIN_OUTPUT_SUFFIX))
MOC_ALL_BIN_OUTPUT_FILE := $(MOC_APP_BIN_OUTPUT_FILE)
TMP_OTA_BIN_OUTPUT_FILE := $(OTA_OUTPUT_DIR)/$(notdir $(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.ota$(BIN_OUTPUT_SUFFIX)))
OTA_OUTPUT_DIR := $(OUTPUT_DIR)/binary/ota

BOOT_BIN_FILE :=$(SOURCE_ROOT)/board/pca10040/pca10040_boot.bin

MOC_OTA_BIN_OUTPUT_FILE :=$(OTA_OUTPUT_DIR)/$(subst @,_,$(notdir $(TMP_OTA_BIN_OUTPUT_FILE)))

BOOT_OFFSET:= 0x0
APP_OFFSET := 0x10000

# Required to build Full binary file
GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT:= $(SCRIPTS_PATH)/gen_common_bin_output_file.py

gen_standard_images:
	mkdir -p $(OTA_OUTPUT_DIR)
	$(QUIET)$(CP) $(MOC_APP_BIN_OUTPUT_FILE) $(MOC_OTA_BIN_OUTPUT_FILE)
	$(QUIET)$(RM) $(MOC_APP_BIN_OUTPUT_FILE)
	$(QUIET)$(ECHO) Generate ALL Standard Flash Images: $(MOC_ALL_BIN_OUTPUT_FILE)
	$(QUIET)$(RM) $(MOC_ALL_BIN_OUTPUT_FILE)
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(MOC_ALL_BIN_OUTPUT_FILE) -f $(BOOT_OFFSET) $(BOOT_BIN_FILE)
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(MOC_ALL_BIN_OUTPUT_FILE) -f $(APP_OFFSET) $(MOC_OTA_BIN_OUTPUT_FILE)
