
#reset
set $psr=0xc0000000
set *(int*)0x42010300=0x03

##Load dsp
#download ihex verify=no $(ProjectPath)generated/dsp.hex

##Load imtb
download ihex verify=no $(ProjectPath)generated/imtb.hex

##Load bmtb
download ihex verify=no $(ProjectPath)generated/bmtb.hex

##Load bootloader binary
download ihex verify=no $(ProjectPath)generated/boot.hex

##Load kv binary
#download ihex verify=no $(ProjectPath)generated/kv.hex

##Load yoc binary
download ihex verify=no $(ProjectPath)generated/prim.hex

