
## 第一部分： 基础信息
name: ucloud_ai                                         # <必选项> 包名称 （符合C语言变量命名规则），长度少于等于64字节
version: master                                     # <必选项> 组件版本号
description: 云端AI推理引擎，支持阿里云视觉智能开放平台     # <必选项> 建议至少20字以上
type: common                                        # <必选项> 组件类型，为：solution, chip, board, common, sdk

tag: 通用组件                                       # <可选项> 组件分类，缺省值： ''
keywords:                                           # <可选项> 标签，会影响到组件被搜索的效果，合理的标签很重要
  - ucloud AI
license: Apache license v2.0                        # <可选项> 源代码的许可证，要确保所有代码、文件的许可证不冲突。如：MIT，Apache license v2.0，BSD

## 第二部分：依赖信息
#           指定该组件依赖的组件及版本，版本支持条件比较，支持：>=v1.0, >v1.0, ==v1.0, <=v1.0, <v1.0, v1.0
#           未指定条件时，默认为 ==，如 v1.0 与 ==v1.0
# depends:                                 # <可选项> 该组件依赖其他的组件，合理的依赖才能保证组件能编译、使用
#   - minilibc: v7.2.0
#   - aos: >=v7.2.0
depends:
  - oss: master
  - http: master
  - mbedtls: master
  - jsoncpp: master

## 第四部分：编译连接信息
# build_config:                            # <可选项> 编译配置项
#   include:                               # <可选项> 编译时，影响编译器的-I 参数 ,全局有效
#     - src                                #        include 只能是该软件包下的目录，不能使用外部目录
#   internal_include:                      # <可选项> 编译时，影响编译器的-I 参数 ,组件内有效
#     - include
#   cflag: ''                              # <可选项> C 编译器所需要要的编译参数
#   cxxflag: ''                            # <可选项> CXX 编译器所需要要的编译参数
#   asmflag: ''                            # <可选项> 汇编器所需要要参数
#   define:                                # <可选项> 宏定义, 增加编译器的-D 选项,如：
#     XXX: 1                               #   -DXXX=1
#     AAA: 1                               #   -DAAA
#     STR: "abc"                           #   -DSTR="abc"
#   libs:                                  # 该组件中支持的二进制静态库,如：libxxx.a, libyyy.a
#     - xxx                                #   -lxxx
#     - yyy                                #   -lyyy
#   libpath:                               # 指定静态库所在的路径（相对于该组件路径）
#     - libs                               #   -Llibs
build_config:
  include:
    - include
    - src/model/aliyun-openapi/core/include
    - src/model/aliyun-openapi/core/src
    - src/model/aliyun-openapi/facebody/include
    - src/model/aliyun-openapi/imagerecog/include
    - src/model/aliyun-openapi/imageseg/include
    - src/model/aliyun-openapi/imageenhan/include
    - src/model/aliyun-openapi/objectdet/include
    - src/model/aliyun-openapi/ocr/include
    - ./
#  prebuild_script: cp_resources.py

# source_file:                             # <可选项> 指定参与编译的源代码文件，支持通配符，采用相对路径
#   - src/*.c                              # 例：组件 src 目录下所有的扩展名为 c 的源代码文件
source_file:
  - src/model/aliyun-openapi/core/src/*.cc                        # 阿里云SDK组件核心
  - src/model/aliyun-openapi/core/src/location/*.cc
  - src/model/aliyun-openapi/core/src/location/model/*.cc
  - src/model/aliyun-openapi/facebody/src/*.cc ? <CONFIG_ALICLOUD_FACEBODY_ENABLE>
  - src/model/aliyun-openapi/facebody/src/model/*.cc ? <CONFIG_ALICLOUD_FACEBODY_ENABLE>
  - src/model/aliyun-openapi/imagerecog/src/*.cc ? <CONFIG_ALICLOUD_IMAGERECOG_ENABLE>
  - src/model/aliyun-openapi/imagerecog/src/model/*.cc ? <CONFIG_ALICLOUD_IMAGERECOG_ENABLE>
  - src/model/aliyun-openapi/imageseg/src/*.cc ? <CONFIG_ALICLOUD_IMAGESEG_ENABLE>
  - src/model/aliyun-openapi/imageseg/src/model/*.cc ? <CONFIG_ALICLOUD_IMAGESEG_ENABLE>
  - src/model/aliyun-openapi/imageenhan/src/*.cc ? <CONFIG_ALICLOUD_IMAGEENHAN_ENABLE>
  - src/model/aliyun-openapi/imageenhan/src/model/*.cc ? <CONFIG_ALICLOUD_IMAGEENHAN_ENABLE>
  - src/model/aliyun-openapi/objectdet/src/*.cc ? <CONFIG_ALICLOUD_OBJECTDET_ENABLE>
  - src/model/aliyun-openapi/objectdet/src/model/*.cc ? <CONFIG_ALICLOUD_OBJECTDET_ENABLE>
  - src/model/aliyun-openapi/ocr/src/*.cc ? <CONFIG_ALICLOUD_OCR_ENABLE>
  - src/model/aliyun-openapi/ocr/src/model/*.cc ? <CONFIG_ALICLOUD_OCR_ENABLE>
  - src/model/facebody.cc ? <CONFIG_ALICLOUD_FACEBODY_ENABLE>
  - src/model/imageenhan.cc ? <CONFIG_ALICLOUD_IMAGEENHAN_ENABLE>
  - src/model/imagerecog.cc ? <CONFIG_ALICLOUD_IMAGERECOG_ENABLE>
  - src/model/imageseg.cc ? <CONFIG_ALICLOUD_IMAGESEG_ENABLE>
  - src/model/objectdet.cc ? <CONFIG_ALICLOUD_OBJECTDET_ENABLE>
  - src/model/ocr.cc ? <CONFIG_ALICLOUD_OCR_ENABLE>
  - src/model/common.cc
  - src/ucloud_ai_facebody.c ? <CONFIG_ALICLOUD_FACEBODY_ENABLE>
  - src/ucloud_ai_imageenhan.c ? <CONFIG_ALICLOUD_IMAGEENHAN_ENABLE>
  - src/ucloud_ai_imagerecog.c ? <CONFIG_ALICLOUD_IMAGERECOG_ENABLE>
  - src/ucloud_ai_imageseg.c ? <CONFIG_ALICLOUD_IMAGESEG_ENABLE>
  - src/ucloud_ai_objectdet.c ? <CONFIG_ALICLOUD_OBJECTDET_ENABLE>
  - src/ucloud_ai_ocr.c ? <CONFIG_ALICLOUD_OCR_ENABLE>
  - src/ucloud_ai_common.c
#  - example/ucloud_ai_example.c

## 第五部分：配置信息
def_config:                              # 组件的可配置项
  CONFIG_ALICLOUD_FACEBODY_ENABLE: 1
  CONFIG_ALICLOUD_IMAGERECOG_ENABLE: 1
  CONFIG_ALICLOUD_IMAGEENHAN_ENABLE: 1
  CONFIG_ALICLOUD_OBJECTDET_ENABLE: 1
  CONFIG_ALICLOUD_IMAGESEG_ENABLE: 1
  CONFIG_ALICLOUD_OCR_ENABLE: 1
  USE_CRYPTO_MBEDTLS: 1

  # OSS 配置信息, 用户在这里替换自己的OSS信息
  OSS_ACCESS_KEY: "Your-Access-Key"
  OSS_ACCESS_SECRET: "Your-Access-Secret"
  OSS_ENDPOINT: "Your-OSS-Endpoint"      # 例如: "oss-cn-shanghai-internal.aliyuncs.com"
  OSS_BUCKET: "Your-OSS-Bucket"          # 例如: "cloud-ai-dev"

## 第六部分：安装信息
# install:
#   - dest: include/                       # 安装的目的路径 dest是相当路径，通常是相对于YoC SDK 安装目录
#     source:                              # 安装源列表
#      - src/*.h                           # 支持通配符，相对路径
install:
  - dest: "include/"
    source:
      - "include/*.h"

## 第七部分：导出部分
# export:
#   - dest: "<SOLUTION_PATH>/generated/data" # 安装的目的路径 dest是相当路径
#     source:                                # 安装源列表
#       - "bootimgs/boot"
#       - "bootimgs/tee"
#       - "bootimgs/mtb"
#       - "configs/config.yaml"
