/*
 * rx65n_macio.h
 *
 *  Created on: 2018年3月21日
 *      Author: gilbe
 */

#ifndef PLATFORM_MCU_R5F565NE_RX65N_MACRO_H_
#define PLATFORM_MCU_R5F565NE_RX65N_MACRO_H_

#define SYSINFO_OS_VERSION "APP-1.0.3"
#define SYSINFO_PRODUCT_MODEL "ALI_AOS_RX65"
#define SYSINFO_DEVICE_NAME "RX65N"
#define SYSINFO_KERNEL_VERSION "AOS-R-1.2.1"
#define SYSINFO_APP_VERSION "APP-1.0.5"
#define AOS_WEAK
#define AOS_packed
#define __FUNCTION__ __func__
#define CONFIG_GUIDER_AUTH_TIMEOUT  (10 * 1000)

#endif /* PLATFORM_MCU_R5F565NE_RX65N_MACRO_H_ */
