
add_definitions(-DCONFIG_AOS_LWIP=y -DPLATFORM_HAS_STDINT=y)
include_directories(${AOSROOTDIR}/kernel/rhino/include)
include_directories(${AOSROOTDIR}/hardware/arch/armv7m/include)
include_directories(${AOSROOTDIR}/hardware/chip/haas1000/drivers/platform/cmsis/inc)
include_directories(${AOSROOTDIR}/hardware/board/haas100/config)
include_directories(${AOSROOTDIR}/hardware/chip/haas1000/aos)
include_directories(${AOSROOTDIR}/hardware/chip/haas1000/aos/arch)
include_directories(${AOSROOTDIR}/hardware/chip/haas1000/drivers/rtos/cmsis)
include_directories(${AOSROOTDIR}/components/cli/include)
include_directories(${AOSROOTDIR}/components/uservice/include)
include_directories(${AOSROOTDIR}/components/mbedtls/include)
include_directories(${AOSROOTDIR}/components/mbedtls/platform/include)
include_directories(${AOSROOTDIR}/components/drivers/peripheral/uart/include)
include_directories(${AOSROOTDIR}/components/vfs/include)
include_directories(${AOSROOTDIR}/components/osal_aos/include)
include_directories(${AOSROOTDIR}/components/netmgr/include)
include_directories(${AOSROOTDIR}/components/lwip/include)
include_directories(${AOSROOTDIR}/components/lwip/lwip2.0.0/include)
include_directories(${AOSROOTDIR}/components/amp/components/linkkit/infra)
include_directories(${AOSROOTDIR}/components/amp/components/linkkit)
include_directories(${AOSROOTDIR}/components/amp/components/kv/include)
include_directories(${AOSROOTDIR}/components/amp/main)
include_directories(${AOSROOTDIR}/components/amp/utils/cJSON)
include_directories(${AOSROOTDIR}/components/amp/components)
include_directories(${AOSROOTDIR}/components/amp/components/linkkit/dev_model)

