
EXTRA_POST_BUILD_TARGETS += mkimage

SOURCE_BIN = $(SOURCE_ROOT)out/$(CLEANED_BUILD_STRING)/binary/$(CLEANED_BUILD_STRING).bin
SECBOOT_IMG = $(SOURCE_ROOT)/$($(HOST_MCU_FAMILY)_LOCATION)/drivers/tools/secboot.img
VERSION_TXT = $(SOURCE_ROOT)/$($(HOST_MCU_FAMILY)_LOCATION)/drivers/tools/version.txt
TOOLS_DIR = $(SOURCE_ROOT)/$($(HOST_MCU_FAMILY)_LOCATION)/drivers/tools
OUT_DIR = $(SOURCE_ROOT)out/$(CLEANED_BUILD_STRING)/binary/


mkimage:	
	$(OBJDUMP) -S $(SOURCE_ROOT)out/$(CLEANED_BUILD_STRING)/binary/$(CLEANED_BUILD_STRING).elf > $(OUT_DIR)System.asm	
	$(TOOLS_DIR)/makeimg $(SOURCE_BIN) $(OUT_DIR)WM_W600.img 0 0 $(VERSION_TXT) E000
	$(TOOLS_DIR)/makeimg $(SOURCE_BIN) $(OUT_DIR)WM_W600_SEC.img 0 0 $(VERSION_TXT) 7E800
	$(TOOLS_DIR)/makeimg_all $(SECBOOT_IMG) $(OUT_DIR)WM_W600.img $(OUT_DIR)WM_W600.FLS

