#ifndef _PLATFORM_CONF_H_
#define _PLATFORM_CONF_H_

#define LITTLEFS_CNT 2
#define PROG_SIZE 4096
#define PAGE_NUMS_ON_BLOCK 64
#define DATA_BLOCK_NUMS 192
#define SYSTEM_BLOCK_NUMS 256

#endif /* _PLATFORM_CONF_H_ */
