// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "5429689-dirty"
#define MICROPY_GIT_HASH "5429689-dirty"
#define MICROPY_BUILD_DATE "2019-06-20"
#define MICROPY_VERSION_MAJOR 1
#define MICROPY_VERSION_MINOR 11
#define MICROPY_VERSION_MICRO 0
#define MICROPY_VERSION_STRING "1.11.0"
#define MICROPY_PY_SYS_PLATFORM "AliOS Things"

