#ifndef _CACHE_CFG_H
#define _CACHE_CFG_H
/*
 * Cache Option
 */
#if ( !defined(__NDS32_ISA_V3M__)  && defined(CONFIG_CACHE_SUPPORT ) )
#define CONFIG_CPU_ICACHE_ENABLE 1
//#undef CONFIG_CPU_DCACHE_ENABLE
#define CONFIG_CPU_DCACHE_ENABLE 1
#else
#undef CONFIG_CPU_ICACHE_ENABLE
#undef CONFIG_CPU_DCACHE_ENABLE
#endif

//#define CONFIG_CPU_DCACHE_WRITETHROUGH 1
//#undef CONFIG_CPU_DCACHE_WRITETHROUGH
#undef CONFIG_CHECK_RANGE_ALIGNMENT
#undef CONFIG_CACHE_L2
#undef CONFIG_FULL_ASSOC

#endif
