/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* UART1_SCB_IRQ */
#define UART1_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART1_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART1_SCB_IRQ__INTC_NUMBER 42u
#define UART1_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART1_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART1_SCB_IRQ_INTC_NUMBER 42u

/* UART5_SCB_IRQ */
#define UART5_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define UART5_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define UART5_SCB_IRQ__INTC_NUMBER 46u
#define UART5_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define UART5_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define UART5_SCB_IRQ_INTC_NUMBER 46u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
