#This abstracts the generated source files in the design. DO NOT EDIT. This document is generated by PSoC Creator design builds.

GEN_SOURCE_DIR= Generated_Source/PSoC6

GEN_C_SOURCE_CortexM0p=\

GEN_ASM_SOURCE_CortexM0p=\

GEN_SEP_C_SOURCE_CortexM0p=\
	$(GEN_SOURCE_DIR)/cyfitter_sysint_cfg.c\
	$(GEN_SOURCE_DIR)/cyfitter_cfg.c\
	$(GEN_SOURCE_DIR)/cymetadata.c\
	$(GEN_SOURCE_DIR)/UART5.c\
	$(GEN_SOURCE_DIR)/UART1.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/sysint/cy_sysint.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/ipc/cy_ipc_drv.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/ipc/cy_ipc_sema.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/ipc/cy_ipc_pipe.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/sysclk/cy_sysclk.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/wdt/cy_wdt.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_common.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_i2c.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_ezi2c.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_spi.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_uart.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/efuse/cy_efuse.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/flash/cy_flash.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/gpio/cy_gpio.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/sysanalog/cy_sysanalog.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/syspm/cy_syspm.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/syslib/cy_syslib.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/syslib/gcc/cy_syslib_gcc.S\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/trigmux/cy_trigmux.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/systick/cy_systick.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/profile/cy_profile.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/prot/cy_prot.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/lvd/cy_lvd.c\
	$(GEN_SOURCE_DIR)/pdl/middleware/ble/cy_ble_clk.c

GEN_LIBS_CortexM0p=\


GEN_C_SOURCE_CortexM4=\

GEN_ASM_SOURCE_CortexM4=\

GEN_SEP_C_SOURCE_CortexM4=\
	$(GEN_SOURCE_DIR)/cyfitter_sysint_cfg.c\
	$(GEN_SOURCE_DIR)/cymetadata.c\
	$(GEN_SOURCE_DIR)/UART5.c\
	$(GEN_SOURCE_DIR)/UART1.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/sysint/cy_sysint.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/ipc/cy_ipc_drv.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/ipc/cy_ipc_sema.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/ipc/cy_ipc_pipe.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/sysclk/cy_sysclk.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/wdt/cy_wdt.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_common.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_i2c.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_ezi2c.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_spi.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/scb/cy_scb_uart.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/efuse/cy_efuse.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/flash/cy_flash.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/gpio/cy_gpio.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/sysanalog/cy_sysanalog.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/syspm/cy_syspm.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/syslib/cy_syslib.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/syslib/gcc/cy_syslib_gcc.S\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/trigmux/cy_trigmux.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/systick/cy_systick.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/profile/cy_profile.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/prot/cy_prot.c\
	$(GEN_SOURCE_DIR)/pdl/drivers/peripheral/lvd/cy_lvd.c\
	$(GEN_SOURCE_DIR)/pdl/middleware/ble/cy_ble_clk.c\

GEN_LIBS_CortexM4=\

