cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/bootloader.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/cfg.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/common.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/cp.sh .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/crypto.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/efuse.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/efuseapi.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/hwmac.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/idmanage.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/iotapi.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/mbox.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/n10.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/netstack_wrapper.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/osal.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/phy.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/pinmux.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/security.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/soc_init.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/softmac.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/sys.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/timer.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/tmr.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/udhcp.a .
cp ../../../../alios_out/linkkitapp@sv6266_evb/libraries/wdt.a .

