/*
 * Copyright (C) 2015-2018 Alibaba Group Holding Limited
 */



#ifndef _IOTX_DM_CONFIG_H_
#define _IOTX_DM_CONFIG_H_

#define IOTX_DM_CLIENT_CONNECT_TIMEOUT_MS     (10000)
#define IOTX_DM_CLIENT_SUB_RETRY_MAX_COUNTS   (3)
#define IOTX_DM_CLIENT_SUB_TIMEOUT_MS         (5000)
#define IOTX_DM_CLIENT_REQUEST_TIMEOUT_MS     (2000)
#define IOTX_DM_CLIENT_KEEPALIVE_INTERVAL_MS  (30000)

#endif