#ifndef U_CONFIG_H
#define U_CONFIG_H

#ifndef RHINO_CONFIG_DYN_SYSCALL_TBL
#define RHINO_CONFIG_DYN_SYSCALL_TBL    0
#endif /* RHINO_CONFIG_DYN_SYSCALL_TBL */

#ifndef RHINO_CONFIG_URES
#define RHINO_CONFIG_URES               1
#endif /* RHINO_CONFIG_URES */

#ifndef RHINO_CONFIG_UTIMER
#define RHINO_CONFIG_UTIMER             1
#endif /* RHINO_CONFIG_UTIMER */

#ifndef RHINO_CONFIG_UCLI
#define RHINO_CONFIG_UCLI               0
#endif /* RHINO_CONFIG_UCLI */

#ifndef RHINO_CONFIG_UFS
#define RHINO_CONFIG_UFS                0
#endif /* RHINO_CONFIG_UFS */

#ifndef RHINO_CONFIG_UTCPIP
#define RHINO_CONFIG_UTCPIP             0
#endif /* RHINO_CONFIG_UTCPIP */

#ifndef RHINO_CONFIG_ULINKKIT
#define RHINO_CONFIG_ULINKKIT           0
#endif /* RHINO_CONFIG_ULINKKIT */

#ifndef RHINO_CONFIG_UCALLBACK
#define RHINO_CONFIG_UCALLBACK          0
#endif

/*----------------- HAL ----------------*/
#ifndef RHINO_CONFIG_HAL_ADC_SYSCALL
#define RHINO_CONFIG_HAL_ADC_SYSCALL        0
#endif /* RHINO_CONFIG_HAL_ADC_SYSCALL */

#ifndef RHINO_CONFIG_HAL_DAC_SYSCALL
#define RHINO_CONFIG_HAL_DAC_SYSCALL        0
#endif /* RHINO_CONFIG_HAL_DAC_SYSCALL */

#ifndef RHINO_CONFIG_HAL_FLASH_SYSCALL
#define RHINO_CONFIG_HAL_FLASH_SYSCALL      0
#endif /* RHINO_CONFIG_HAL_FLASH_SYSCALL */

#ifndef RHINO_CONFIG_HAL_GPIO_SYSCALL
#define RHINO_CONFIG_HAL_GPIO_SYSCALL       0
#endif /* RHINO_CONFIG_HAL_GPIO_SYSCALL */

#ifndef RHINO_CONFIG_HAL_I2C_SYSCALL
#define RHINO_CONFIG_HAL_I2C_SYSCALL        0
#endif /* RHINO_CONFIG_HAL_I2C_SYSCALL */

#ifndef RHINO_CONFIG_HAL_NAND_SYSCALL
#define RHINO_CONFIG_HAL_NAND_SYSCALL       0
#endif /* RHINO_CONFIG_HAL_NAND_SYSCALL */

#ifndef RHINO_CONFIG_HAL_NOR_SYSCALL
#define RHINO_CONFIG_HAL_NOR_SYSCALL        0
#endif /* RHINO_CONFIG_HAL_NOR_SYSCALL */

#ifndef RHINO_CONFIG_HAL_RTC_SYSCALL
#define RHINO_CONFIG_HAL_RTC_SYSCALL        0
#endif /* RHINO_CONFIG_HAL_RTC_SYSCALL */

#ifndef RHINO_CONFIG_HAL_SD_SYSCALL
#define RHINO_CONFIG_HAL_SD_SYSCALL         0
#endif /* RHINO_CONFIG_HAL_SD_SYSCALL */

#ifndef RHINO_CONFIG_HAL_SPI_SYSCALL
#define RHINO_CONFIG_HAL_SPI_SYSCALL        0
#endif /* RHINO_CONFIG_HAL_SPI_SYSCALL */

#ifndef RHINO_CONFIG_HAL_UART_SYSCALL
#define RHINO_CONFIG_HAL_UART_SYSCALL       1
#endif

#endif /* U_CONFIG_H */

