/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SCB3.h"
#include "SCB3_SPI_UART.h"
#include "SCB3_PINS.h"
#include "SCB3_SPI_UART_PVT.h"
#include "SCB3_PVT.h"
#include "SCB3_BOOT.h"
#include "SCB3_SCBCLK.h"
#include "SCB3_tx.h"
#include "SCB3_tx_aliases.h"
#include "SCB3_SCB_IRQ.h"
#include "SCB3_rx.h"
#include "SCB3_rx_aliases.h"
#include "cy_em_eeprom.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

