#!/bin/bash
echo "Making cmake_comp"
library_path=$1
host_os=$2
toolchan_path=$3
config_file=$4
origin_path="$(pwd)"
comp_path="$( cd "$(dirname "$0")" ; pwd -P )"
echo origin_path: $origin_path
echo comp_path: $comp_path

# include config.mk to import variables
python ./build/scripts/aos_configmk_convert.py ${config_file} ${config_file}.sh
source ${config_file}.sh
rm -f ${config_file}.sh

# enter into component path
cd $comp_path
if [ $? -ne 0 ]; then
    echo "cd fail!"
    exit 1
fi

# add your specific build command, and set the path of library generated by
# third party build tools
cd cmake_test
if [ ! -d "build" ]; then
    mkdir build
fi 
cd build

if [ ! -f "Makefile" ]; then
    cmake .. -DCMAKE_C_COMPILER="$origin_path/${toolchan_path}gcc" -DCMAKE_CXX_COMPILER="$origin_path/${toolchan_path}g++" -DCMAKE_BUILD_FLAGS="$AOS_SDK_LDFLAGS" -DCMAKE_C_FLAGS="$AOS_SDK_CFLAGS" -DCMAKE_CXX_FLAGS="$AOS_SDK_CFLAGS"
fi

make

libraries="./lib/libhello.a"

# copy library to AliOS-Things library folder
echo "copy to library path: $origin_path/$library_path"
cp $libraries $origin_path/$library_path
if [ $? -ne 0 ]; then
    echo "cp failed!"
    exit 1
fi
