// Automatically generated by makemoduledefs.py.

#if (MICROPY_PY_ALIYUNIOT)
    extern const struct _mp_obj_module_t mp_module_aliyunIoT;
    #define MODULE_DEF_MP_QSTR_ALIYUNIOT { MP_ROM_QSTR(MP_QSTR_aliyunIoT), MP_ROM_PTR(&mp_module_aliyunIoT) },
#else
    #define MODULE_DEF_MP_QSTR_ALIYUNIOT
#endif

#if (MICROPY_PY_DRIVER)
    extern const struct _mp_obj_module_t driver_module;
    #define MODULE_DEF_MP_QSTR_DRIVER { MP_ROM_QSTR(MP_QSTR_driver), MP_ROM_PTR(&driver_module) },
#else
    #define MODULE_DEF_MP_QSTR_DRIVER
#endif

#if (MICROPY_PY_HTTP)
    extern const struct _mp_obj_module_t mp_module_http;
    #define MODULE_DEF_MP_QSTR_HTTP { MP_ROM_QSTR(MP_QSTR_http), MP_ROM_PTR(&mp_module_http) },
#else
    #define MODULE_DEF_MP_QSTR_HTTP
#endif

#if (MICROPY_PY_KV)
    extern const struct _mp_obj_module_t mp_module_kv;
    #define MODULE_DEF_MP_QSTR_KV { MP_ROM_QSTR(MP_QSTR_kv), MP_ROM_PTR(&mp_module_kv) },
#else
    #define MODULE_DEF_MP_QSTR_KV
#endif

#if (MICROPY_PY_MODBUS)
    extern const struct _mp_obj_module_t mp_module_modbus;
    #define MODULE_DEF_MP_QSTR_MODBUS { MP_ROM_QSTR(MP_QSTR_modbus), MP_ROM_PTR(&mp_module_modbus) },
#else
    #define MODULE_DEF_MP_QSTR_MODBUS
#endif

#if (MICROPY_PY_OTA)
    extern const struct _mp_obj_module_t mp_module_ota;
    #define MODULE_DEF_MP_QSTR_OTA { MP_ROM_QSTR(MP_QSTR_ota), MP_ROM_PTR(&mp_module_ota) },
#else
    #define MODULE_DEF_MP_QSTR_OTA
#endif

#if (MICROPY_PY_SNTP)
    extern const struct _mp_obj_module_t sntp_module;
    #define MODULE_DEF_MP_QSTR_SNTP { MP_ROM_QSTR(MP_QSTR_sntp), MP_ROM_PTR(&sntp_module) },
#else
    #define MODULE_DEF_MP_QSTR_SNTP
#endif

#if (MICROPY_PY_ARRAY)
    extern const struct _mp_obj_module_t mp_module_uarray;
    #define MODULE_DEF_MP_QSTR_UARRAY { MP_ROM_QSTR(MP_QSTR_uarray), MP_ROM_PTR(&mp_module_uarray) },
#else
    #define MODULE_DEF_MP_QSTR_UARRAY
#endif


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_MP_QSTR_ALIYUNIOT \
    MODULE_DEF_MP_QSTR_DRIVER \
    MODULE_DEF_MP_QSTR_HTTP \
    MODULE_DEF_MP_QSTR_KV \
    MODULE_DEF_MP_QSTR_MODBUS \
    MODULE_DEF_MP_QSTR_OTA \
    MODULE_DEF_MP_QSTR_SNTP \
    MODULE_DEF_MP_QSTR_UARRAY \
// MICROPY_REGISTERED_MODULES
