#add include
include_directories(${MICROPYTHONDIR}/extmod)
include_directories(${MICROPYTHONDIR}/extmod/crypto-algorithms)
include_directories(${MICROPYTHONDIR}/extmod/re1.5)
include_directories(${MICROPYTHONDIR}/extmod/uzlib)

#add src
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/crypto-algorithms/sha256.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/machine_i2c.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/machine_mem.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/machine_pinbase.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/machine_pulse.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/machine_signal.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/machine_spi.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modbtree.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modframebuf.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modubinascii.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/moductypes.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/moduhashlib.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/moduheapq.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modujson.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modurandom.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modure.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/moduselect.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modussl_axtls.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modussl_mbedtls.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modutimeq.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/moduzlib.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/modwebrepl.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/moduwebsocket.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/uos_dupterm.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/vfs.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/vfs_fat.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/vfs_fat_diskio.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/vfs_fat_file.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/vfs_reader.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/virtpin.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/re1.5/charclass.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/re1.5/compilecode.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/re1.5/dumpcode.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/re1.5/recursiveloop.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/uzlib/adler32.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/uzlib/crc32.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/uzlib/tinfgzip.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/uzlib/tinflate.c")
# list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/uzlib/tinfzlib.c")
list(APPEND SOURCEFILE "${MICROPYTHONDIR}/extmod/utime_mphal.c")
