freeze(
    "..",
    (
        "driver/__init__.py",
        "driver/adc.py",
        "driver/gpio.py",
        "driver/i2c.py",
        "driver/pwm.py",
        "driver/spi.py",
        "driver/timer.py",
        "driver/uart.py",
        "driver/wdt.py"
    ),
)