/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/


#ifndef _USBC_ASM_H_
#define _USBC_ASM_H_

//THIS FILE HAS BEEN GENERATED WITH COOLWATCHER. PLEASE EDIT WITH CARE !

#ifndef CT_ASM
#error "You are trying to use in a normal C code the assembly H description of 'usbc'."
#endif


#define SPFIFORAM_SIZE                          (264)
#define DIEP_NUM                                (3)
#define DOEP_NUM                                (2)

//==============================================================================
// usbc
//------------------------------------------------------------------------------
///
//==============================================================================
#define REG_USBC_BASE              0x01A80000

#define REG_USBC_BASE_HI           BASE_HI(REG_USBC_BASE)
#define REG_USBC_BASE_LO           BASE_LO(REG_USBC_BASE)

#define REG_USBC_GOTGCTL           REG_USBC_BASE_LO + 0x00000000
#define REG_USBC_GOTGINT           REG_USBC_BASE_LO + 0x00000004
#define REG_USBC_GAHBCFG           REG_USBC_BASE_LO + 0x00000008
#define REG_USBC_GUSBCFG           REG_USBC_BASE_LO + 0x0000000C
#define REG_USBC_GRSTCTL           REG_USBC_BASE_LO + 0x00000010
#define REG_USBC_GINTSTS           REG_USBC_BASE_LO + 0x00000014
#define REG_USBC_GINTMSK           REG_USBC_BASE_LO + 0x00000018
#define REG_USBC_GRXSTSR           REG_USBC_BASE_LO + 0x0000001C
#define REG_USBC_GRXSTSP           REG_USBC_BASE_LO + 0x00000020
#define REG_USBC_GRXFSIZ           REG_USBC_BASE_LO + 0x00000024
#define REG_USBC_GNPTXFSIZ         REG_USBC_BASE_LO + 0x00000028
#define REG_USBC_GNPTXSTS          REG_USBC_BASE_LO + 0x0000002C
#define REG_USBC_GI2CCTL           REG_USBC_BASE_LO + 0x00000030
#define REG_USBC_GPVNDCTL          REG_USBC_BASE_LO + 0x00000034
#define REG_USBC_GGPIO             REG_USBC_BASE_LO + 0x00000038
#define REG_USBC_GUID              REG_USBC_BASE_LO + 0x0000003C
#define REG_USBC_GSNPSID           REG_USBC_BASE_LO + 0x00000040
#define REG_USBC_GHWCFG1           REG_USBC_BASE_LO + 0x00000044
#define REG_USBC_GHWCFG2           REG_USBC_BASE_LO + 0x00000048
#define REG_USBC_GHWCFG3           REG_USBC_BASE_LO + 0x0000004C
#define REG_USBC_GHWCFG4           REG_USBC_BASE_LO + 0x00000050
#define REG_USBC_HPTXFSIZ          REG_USBC_BASE_LO + 0x00000100
#define REG_USBC_DIEPTXF_0_DIENPTXF REG_USBC_BASE_LO + 0x00000104
#define REG_USBC_DIEPTXF_1_DIENPTXF REG_USBC_BASE_LO + 0x00000108
#define REG_USBC_DIEPTXF_2_DIENPTXF REG_USBC_BASE_LO + 0x0000010C
#define REG_USBC_DCFG              REG_USBC_BASE_LO + 0x00000800
#define REG_USBC_DCTL              REG_USBC_BASE_LO + 0x00000804
#define REG_USBC_DSTS              REG_USBC_BASE_LO + 0x00000808
#define REG_USBC_DIEPMSK           REG_USBC_BASE_LO + 0x00000810
#define REG_USBC_DOEPMSK           REG_USBC_BASE_LO + 0x00000814
#define REG_USBC_DAINT             REG_USBC_BASE_LO + 0x00000818
#define REG_USBC_DAINTMSK          REG_USBC_BASE_LO + 0x0000081C
#define REG_USBC_DTKNQR1           REG_USBC_BASE_LO + 0x00000820
#define REG_USBC_DTKNQR2           REG_USBC_BASE_LO + 0x00000824
#define REG_USBC_DVBUSDIS          REG_USBC_BASE_LO + 0x00000828
#define REG_USBC_DVBUSPULSE        REG_USBC_BASE_LO + 0x0000082C
#define REG_USBC_DTHRCTL           REG_USBC_BASE_LO + 0x00000830
#define REG_USBC_DIEPEMPMSK        REG_USBC_BASE_LO + 0x00000834
#define REG_USBC_DIEPCTL0          REG_USBC_BASE_LO + 0x00000900
#define REG_USBC_DIEPINT0          REG_USBC_BASE_LO + 0x00000908
#define REG_USBC_DIEPTSIZ0         REG_USBC_BASE_LO + 0x00000910
#define REG_USBC_DIEPDMA0          REG_USBC_BASE_LO + 0x00000914
#define REG_USBC_DIEPFSTS0         REG_USBC_BASE_LO + 0x00000918
#define REG_USBC_DIEPNCONFIG_0_DIEPCTL REG_USBC_BASE_LO + 0x00000920
#define REG_USBC_DIEPNCONFIG_0_DIEPINT REG_USBC_BASE_LO + 0x00000928
#define REG_USBC_DIEPNCONFIG_0_DIEPTSIZ REG_USBC_BASE_LO + 0x00000930
#define REG_USBC_DIEPNCONFIG_0_DIEPDMA REG_USBC_BASE_LO + 0x00000934
#define REG_USBC_DIEPNCONFIG_0_DIEPFSTS REG_USBC_BASE_LO + 0x00000938
#define REG_USBC_DIEPNCONFIG_1_DIEPCTL REG_USBC_BASE_LO + 0x00000940
#define REG_USBC_DIEPNCONFIG_1_DIEPINT REG_USBC_BASE_LO + 0x00000948
#define REG_USBC_DIEPNCONFIG_1_DIEPTSIZ REG_USBC_BASE_LO + 0x00000950
#define REG_USBC_DIEPNCONFIG_1_DIEPDMA REG_USBC_BASE_LO + 0x00000954
#define REG_USBC_DIEPNCONFIG_1_DIEPFSTS REG_USBC_BASE_LO + 0x00000958
#define REG_USBC_DIEPNCONFIG_2_DIEPCTL REG_USBC_BASE_LO + 0x00000960
#define REG_USBC_DIEPNCONFIG_2_DIEPINT REG_USBC_BASE_LO + 0x00000968
#define REG_USBC_DIEPNCONFIG_2_DIEPTSIZ REG_USBC_BASE_LO + 0x00000970
#define REG_USBC_DIEPNCONFIG_2_DIEPDMA REG_USBC_BASE_LO + 0x00000974
#define REG_USBC_DIEPNCONFIG_2_DIEPFSTS REG_USBC_BASE_LO + 0x00000978
#define REG_USBC_DOEPCTL0          REG_USBC_BASE_LO + 0x00000B00
#define REG_USBC_DOEPINT0          REG_USBC_BASE_LO + 0x00000B08
#define REG_USBC_DOEPTSIZ0         REG_USBC_BASE_LO + 0x00000B10
#define REG_USBC_DOEPDMA0          REG_USBC_BASE_LO + 0x00000B14
#define REG_USBC_DOEPNCONFIG_0_DOEPCTL REG_USBC_BASE_LO + 0x00000B20
#define REG_USBC_DOEPNCONFIG_0_DOEPINT REG_USBC_BASE_LO + 0x00000B28
#define REG_USBC_DOEPNCONFIG_0_DOEPTSIZ REG_USBC_BASE_LO + 0x00000B30
#define REG_USBC_DOEPNCONFIG_0_DOEPDMA REG_USBC_BASE_LO + 0x00000B34
#define REG_USBC_DOEPNCONFIG_1_DOEPCTL REG_USBC_BASE_LO + 0x00000B40
#define REG_USBC_DOEPNCONFIG_1_DOEPINT REG_USBC_BASE_LO + 0x00000B48
#define REG_USBC_DOEPNCONFIG_1_DOEPTSIZ REG_USBC_BASE_LO + 0x00000B50
#define REG_USBC_DOEPNCONFIG_1_DOEPDMA REG_USBC_BASE_LO + 0x00000B54
#define REG_USBC_PCGCCTL           REG_USBC_BASE_LO + 0x00000E00
#define REG_USBC_EPNFIFO_0_TXRXDATA REG_USBC_BASE_LO + 0x00001000
#define REG_USBC_EPNFIFO_1_TXRXDATA REG_USBC_BASE_LO + 0x00002000
#define REG_USBC_EPNFIFO_2_TXRXDATA REG_USBC_BASE_LO + 0x00003000
#define REG_USBC_EPNFIFO_3_TXRXDATA REG_USBC_BASE_LO + 0x00004000
#define REG_USBC_SPFIFORAM_0_RAMDATA REG_USBC_BASE_LO + 0x00020000
#define REG_USBC_SPFIFORAM_1_RAMDATA REG_USBC_BASE_LO + 0x00020004
#define REG_USBC_SPFIFORAM_2_RAMDATA REG_USBC_BASE_LO + 0x00020008
#define REG_USBC_SPFIFORAM_3_RAMDATA REG_USBC_BASE_LO + 0x0002000C
#define REG_USBC_SPFIFORAM_4_RAMDATA REG_USBC_BASE_LO + 0x00020010
#define REG_USBC_SPFIFORAM_5_RAMDATA REG_USBC_BASE_LO + 0x00020014
#define REG_USBC_SPFIFORAM_6_RAMDATA REG_USBC_BASE_LO + 0x00020018
#define REG_USBC_SPFIFORAM_7_RAMDATA REG_USBC_BASE_LO + 0x0002001C
#define REG_USBC_SPFIFORAM_8_RAMDATA REG_USBC_BASE_LO + 0x00020020
#define REG_USBC_SPFIFORAM_9_RAMDATA REG_USBC_BASE_LO + 0x00020024
#define REG_USBC_SPFIFORAM_10_RAMDATA REG_USBC_BASE_LO + 0x00020028
#define REG_USBC_SPFIFORAM_11_RAMDATA REG_USBC_BASE_LO + 0x0002002C
#define REG_USBC_SPFIFORAM_12_RAMDATA REG_USBC_BASE_LO + 0x00020030
#define REG_USBC_SPFIFORAM_13_RAMDATA REG_USBC_BASE_LO + 0x00020034
#define REG_USBC_SPFIFORAM_14_RAMDATA REG_USBC_BASE_LO + 0x00020038
#define REG_USBC_SPFIFORAM_15_RAMDATA REG_USBC_BASE_LO + 0x0002003C
#define REG_USBC_SPFIFORAM_16_RAMDATA REG_USBC_BASE_LO + 0x00020040
#define REG_USBC_SPFIFORAM_17_RAMDATA REG_USBC_BASE_LO + 0x00020044
#define REG_USBC_SPFIFORAM_18_RAMDATA REG_USBC_BASE_LO + 0x00020048
#define REG_USBC_SPFIFORAM_19_RAMDATA REG_USBC_BASE_LO + 0x0002004C
#define REG_USBC_SPFIFORAM_20_RAMDATA REG_USBC_BASE_LO + 0x00020050
#define REG_USBC_SPFIFORAM_21_RAMDATA REG_USBC_BASE_LO + 0x00020054
#define REG_USBC_SPFIFORAM_22_RAMDATA REG_USBC_BASE_LO + 0x00020058
#define REG_USBC_SPFIFORAM_23_RAMDATA REG_USBC_BASE_LO + 0x0002005C
#define REG_USBC_SPFIFORAM_24_RAMDATA REG_USBC_BASE_LO + 0x00020060
#define REG_USBC_SPFIFORAM_25_RAMDATA REG_USBC_BASE_LO + 0x00020064
#define REG_USBC_SPFIFORAM_26_RAMDATA REG_USBC_BASE_LO + 0x00020068
#define REG_USBC_SPFIFORAM_27_RAMDATA REG_USBC_BASE_LO + 0x0002006C
#define REG_USBC_SPFIFORAM_28_RAMDATA REG_USBC_BASE_LO + 0x00020070
#define REG_USBC_SPFIFORAM_29_RAMDATA REG_USBC_BASE_LO + 0x00020074
#define REG_USBC_SPFIFORAM_30_RAMDATA REG_USBC_BASE_LO + 0x00020078
#define REG_USBC_SPFIFORAM_31_RAMDATA REG_USBC_BASE_LO + 0x0002007C
#define REG_USBC_SPFIFORAM_32_RAMDATA REG_USBC_BASE_LO + 0x00020080
#define REG_USBC_SPFIFORAM_33_RAMDATA REG_USBC_BASE_LO + 0x00020084
#define REG_USBC_SPFIFORAM_34_RAMDATA REG_USBC_BASE_LO + 0x00020088
#define REG_USBC_SPFIFORAM_35_RAMDATA REG_USBC_BASE_LO + 0x0002008C
#define REG_USBC_SPFIFORAM_36_RAMDATA REG_USBC_BASE_LO + 0x00020090
#define REG_USBC_SPFIFORAM_37_RAMDATA REG_USBC_BASE_LO + 0x00020094
#define REG_USBC_SPFIFORAM_38_RAMDATA REG_USBC_BASE_LO + 0x00020098
#define REG_USBC_SPFIFORAM_39_RAMDATA REG_USBC_BASE_LO + 0x0002009C
#define REG_USBC_SPFIFORAM_40_RAMDATA REG_USBC_BASE_LO + 0x000200A0
#define REG_USBC_SPFIFORAM_41_RAMDATA REG_USBC_BASE_LO + 0x000200A4
#define REG_USBC_SPFIFORAM_42_RAMDATA REG_USBC_BASE_LO + 0x000200A8
#define REG_USBC_SPFIFORAM_43_RAMDATA REG_USBC_BASE_LO + 0x000200AC
#define REG_USBC_SPFIFORAM_44_RAMDATA REG_USBC_BASE_LO + 0x000200B0
#define REG_USBC_SPFIFORAM_45_RAMDATA REG_USBC_BASE_LO + 0x000200B4
#define REG_USBC_SPFIFORAM_46_RAMDATA REG_USBC_BASE_LO + 0x000200B8
#define REG_USBC_SPFIFORAM_47_RAMDATA REG_USBC_BASE_LO + 0x000200BC
#define REG_USBC_SPFIFORAM_48_RAMDATA REG_USBC_BASE_LO + 0x000200C0
#define REG_USBC_SPFIFORAM_49_RAMDATA REG_USBC_BASE_LO + 0x000200C4
#define REG_USBC_SPFIFORAM_50_RAMDATA REG_USBC_BASE_LO + 0x000200C8
#define REG_USBC_SPFIFORAM_51_RAMDATA REG_USBC_BASE_LO + 0x000200CC
#define REG_USBC_SPFIFORAM_52_RAMDATA REG_USBC_BASE_LO + 0x000200D0
#define REG_USBC_SPFIFORAM_53_RAMDATA REG_USBC_BASE_LO + 0x000200D4
#define REG_USBC_SPFIFORAM_54_RAMDATA REG_USBC_BASE_LO + 0x000200D8
#define REG_USBC_SPFIFORAM_55_RAMDATA REG_USBC_BASE_LO + 0x000200DC
#define REG_USBC_SPFIFORAM_56_RAMDATA REG_USBC_BASE_LO + 0x000200E0
#define REG_USBC_SPFIFORAM_57_RAMDATA REG_USBC_BASE_LO + 0x000200E4
#define REG_USBC_SPFIFORAM_58_RAMDATA REG_USBC_BASE_LO + 0x000200E8
#define REG_USBC_SPFIFORAM_59_RAMDATA REG_USBC_BASE_LO + 0x000200EC
#define REG_USBC_SPFIFORAM_60_RAMDATA REG_USBC_BASE_LO + 0x000200F0
#define REG_USBC_SPFIFORAM_61_RAMDATA REG_USBC_BASE_LO + 0x000200F4
#define REG_USBC_SPFIFORAM_62_RAMDATA REG_USBC_BASE_LO + 0x000200F8
#define REG_USBC_SPFIFORAM_63_RAMDATA REG_USBC_BASE_LO + 0x000200FC
#define REG_USBC_SPFIFORAM_64_RAMDATA REG_USBC_BASE_LO + 0x00020100
#define REG_USBC_SPFIFORAM_65_RAMDATA REG_USBC_BASE_LO + 0x00020104
#define REG_USBC_SPFIFORAM_66_RAMDATA REG_USBC_BASE_LO + 0x00020108
#define REG_USBC_SPFIFORAM_67_RAMDATA REG_USBC_BASE_LO + 0x0002010C
#define REG_USBC_SPFIFORAM_68_RAMDATA REG_USBC_BASE_LO + 0x00020110
#define REG_USBC_SPFIFORAM_69_RAMDATA REG_USBC_BASE_LO + 0x00020114
#define REG_USBC_SPFIFORAM_70_RAMDATA REG_USBC_BASE_LO + 0x00020118
#define REG_USBC_SPFIFORAM_71_RAMDATA REG_USBC_BASE_LO + 0x0002011C
#define REG_USBC_SPFIFORAM_72_RAMDATA REG_USBC_BASE_LO + 0x00020120
#define REG_USBC_SPFIFORAM_73_RAMDATA REG_USBC_BASE_LO + 0x00020124
#define REG_USBC_SPFIFORAM_74_RAMDATA REG_USBC_BASE_LO + 0x00020128
#define REG_USBC_SPFIFORAM_75_RAMDATA REG_USBC_BASE_LO + 0x0002012C
#define REG_USBC_SPFIFORAM_76_RAMDATA REG_USBC_BASE_LO + 0x00020130
#define REG_USBC_SPFIFORAM_77_RAMDATA REG_USBC_BASE_LO + 0x00020134
#define REG_USBC_SPFIFORAM_78_RAMDATA REG_USBC_BASE_LO + 0x00020138
#define REG_USBC_SPFIFORAM_79_RAMDATA REG_USBC_BASE_LO + 0x0002013C
#define REG_USBC_SPFIFORAM_80_RAMDATA REG_USBC_BASE_LO + 0x00020140
#define REG_USBC_SPFIFORAM_81_RAMDATA REG_USBC_BASE_LO + 0x00020144
#define REG_USBC_SPFIFORAM_82_RAMDATA REG_USBC_BASE_LO + 0x00020148
#define REG_USBC_SPFIFORAM_83_RAMDATA REG_USBC_BASE_LO + 0x0002014C
#define REG_USBC_SPFIFORAM_84_RAMDATA REG_USBC_BASE_LO + 0x00020150
#define REG_USBC_SPFIFORAM_85_RAMDATA REG_USBC_BASE_LO + 0x00020154
#define REG_USBC_SPFIFORAM_86_RAMDATA REG_USBC_BASE_LO + 0x00020158
#define REG_USBC_SPFIFORAM_87_RAMDATA REG_USBC_BASE_LO + 0x0002015C
#define REG_USBC_SPFIFORAM_88_RAMDATA REG_USBC_BASE_LO + 0x00020160
#define REG_USBC_SPFIFORAM_89_RAMDATA REG_USBC_BASE_LO + 0x00020164
#define REG_USBC_SPFIFORAM_90_RAMDATA REG_USBC_BASE_LO + 0x00020168
#define REG_USBC_SPFIFORAM_91_RAMDATA REG_USBC_BASE_LO + 0x0002016C
#define REG_USBC_SPFIFORAM_92_RAMDATA REG_USBC_BASE_LO + 0x00020170
#define REG_USBC_SPFIFORAM_93_RAMDATA REG_USBC_BASE_LO + 0x00020174
#define REG_USBC_SPFIFORAM_94_RAMDATA REG_USBC_BASE_LO + 0x00020178
#define REG_USBC_SPFIFORAM_95_RAMDATA REG_USBC_BASE_LO + 0x0002017C
#define REG_USBC_SPFIFORAM_96_RAMDATA REG_USBC_BASE_LO + 0x00020180
#define REG_USBC_SPFIFORAM_97_RAMDATA REG_USBC_BASE_LO + 0x00020184
#define REG_USBC_SPFIFORAM_98_RAMDATA REG_USBC_BASE_LO + 0x00020188
#define REG_USBC_SPFIFORAM_99_RAMDATA REG_USBC_BASE_LO + 0x0002018C
#define REG_USBC_SPFIFORAM_100_RAMDATA REG_USBC_BASE_LO + 0x00020190
#define REG_USBC_SPFIFORAM_101_RAMDATA REG_USBC_BASE_LO + 0x00020194
#define REG_USBC_SPFIFORAM_102_RAMDATA REG_USBC_BASE_LO + 0x00020198
#define REG_USBC_SPFIFORAM_103_RAMDATA REG_USBC_BASE_LO + 0x0002019C
#define REG_USBC_SPFIFORAM_104_RAMDATA REG_USBC_BASE_LO + 0x000201A0
#define REG_USBC_SPFIFORAM_105_RAMDATA REG_USBC_BASE_LO + 0x000201A4
#define REG_USBC_SPFIFORAM_106_RAMDATA REG_USBC_BASE_LO + 0x000201A8
#define REG_USBC_SPFIFORAM_107_RAMDATA REG_USBC_BASE_LO + 0x000201AC
#define REG_USBC_SPFIFORAM_108_RAMDATA REG_USBC_BASE_LO + 0x000201B0
#define REG_USBC_SPFIFORAM_109_RAMDATA REG_USBC_BASE_LO + 0x000201B4
#define REG_USBC_SPFIFORAM_110_RAMDATA REG_USBC_BASE_LO + 0x000201B8
#define REG_USBC_SPFIFORAM_111_RAMDATA REG_USBC_BASE_LO + 0x000201BC
#define REG_USBC_SPFIFORAM_112_RAMDATA REG_USBC_BASE_LO + 0x000201C0
#define REG_USBC_SPFIFORAM_113_RAMDATA REG_USBC_BASE_LO + 0x000201C4
#define REG_USBC_SPFIFORAM_114_RAMDATA REG_USBC_BASE_LO + 0x000201C8
#define REG_USBC_SPFIFORAM_115_RAMDATA REG_USBC_BASE_LO + 0x000201CC
#define REG_USBC_SPFIFORAM_116_RAMDATA REG_USBC_BASE_LO + 0x000201D0
#define REG_USBC_SPFIFORAM_117_RAMDATA REG_USBC_BASE_LO + 0x000201D4
#define REG_USBC_SPFIFORAM_118_RAMDATA REG_USBC_BASE_LO + 0x000201D8
#define REG_USBC_SPFIFORAM_119_RAMDATA REG_USBC_BASE_LO + 0x000201DC
#define REG_USBC_SPFIFORAM_120_RAMDATA REG_USBC_BASE_LO + 0x000201E0
#define REG_USBC_SPFIFORAM_121_RAMDATA REG_USBC_BASE_LO + 0x000201E4
#define REG_USBC_SPFIFORAM_122_RAMDATA REG_USBC_BASE_LO + 0x000201E8
#define REG_USBC_SPFIFORAM_123_RAMDATA REG_USBC_BASE_LO + 0x000201EC
#define REG_USBC_SPFIFORAM_124_RAMDATA REG_USBC_BASE_LO + 0x000201F0
#define REG_USBC_SPFIFORAM_125_RAMDATA REG_USBC_BASE_LO + 0x000201F4
#define REG_USBC_SPFIFORAM_126_RAMDATA REG_USBC_BASE_LO + 0x000201F8
#define REG_USBC_SPFIFORAM_127_RAMDATA REG_USBC_BASE_LO + 0x000201FC
#define REG_USBC_SPFIFORAM_128_RAMDATA REG_USBC_BASE_LO + 0x00020200
#define REG_USBC_SPFIFORAM_129_RAMDATA REG_USBC_BASE_LO + 0x00020204
#define REG_USBC_SPFIFORAM_130_RAMDATA REG_USBC_BASE_LO + 0x00020208
#define REG_USBC_SPFIFORAM_131_RAMDATA REG_USBC_BASE_LO + 0x0002020C
#define REG_USBC_SPFIFORAM_132_RAMDATA REG_USBC_BASE_LO + 0x00020210
#define REG_USBC_SPFIFORAM_133_RAMDATA REG_USBC_BASE_LO + 0x00020214
#define REG_USBC_SPFIFORAM_134_RAMDATA REG_USBC_BASE_LO + 0x00020218
#define REG_USBC_SPFIFORAM_135_RAMDATA REG_USBC_BASE_LO + 0x0002021C
#define REG_USBC_SPFIFORAM_136_RAMDATA REG_USBC_BASE_LO + 0x00020220
#define REG_USBC_SPFIFORAM_137_RAMDATA REG_USBC_BASE_LO + 0x00020224
#define REG_USBC_SPFIFORAM_138_RAMDATA REG_USBC_BASE_LO + 0x00020228
#define REG_USBC_SPFIFORAM_139_RAMDATA REG_USBC_BASE_LO + 0x0002022C
#define REG_USBC_SPFIFORAM_140_RAMDATA REG_USBC_BASE_LO + 0x00020230
#define REG_USBC_SPFIFORAM_141_RAMDATA REG_USBC_BASE_LO + 0x00020234
#define REG_USBC_SPFIFORAM_142_RAMDATA REG_USBC_BASE_LO + 0x00020238
#define REG_USBC_SPFIFORAM_143_RAMDATA REG_USBC_BASE_LO + 0x0002023C
#define REG_USBC_SPFIFORAM_144_RAMDATA REG_USBC_BASE_LO + 0x00020240
#define REG_USBC_SPFIFORAM_145_RAMDATA REG_USBC_BASE_LO + 0x00020244
#define REG_USBC_SPFIFORAM_146_RAMDATA REG_USBC_BASE_LO + 0x00020248
#define REG_USBC_SPFIFORAM_147_RAMDATA REG_USBC_BASE_LO + 0x0002024C
#define REG_USBC_SPFIFORAM_148_RAMDATA REG_USBC_BASE_LO + 0x00020250
#define REG_USBC_SPFIFORAM_149_RAMDATA REG_USBC_BASE_LO + 0x00020254
#define REG_USBC_SPFIFORAM_150_RAMDATA REG_USBC_BASE_LO + 0x00020258
#define REG_USBC_SPFIFORAM_151_RAMDATA REG_USBC_BASE_LO + 0x0002025C
#define REG_USBC_SPFIFORAM_152_RAMDATA REG_USBC_BASE_LO + 0x00020260
#define REG_USBC_SPFIFORAM_153_RAMDATA REG_USBC_BASE_LO + 0x00020264
#define REG_USBC_SPFIFORAM_154_RAMDATA REG_USBC_BASE_LO + 0x00020268
#define REG_USBC_SPFIFORAM_155_RAMDATA REG_USBC_BASE_LO + 0x0002026C
#define REG_USBC_SPFIFORAM_156_RAMDATA REG_USBC_BASE_LO + 0x00020270
#define REG_USBC_SPFIFORAM_157_RAMDATA REG_USBC_BASE_LO + 0x00020274
#define REG_USBC_SPFIFORAM_158_RAMDATA REG_USBC_BASE_LO + 0x00020278
#define REG_USBC_SPFIFORAM_159_RAMDATA REG_USBC_BASE_LO + 0x0002027C
#define REG_USBC_SPFIFORAM_160_RAMDATA REG_USBC_BASE_LO + 0x00020280
#define REG_USBC_SPFIFORAM_161_RAMDATA REG_USBC_BASE_LO + 0x00020284
#define REG_USBC_SPFIFORAM_162_RAMDATA REG_USBC_BASE_LO + 0x00020288
#define REG_USBC_SPFIFORAM_163_RAMDATA REG_USBC_BASE_LO + 0x0002028C
#define REG_USBC_SPFIFORAM_164_RAMDATA REG_USBC_BASE_LO + 0x00020290
#define REG_USBC_SPFIFORAM_165_RAMDATA REG_USBC_BASE_LO + 0x00020294
#define REG_USBC_SPFIFORAM_166_RAMDATA REG_USBC_BASE_LO + 0x00020298
#define REG_USBC_SPFIFORAM_167_RAMDATA REG_USBC_BASE_LO + 0x0002029C
#define REG_USBC_SPFIFORAM_168_RAMDATA REG_USBC_BASE_LO + 0x000202A0
#define REG_USBC_SPFIFORAM_169_RAMDATA REG_USBC_BASE_LO + 0x000202A4
#define REG_USBC_SPFIFORAM_170_RAMDATA REG_USBC_BASE_LO + 0x000202A8
#define REG_USBC_SPFIFORAM_171_RAMDATA REG_USBC_BASE_LO + 0x000202AC
#define REG_USBC_SPFIFORAM_172_RAMDATA REG_USBC_BASE_LO + 0x000202B0
#define REG_USBC_SPFIFORAM_173_RAMDATA REG_USBC_BASE_LO + 0x000202B4
#define REG_USBC_SPFIFORAM_174_RAMDATA REG_USBC_BASE_LO + 0x000202B8
#define REG_USBC_SPFIFORAM_175_RAMDATA REG_USBC_BASE_LO + 0x000202BC
#define REG_USBC_SPFIFORAM_176_RAMDATA REG_USBC_BASE_LO + 0x000202C0
#define REG_USBC_SPFIFORAM_177_RAMDATA REG_USBC_BASE_LO + 0x000202C4
#define REG_USBC_SPFIFORAM_178_RAMDATA REG_USBC_BASE_LO + 0x000202C8
#define REG_USBC_SPFIFORAM_179_RAMDATA REG_USBC_BASE_LO + 0x000202CC
#define REG_USBC_SPFIFORAM_180_RAMDATA REG_USBC_BASE_LO + 0x000202D0
#define REG_USBC_SPFIFORAM_181_RAMDATA REG_USBC_BASE_LO + 0x000202D4
#define REG_USBC_SPFIFORAM_182_RAMDATA REG_USBC_BASE_LO + 0x000202D8
#define REG_USBC_SPFIFORAM_183_RAMDATA REG_USBC_BASE_LO + 0x000202DC
#define REG_USBC_SPFIFORAM_184_RAMDATA REG_USBC_BASE_LO + 0x000202E0
#define REG_USBC_SPFIFORAM_185_RAMDATA REG_USBC_BASE_LO + 0x000202E4
#define REG_USBC_SPFIFORAM_186_RAMDATA REG_USBC_BASE_LO + 0x000202E8
#define REG_USBC_SPFIFORAM_187_RAMDATA REG_USBC_BASE_LO + 0x000202EC
#define REG_USBC_SPFIFORAM_188_RAMDATA REG_USBC_BASE_LO + 0x000202F0
#define REG_USBC_SPFIFORAM_189_RAMDATA REG_USBC_BASE_LO + 0x000202F4
#define REG_USBC_SPFIFORAM_190_RAMDATA REG_USBC_BASE_LO + 0x000202F8
#define REG_USBC_SPFIFORAM_191_RAMDATA REG_USBC_BASE_LO + 0x000202FC
#define REG_USBC_SPFIFORAM_192_RAMDATA REG_USBC_BASE_LO + 0x00020300
#define REG_USBC_SPFIFORAM_193_RAMDATA REG_USBC_BASE_LO + 0x00020304
#define REG_USBC_SPFIFORAM_194_RAMDATA REG_USBC_BASE_LO + 0x00020308
#define REG_USBC_SPFIFORAM_195_RAMDATA REG_USBC_BASE_LO + 0x0002030C
#define REG_USBC_SPFIFORAM_196_RAMDATA REG_USBC_BASE_LO + 0x00020310
#define REG_USBC_SPFIFORAM_197_RAMDATA REG_USBC_BASE_LO + 0x00020314
#define REG_USBC_SPFIFORAM_198_RAMDATA REG_USBC_BASE_LO + 0x00020318
#define REG_USBC_SPFIFORAM_199_RAMDATA REG_USBC_BASE_LO + 0x0002031C
#define REG_USBC_SPFIFORAM_200_RAMDATA REG_USBC_BASE_LO + 0x00020320
#define REG_USBC_SPFIFORAM_201_RAMDATA REG_USBC_BASE_LO + 0x00020324
#define REG_USBC_SPFIFORAM_202_RAMDATA REG_USBC_BASE_LO + 0x00020328
#define REG_USBC_SPFIFORAM_203_RAMDATA REG_USBC_BASE_LO + 0x0002032C
#define REG_USBC_SPFIFORAM_204_RAMDATA REG_USBC_BASE_LO + 0x00020330
#define REG_USBC_SPFIFORAM_205_RAMDATA REG_USBC_BASE_LO + 0x00020334
#define REG_USBC_SPFIFORAM_206_RAMDATA REG_USBC_BASE_LO + 0x00020338
#define REG_USBC_SPFIFORAM_207_RAMDATA REG_USBC_BASE_LO + 0x0002033C
#define REG_USBC_SPFIFORAM_208_RAMDATA REG_USBC_BASE_LO + 0x00020340
#define REG_USBC_SPFIFORAM_209_RAMDATA REG_USBC_BASE_LO + 0x00020344
#define REG_USBC_SPFIFORAM_210_RAMDATA REG_USBC_BASE_LO + 0x00020348
#define REG_USBC_SPFIFORAM_211_RAMDATA REG_USBC_BASE_LO + 0x0002034C
#define REG_USBC_SPFIFORAM_212_RAMDATA REG_USBC_BASE_LO + 0x00020350
#define REG_USBC_SPFIFORAM_213_RAMDATA REG_USBC_BASE_LO + 0x00020354
#define REG_USBC_SPFIFORAM_214_RAMDATA REG_USBC_BASE_LO + 0x00020358
#define REG_USBC_SPFIFORAM_215_RAMDATA REG_USBC_BASE_LO + 0x0002035C
#define REG_USBC_SPFIFORAM_216_RAMDATA REG_USBC_BASE_LO + 0x00020360
#define REG_USBC_SPFIFORAM_217_RAMDATA REG_USBC_BASE_LO + 0x00020364
#define REG_USBC_SPFIFORAM_218_RAMDATA REG_USBC_BASE_LO + 0x00020368
#define REG_USBC_SPFIFORAM_219_RAMDATA REG_USBC_BASE_LO + 0x0002036C
#define REG_USBC_SPFIFORAM_220_RAMDATA REG_USBC_BASE_LO + 0x00020370
#define REG_USBC_SPFIFORAM_221_RAMDATA REG_USBC_BASE_LO + 0x00020374
#define REG_USBC_SPFIFORAM_222_RAMDATA REG_USBC_BASE_LO + 0x00020378
#define REG_USBC_SPFIFORAM_223_RAMDATA REG_USBC_BASE_LO + 0x0002037C
#define REG_USBC_SPFIFORAM_224_RAMDATA REG_USBC_BASE_LO + 0x00020380
#define REG_USBC_SPFIFORAM_225_RAMDATA REG_USBC_BASE_LO + 0x00020384
#define REG_USBC_SPFIFORAM_226_RAMDATA REG_USBC_BASE_LO + 0x00020388
#define REG_USBC_SPFIFORAM_227_RAMDATA REG_USBC_BASE_LO + 0x0002038C
#define REG_USBC_SPFIFORAM_228_RAMDATA REG_USBC_BASE_LO + 0x00020390
#define REG_USBC_SPFIFORAM_229_RAMDATA REG_USBC_BASE_LO + 0x00020394
#define REG_USBC_SPFIFORAM_230_RAMDATA REG_USBC_BASE_LO + 0x00020398
#define REG_USBC_SPFIFORAM_231_RAMDATA REG_USBC_BASE_LO + 0x0002039C
#define REG_USBC_SPFIFORAM_232_RAMDATA REG_USBC_BASE_LO + 0x000203A0
#define REG_USBC_SPFIFORAM_233_RAMDATA REG_USBC_BASE_LO + 0x000203A4
#define REG_USBC_SPFIFORAM_234_RAMDATA REG_USBC_BASE_LO + 0x000203A8
#define REG_USBC_SPFIFORAM_235_RAMDATA REG_USBC_BASE_LO + 0x000203AC
#define REG_USBC_SPFIFORAM_236_RAMDATA REG_USBC_BASE_LO + 0x000203B0
#define REG_USBC_SPFIFORAM_237_RAMDATA REG_USBC_BASE_LO + 0x000203B4
#define REG_USBC_SPFIFORAM_238_RAMDATA REG_USBC_BASE_LO + 0x000203B8
#define REG_USBC_SPFIFORAM_239_RAMDATA REG_USBC_BASE_LO + 0x000203BC
#define REG_USBC_SPFIFORAM_240_RAMDATA REG_USBC_BASE_LO + 0x000203C0
#define REG_USBC_SPFIFORAM_241_RAMDATA REG_USBC_BASE_LO + 0x000203C4
#define REG_USBC_SPFIFORAM_242_RAMDATA REG_USBC_BASE_LO + 0x000203C8
#define REG_USBC_SPFIFORAM_243_RAMDATA REG_USBC_BASE_LO + 0x000203CC
#define REG_USBC_SPFIFORAM_244_RAMDATA REG_USBC_BASE_LO + 0x000203D0
#define REG_USBC_SPFIFORAM_245_RAMDATA REG_USBC_BASE_LO + 0x000203D4
#define REG_USBC_SPFIFORAM_246_RAMDATA REG_USBC_BASE_LO + 0x000203D8
#define REG_USBC_SPFIFORAM_247_RAMDATA REG_USBC_BASE_LO + 0x000203DC
#define REG_USBC_SPFIFORAM_248_RAMDATA REG_USBC_BASE_LO + 0x000203E0
#define REG_USBC_SPFIFORAM_249_RAMDATA REG_USBC_BASE_LO + 0x000203E4
#define REG_USBC_SPFIFORAM_250_RAMDATA REG_USBC_BASE_LO + 0x000203E8
#define REG_USBC_SPFIFORAM_251_RAMDATA REG_USBC_BASE_LO + 0x000203EC
#define REG_USBC_SPFIFORAM_252_RAMDATA REG_USBC_BASE_LO + 0x000203F0
#define REG_USBC_SPFIFORAM_253_RAMDATA REG_USBC_BASE_LO + 0x000203F4
#define REG_USBC_SPFIFORAM_254_RAMDATA REG_USBC_BASE_LO + 0x000203F8
#define REG_USBC_SPFIFORAM_255_RAMDATA REG_USBC_BASE_LO + 0x000203FC
#define REG_USBC_SPFIFORAM_256_RAMDATA REG_USBC_BASE_LO + 0x00020400
#define REG_USBC_SPFIFORAM_257_RAMDATA REG_USBC_BASE_LO + 0x00020404
#define REG_USBC_SPFIFORAM_258_RAMDATA REG_USBC_BASE_LO + 0x00020408
#define REG_USBC_SPFIFORAM_259_RAMDATA REG_USBC_BASE_LO + 0x0002040C
#define REG_USBC_SPFIFORAM_260_RAMDATA REG_USBC_BASE_LO + 0x00020410
#define REG_USBC_SPFIFORAM_261_RAMDATA REG_USBC_BASE_LO + 0x00020414
#define REG_USBC_SPFIFORAM_262_RAMDATA REG_USBC_BASE_LO + 0x00020418
#define REG_USBC_SPFIFORAM_263_RAMDATA REG_USBC_BASE_LO + 0x0002041C

//GOTGCTL
#define USBC_SESREQSCS             (1<<0)
#define USBC_SESREQSCS_MASK        (1<<0)
#define USBC_SESREQSCS_SHIFT       (0)
#define USBC_SESREQ                (1<<1)
#define USBC_SESREQ_MASK           (1<<1)
#define USBC_SESREQ_SHIFT          (1)
#define USBC_HSTNEGSCS             (1<<8)
#define USBC_HSTNEGSCS_MASK        (1<<8)
#define USBC_HSTNEGSCS_SHIFT       (8)
#define USBC_HNPREQ                (1<<9)
#define USBC_HNPREQ_MASK           (1<<9)
#define USBC_HNPREQ_SHIFT          (9)
#define USBC_HSTSETHNPEN           (1<<10)
#define USBC_HSTSETHNPEN_MASK      (1<<10)
#define USBC_HSTSETHNPEN_SHIFT     (10)
#define USBC_DEVHNPEN              (1<<11)
#define USBC_DEVHNPEN_MASK         (1<<11)
#define USBC_DEVHNPEN_SHIFT        (11)
#define USBC_CONLDSTS              (1<<16)
#define USBC_CONLDSTS_MASK         (1<<16)
#define USBC_CONLDSTS_SHIFT        (16)
#define USBC_DBNCTIME              (1<<17)
#define USBC_DBNCTIME_MASK         (1<<17)
#define USBC_DBNCTIME_SHIFT        (17)
#define USBC_ASESVLD               (1<<18)
#define USBC_ASESVLD_MASK          (1<<18)
#define USBC_ASESVLD_SHIFT         (18)
#define USBC_BSESVLD               (1<<19)
#define USBC_BSESVLD_MASK          (1<<19)
#define USBC_BSESVLD_SHIFT         (19)

//GOTGINT
#define USBC_SESENDDET             (1<<2)
#define USBC_SESENDDET_MASK        (1<<2)
#define USBC_SESENDDET_SHIFT       (2)
#define USBC_SESREQSUCSTSCHNG      (1<<8)
#define USBC_SESREQSUCSTSCHNG_MASK (1<<8)
#define USBC_SESREQSUCSTSCHNG_SHIFT (8)
#define USBC_HSTNEGSUCSTSCHNG      (1<<9)
#define USBC_HSTNEGSUCSTSCHNG_MASK (1<<9)
#define USBC_HSTNEGSUCSTSCHNG_SHIFT (9)
#define USBC_HSTNEGDET             (1<<17)
#define USBC_HSTNEGDET_MASK        (1<<17)
#define USBC_HSTNEGDET_SHIFT       (17)
#define USBC_ADEVTOUTCHG           (1<<18)
#define USBC_ADEVTOUTCHG_MASK      (1<<18)
#define USBC_ADEVTOUTCHG_SHIFT     (18)
#define USBC_DBNCEDONE             (1<<19)
#define USBC_DBNCEDONE_MASK        (1<<19)
#define USBC_DBNCEDONE_SHIFT       (19)

//GAHBCFG
#define USBC_GLBLINTRMSK           (1<<0)
#define USBC_GLBLINTRMSK_MASK      (1<<0)
#define USBC_GLBLINTRMSK_SHIFT     (0)
#define USBC_HBSTLEN(n)            (((n)&15)<<1)
#define USBC_HBSTLEN_MASK          (15<<1)
#define USBC_HBSTLEN_SHIFT         (1)
#define USBC_DMAEN                 (1<<5)
#define USBC_DMAEN_MASK            (1<<5)
#define USBC_DMAEN_SHIFT           (5)
#define USBC_NPTXFEMPLVL           (1<<7)
#define USBC_NPTXFEMPLVL_MASK      (1<<7)
#define USBC_NPTXFEMPLVL_SHIFT     (7)
#define USBC_PTXFEMPLVL            (1<<8)
#define USBC_PTXFEMPLVL_MASK       (1<<8)
#define USBC_PTXFEMPLVL_SHIFT      (8)

//GUSBCFG
#define USBC_TOUTCAL(n)            (((n)&7)<<0)
#define USBC_TOUTCAL_MASK          (7<<0)
#define USBC_TOUTCAL_SHIFT         (0)
#define USBC_PHYIF                 (1<<3)
#define USBC_PHYIF_MASK            (1<<3)
#define USBC_PHYIF_SHIFT           (3)
#define USBC_ULPI_UTMI_SEL         (1<<4)
#define USBC_ULPI_UTMI_SEL_MASK    (1<<4)
#define USBC_ULPI_UTMI_SEL_SHIFT   (4)
#define USBC_FSINTF                (1<<5)
#define USBC_FSINTF_MASK           (1<<5)
#define USBC_FSINTF_SHIFT          (5)
#define USBC_PHYSEL                (1<<6)
#define USBC_PHYSEL_MASK           (1<<6)
#define USBC_PHYSEL_SHIFT          (6)
#define USBC_DDRSEL                (1<<7)
#define USBC_DDRSEL_MASK           (1<<7)
#define USBC_DDRSEL_SHIFT          (7)
#define USBC_SRPCAP                (1<<8)
#define USBC_SRPCAP_MASK           (1<<8)
#define USBC_SRPCAP_SHIFT          (8)
#define USBC_HNPCAP                (1<<9)
#define USBC_HNPCAP_MASK           (1<<9)
#define USBC_HNPCAP_SHIFT          (9)
#define USBC_USBTRDTIM(n)          (((n)&15)<<10)
#define USBC_USBTRDTIM_MASK        (15<<10)
#define USBC_USBTRDTIM_SHIFT       (10)
#define USBC_PHYPWRCLKSEL          (1<<15)
#define USBC_PHYPWRCLKSEL_MASK     (1<<15)
#define USBC_PHYPWRCLKSEL_SHIFT    (15)
#define USBC_OTGI2CSEL             (1<<16)
#define USBC_OTGI2CSEL_MASK        (1<<16)
#define USBC_OTGI2CSEL_SHIFT       (16)
#define USBC_ULPIFSLS              (1<<17)
#define USBC_ULPIFSLS_MASK         (1<<17)
#define USBC_ULPIFSLS_SHIFT        (17)
#define USBC_ULPIAUTORES           (1<<18)
#define USBC_ULPIAUTORES_MASK      (1<<18)
#define USBC_ULPIAUTORES_SHIFT     (18)
#define USBC_ULPICLKSUSM           (1<<19)
#define USBC_ULPICLKSUSM_MASK      (1<<19)
#define USBC_ULPICLKSUSM_SHIFT     (19)
#define USBC_ULPIEXTVBUSDRV        (1<<20)
#define USBC_ULPIEXTVBUSDRV_MASK   (1<<20)
#define USBC_ULPIEXTVBUSDRV_SHIFT  (20)
#define USBC_ULPIEXTVBUSINDICATOR  (1<<21)
#define USBC_ULPIEXTVBUSINDICATOR_MASK (1<<21)
#define USBC_ULPIEXTVBUSINDICATOR_SHIFT (21)
#define USBC_TERMSELDLPULSE        (1<<22)
#define USBC_TERMSELDLPULSE_MASK   (1<<22)
#define USBC_TERMSELDLPULSE_SHIFT  (22)
#define USBC_FORCEHSTMODE          (1<<29)
#define USBC_FORCEHSTMODE_MASK     (1<<29)
#define USBC_FORCEHSTMODE_SHIFT    (29)
#define USBC_FORCEDEVMODE          (1<<30)
#define USBC_FORCEDEVMODE_MASK     (1<<30)
#define USBC_FORCEDEVMODE_SHIFT    (30)
#define USBC_CORRUPTTXPACKET       (1<<31)
#define USBC_CORRUPTTXPACKET_MASK  (1<<31)
#define USBC_CORRUPTTXPACKET_SHIFT (31)

//GRSTCTL
#define USBC_CSFTRST               (1<<0)
#define USBC_CSFTRST_MASK          (1<<0)
#define USBC_CSFTRST_SHIFT         (0)
#define USBC_HSFTRST               (1<<1)
#define USBC_HSFTRST_MASK          (1<<1)
#define USBC_HSFTRST_SHIFT         (1)
#define USBC_FRMCNTRRST            (1<<2)
#define USBC_FRMCNTRRST_MASK       (1<<2)
#define USBC_FRMCNTRRST_SHIFT      (2)
#define USBC_INTKNQFLSH            (1<<3)
#define USBC_INTKNQFLSH_MASK       (1<<3)
#define USBC_INTKNQFLSH_SHIFT      (3)
#define USBC_RXFFLSH               (1<<4)
#define USBC_RXFFLSH_MASK          (1<<4)
#define USBC_RXFFLSH_SHIFT         (4)
#define USBC_TXFFLSH               (1<<5)
#define USBC_TXFFLSH_MASK          (1<<5)
#define USBC_TXFFLSH_SHIFT         (5)
#define USBC_TXFNUM(n)             (((n)&31)<<6)
#define USBC_TXFNUM_MASK           (31<<6)
#define USBC_TXFNUM_SHIFT          (6)
#define USBC_DMAREQ                (1<<30)
#define USBC_DMAREQ_MASK           (1<<30)
#define USBC_DMAREQ_SHIFT          (30)
#define USBC_AHBIDLE               (1<<31)
#define USBC_AHBIDLE_MASK          (1<<31)
#define USBC_AHBIDLE_SHIFT         (31)

//GINTSTS
#define USBC_CURMOD                (1<<0)
#define USBC_CURMOD_MASK           (1<<0)
#define USBC_CURMOD_SHIFT          (0)
#define USBC_MODEMIS               (1<<1)
#define USBC_MODEMIS_MASK          (1<<1)
#define USBC_MODEMIS_SHIFT         (1)
#define USBC_OTGINT                (1<<2)
#define USBC_OTGINT_MASK           (1<<2)
#define USBC_OTGINT_SHIFT          (2)
#define USBC_SOF                   (1<<3)
#define USBC_SOF_MASK              (1<<3)
#define USBC_SOF_SHIFT             (3)
#define USBC_RXFLVL                (1<<4)
#define USBC_RXFLVL_MASK           (1<<4)
#define USBC_RXFLVL_SHIFT          (4)
#define USBC_NPTXFEMP              (1<<5)
#define USBC_NPTXFEMP_MASK         (1<<5)
#define USBC_NPTXFEMP_SHIFT        (5)
#define USBC_GINNAKEFF             (1<<6)
#define USBC_GINNAKEFF_MASK        (1<<6)
#define USBC_GINNAKEFF_SHIFT       (6)
#define USBC_GOUTNAKEFF            (1<<7)
#define USBC_GOUTNAKEFF_MASK       (1<<7)
#define USBC_GOUTNAKEFF_SHIFT      (7)
#define USBC_ULPICKINT             (1<<8)
#define USBC_ULPICKINT_MASK        (1<<8)
#define USBC_ULPICKINT_SHIFT       (8)
#define USBC_I2CINT                (1<<9)
#define USBC_I2CINT_MASK           (1<<9)
#define USBC_I2CINT_SHIFT          (9)
#define USBC_ERLYSUSP              (1<<10)
#define USBC_ERLYSUSP_MASK         (1<<10)
#define USBC_ERLYSUSP_SHIFT        (10)
#define USBC_USBSUSP               (1<<11)
#define USBC_USBSUSP_MASK          (1<<11)
#define USBC_USBSUSP_SHIFT         (11)
#define USBC_USBRST                (1<<12)
#define USBC_USBRST_MASK           (1<<12)
#define USBC_USBRST_SHIFT          (12)
#define USBC_ENUMDONE              (1<<13)
#define USBC_ENUMDONE_MASK         (1<<13)
#define USBC_ENUMDONE_SHIFT        (13)
#define USBC_ISOOUTDROP            (1<<14)
#define USBC_ISOOUTDROP_MASK       (1<<14)
#define USBC_ISOOUTDROP_SHIFT      (14)
#define USBC_EOPF                  (1<<15)
#define USBC_EOPF_MASK             (1<<15)
#define USBC_EOPF_SHIFT            (15)
#define USBC_EPMIS                 (1<<17)
#define USBC_EPMIS_MASK            (1<<17)
#define USBC_EPMIS_SHIFT           (17)
#define USBC_IEPINT                (1<<18)
#define USBC_IEPINT_MASK           (1<<18)
#define USBC_IEPINT_SHIFT          (18)
#define USBC_OEPINT                (1<<19)
#define USBC_OEPINT_MASK           (1<<19)
#define USBC_OEPINT_SHIFT          (19)
#define USBC_INCOMPLSOIN           (1<<20)
#define USBC_INCOMPLSOIN_MASK      (1<<20)
#define USBC_INCOMPLSOIN_SHIFT     (20)
#define USBC_INCOMPIP              (1<<21)
#define USBC_INCOMPIP_MASK         (1<<21)
#define USBC_INCOMPIP_SHIFT        (21)
#define USBC_FETSUSP               (1<<22)
#define USBC_FETSUSP_MASK          (1<<22)
#define USBC_FETSUSP_SHIFT         (22)
#define USBC_PRTINT                (1<<24)
#define USBC_PRTINT_MASK           (1<<24)
#define USBC_PRTINT_SHIFT          (24)
#define USBC_HCHINT                (1<<25)
#define USBC_HCHINT_MASK           (1<<25)
#define USBC_HCHINT_SHIFT          (25)
#define USBC_PTXFEMP               (1<<26)
#define USBC_PTXFEMP_MASK          (1<<26)
#define USBC_PTXFEMP_SHIFT         (26)
#define USBC_CONLDSTSCHNG          (1<<28)
#define USBC_CONLDSTSCHNG_MASK     (1<<28)
#define USBC_CONLDSTSCHNG_SHIFT    (28)
#define USBC_DISCONNINT            (1<<29)
#define USBC_DISCONNINT_MASK       (1<<29)
#define USBC_DISCONNINT_SHIFT      (29)
#define USBC_SESSREQINT            (1<<30)
#define USBC_SESSREQINT_MASK       (1<<30)
#define USBC_SESSREQINT_SHIFT      (30)
#define USBC_WKUPINT               (1<<31)
#define USBC_WKUPINT_MASK          (1<<31)
#define USBC_WKUPINT_SHIFT         (31)

//GINTMSK
//#define USBC_MODEMIS             (1<<1)
//#define USBC_MODEMIS_MASK        (1<<1)
//#define USBC_MODEMIS_SHIFT       (1)
//#define USBC_OTGINT              (1<<2)
//#define USBC_OTGINT_MASK         (1<<2)
//#define USBC_OTGINT_SHIFT        (2)
//#define USBC_SOF                 (1<<3)
//#define USBC_SOF_MASK            (1<<3)
//#define USBC_SOF_SHIFT           (3)
//#define USBC_RXFLVL              (1<<4)
//#define USBC_RXFLVL_MASK         (1<<4)
//#define USBC_RXFLVL_SHIFT        (4)
//#define USBC_NPTXFEMP            (1<<5)
//#define USBC_NPTXFEMP_MASK       (1<<5)
//#define USBC_NPTXFEMP_SHIFT      (5)
//#define USBC_GINNAKEFF           (1<<6)
//#define USBC_GINNAKEFF_MASK      (1<<6)
//#define USBC_GINNAKEFF_SHIFT     (6)
//#define USBC_GOUTNAKEFF          (1<<7)
//#define USBC_GOUTNAKEFF_MASK     (1<<7)
//#define USBC_GOUTNAKEFF_SHIFT    (7)
//#define USBC_ULPICKINT           (1<<8)
//#define USBC_ULPICKINT_MASK      (1<<8)
//#define USBC_ULPICKINT_SHIFT     (8)
//#define USBC_I2CINT              (1<<9)
//#define USBC_I2CINT_MASK         (1<<9)
//#define USBC_I2CINT_SHIFT        (9)
//#define USBC_ERLYSUSP            (1<<10)
//#define USBC_ERLYSUSP_MASK       (1<<10)
//#define USBC_ERLYSUSP_SHIFT      (10)
//#define USBC_USBSUSP             (1<<11)
//#define USBC_USBSUSP_MASK        (1<<11)
//#define USBC_USBSUSP_SHIFT       (11)
//#define USBC_USBRST              (1<<12)
//#define USBC_USBRST_MASK         (1<<12)
//#define USBC_USBRST_SHIFT        (12)
//#define USBC_ENUMDONE            (1<<13)
//#define USBC_ENUMDONE_MASK       (1<<13)
//#define USBC_ENUMDONE_SHIFT      (13)
//#define USBC_ISOOUTDROP          (1<<14)
//#define USBC_ISOOUTDROP_MASK     (1<<14)
//#define USBC_ISOOUTDROP_SHIFT    (14)
//#define USBC_EOPF                (1<<15)
//#define USBC_EOPF_MASK           (1<<15)
//#define USBC_EOPF_SHIFT          (15)
//#define USBC_EPMIS               (1<<17)
//#define USBC_EPMIS_MASK          (1<<17)
//#define USBC_EPMIS_SHIFT         (17)
//#define USBC_IEPINT              (1<<18)
//#define USBC_IEPINT_MASK         (1<<18)
//#define USBC_IEPINT_SHIFT        (18)
//#define USBC_OEPINT              (1<<19)
//#define USBC_OEPINT_MASK         (1<<19)
//#define USBC_OEPINT_SHIFT        (19)
//#define USBC_INCOMPLSOIN         (1<<20)
//#define USBC_INCOMPLSOIN_MASK    (1<<20)
//#define USBC_INCOMPLSOIN_SHIFT   (20)
//#define USBC_INCOMPIP            (1<<21)
//#define USBC_INCOMPIP_MASK       (1<<21)
//#define USBC_INCOMPIP_SHIFT      (21)
//#define USBC_FETSUSP             (1<<22)
//#define USBC_FETSUSP_MASK        (1<<22)
//#define USBC_FETSUSP_SHIFT       (22)
//#define USBC_PRTINT              (1<<24)
//#define USBC_PRTINT_MASK         (1<<24)
//#define USBC_PRTINT_SHIFT        (24)
//#define USBC_HCHINT              (1<<25)
//#define USBC_HCHINT_MASK         (1<<25)
//#define USBC_HCHINT_SHIFT        (25)
//#define USBC_PTXFEMP             (1<<26)
//#define USBC_PTXFEMP_MASK        (1<<26)
//#define USBC_PTXFEMP_SHIFT       (26)
//#define USBC_CONLDSTSCHNG        (1<<28)
//#define USBC_CONLDSTSCHNG_MASK   (1<<28)
//#define USBC_CONLDSTSCHNG_SHIFT  (28)
//#define USBC_DISCONNINT          (1<<29)
//#define USBC_DISCONNINT_MASK     (1<<29)
//#define USBC_DISCONNINT_SHIFT    (29)
//#define USBC_SESSREQINT          (1<<30)
//#define USBC_SESSREQINT_MASK     (1<<30)
//#define USBC_SESSREQINT_SHIFT    (30)
//#define USBC_WKUPINT             (1<<31)
//#define USBC_WKUPINT_MASK        (1<<31)
//#define USBC_WKUPINT_SHIFT       (31)

//GRXSTSR
#define USBC_EPNUM(n)              (((n)&15)<<0)
#define USBC_EPNUM_MASK            (15<<0)
#define USBC_EPNUM_SHIFT           (0)
#define USBC_BCNT(n)               (((n)&0x7FF)<<4)
#define USBC_BCNT_MASK             (0x7FF<<4)
#define USBC_BCNT_SHIFT            (4)
#define USBC_DPID(n)               (((n)&3)<<15)
#define USBC_DPID_MASK             (3<<15)
#define USBC_DPID_SHIFT            (15)
#define USBC_PKTSTS(n)             (((n)&15)<<17)
#define USBC_PKTSTS_MASK           (15<<17)
#define USBC_PKTSTS_SHIFT          (17)
#define USBC_FN(n)                 (((n)&15)<<21)
#define USBC_FN_MASK               (15<<21)
#define USBC_FN_SHIFT              (21)

//GRXSTSP
//#define USBC_EPNUM(n)            (((n)&15)<<0)
//#define USBC_EPNUM_MASK          (15<<0)
//#define USBC_EPNUM_SHIFT         (0)
//#define USBC_BCNT(n)             (((n)&0x7FF)<<4)
//#define USBC_BCNT_MASK           (0x7FF<<4)
//#define USBC_BCNT_SHIFT          (4)
//#define USBC_DPID(n)             (((n)&3)<<15)
//#define USBC_DPID_MASK           (3<<15)
//#define USBC_DPID_SHIFT          (15)
//#define USBC_PKTSTS(n)           (((n)&15)<<17)
//#define USBC_PKTSTS_MASK         (15<<17)
//#define USBC_PKTSTS_SHIFT        (17)
//#define USBC_FN(n)               (((n)&15)<<21)
//#define USBC_FN_MASK             (15<<21)
//#define USBC_FN_SHIFT            (21)

//GRXFSIZ
#define USBC_RXFDEP(n)             (((n)&0xFFFF)<<0)
#define USBC_RXFDEP_MASK           (0xFFFF<<0)
#define USBC_RXFDEP_SHIFT          (0)

//GNPTXFSIZ
#define USBC_NPTXFSTADDR(n)        (((n)&0xFFFF)<<0)
#define USBC_NPTXFSTADDR_MASK      (0xFFFF<<0)
#define USBC_NPTXFSTADDR_SHIFT     (0)
#define USBC_NPTXFDEPS(n)          (((n)&0xFFFF)<<16)
#define USBC_NPTXFDEPS_MASK        (0xFFFF<<16)
#define USBC_NPTXFDEPS_SHIFT       (16)

//GNPTXSTS
#define USBC_NPTXFSPCAVAIL(n)      (((n)&0xFFFF)<<0)
#define USBC_NPTXFSPCAVAIL_MASK    (0xFFFF<<0)
#define USBC_NPTXFSPCAVAIL_SHIFT   (0)
#define USBC_NPTXQSPCAVAIL(n)      (((n)&0xFF)<<16)
#define USBC_NPTXQSPCAVAIL_MASK    (0xFF<<16)
#define USBC_NPTXQSPCAVAIL_SHIFT   (16)
#define USBC_NPTXQTOP(n)           (((n)&0x7F)<<24)
#define USBC_NPTXQTOP_MASK         (0x7F<<24)
#define USBC_NPTXQTOP_SHIFT        (24)

//GUID
#define USBC_USERID(n)             (((n)&0xFFFFFFFF)<<0)
#define USBC_USERID_MASK           (0xFFFFFFFF<<0)
#define USBC_USERID_SHIFT          (0)

//GSNPSID
#define USBC_SYNOPSYSID(n)         (((n)&0xFFFFFFFF)<<0)
#define USBC_SYNOPSYSID_MASK       (0xFFFFFFFF<<0)
#define USBC_SYNOPSYSID_SHIFT      (0)

//GHWCFG1
#define USBC_EPDIR(n)              (((n)&0xFFFFFFFF)<<0)
#define USBC_EPDIR_MASK            (0xFFFFFFFF<<0)
#define USBC_EPDIR_SHIFT           (0)

//GHWCFG2
#define USBC_OTGMODE(n)            (((n)&7)<<0)
#define USBC_OTGMODE_MASK          (7<<0)
#define USBC_OTGMODE_SHIFT         (0)
#define USBC_OTGARCH(n)            (((n)&3)<<3)
#define USBC_OTGARCH_MASK          (3<<3)
#define USBC_OTGARCH_SHIFT         (3)
#define USBC_SINGPNT               (1<<5)
#define USBC_SINGPNT_MASK          (1<<5)
#define USBC_SINGPNT_SHIFT         (5)
#define USBC_HSPHYTYPE(n)          (((n)&3)<<6)
#define USBC_HSPHYTYPE_MASK        (3<<6)
#define USBC_HSPHYTYPE_SHIFT       (6)
#define USBC_FSPHYTYPE(n)          (((n)&3)<<8)
#define USBC_FSPHYTYPE_MASK        (3<<8)
#define USBC_FSPHYTYPE_SHIFT       (8)
#define USBC_NUMDEVEPS(n)          (((n)&15)<<10)
#define USBC_NUMDEVEPS_MASK        (15<<10)
#define USBC_NUMDEVEPS_SHIFT       (10)
#define USBC_NUMHSTCHNL(n)         (((n)&15)<<14)
#define USBC_NUMHSTCHNL_MASK       (15<<14)
#define USBC_NUMHSTCHNL_SHIFT      (14)
#define USBC_PERIOSUPPORT          (1<<18)
#define USBC_PERIOSUPPORT_MASK     (1<<18)
#define USBC_PERIOSUPPORT_SHIFT    (18)
#define USBC_DYNFIFOSIZING         (1<<19)
#define USBC_DYNFIFOSIZING_MASK    (1<<19)
#define USBC_DYNFIFOSIZING_SHIFT   (19)
#define USBC_NPTXQDEPTH(n)         (((n)&3)<<22)
#define USBC_NPTXQDEPTH_MASK       (3<<22)
#define USBC_NPTXQDEPTH_SHIFT      (22)
#define USBC_PTXQDEPTH(n)          (((n)&3)<<24)
#define USBC_PTXQDEPTH_MASK        (3<<24)
#define USBC_PTXQDEPTH_SHIFT       (24)
#define USBC_TKNQDEPTH(n)          (((n)&31)<<26)
#define USBC_TKNQDEPTH_MASK        (31<<26)
#define USBC_TKNQDEPTH_SHIFT       (26)

//GHWCFG3
#define USBC_XFERSIZEWIDTH(n)      (((n)&15)<<0)
#define USBC_XFERSIZEWIDTH_MASK    (15<<0)
#define USBC_XFERSIZEWIDTH_SHIFT   (0)
#define USBC_PKTSIZEWIDTH(n)       (((n)&7)<<4)
#define USBC_PKTSIZEWIDTH_MASK     (7<<4)
#define USBC_PKTSIZEWIDTH_SHIFT    (4)
#define USBC_OTGEN                 (1<<7)
#define USBC_OTGEN_MASK            (1<<7)
#define USBC_OTGEN_SHIFT           (7)
#define USBC_I2CINTSEL             (1<<8)
#define USBC_I2CINTSEL_MASK        (1<<8)
#define USBC_I2CINTSEL_SHIFT       (8)
#define USBC_VNDCTLSUPT            (1<<9)
#define USBC_VNDCTLSUPT_MASK       (1<<9)
#define USBC_VNDCTLSUPT_SHIFT      (9)
#define USBC_OPTFEATURE            (1<<10)
#define USBC_OPTFEATURE_MASK       (1<<10)
#define USBC_OPTFEATURE_SHIFT      (10)
#define USBC_RSTTYPE               (1<<11)
#define USBC_RSTTYPE_MASK          (1<<11)
#define USBC_RSTTYPE_SHIFT         (11)
#define USBC_DFIFODEPTH(n)         (((n)&0xFFFF)<<16)
#define USBC_DFIFODEPTH_MASK       (0xFFFF<<16)
#define USBC_DFIFODEPTH_SHIFT      (16)

//GHWCFG4
#define USBC_NUMDEVPERIOEPS(n)     (((n)&15)<<0)
#define USBC_NUMDEVPERIOEPS_MASK   (15<<0)
#define USBC_NUMDEVPERIOEPS_SHIFT  (0)
#define USBC_ENABLEPWROPT          (1<<4)
#define USBC_ENABLEPWROPT_MASK     (1<<4)
#define USBC_ENABLEPWROPT_SHIFT    (4)
#define USBC_AHBFREQ               (1<<5)
#define USBC_AHBFREQ_MASK          (1<<5)
#define USBC_AHBFREQ_SHIFT         (5)
#define USBC_PHYDATAWIDTH(n)       (((n)&3)<<14)
#define USBC_PHYDATAWIDTH_MASK     (3<<14)
#define USBC_PHYDATAWIDTH_SHIFT    (14)
#define USBC_NUMCTLEPS(n)          (((n)&15)<<16)
#define USBC_NUMCTLEPS_MASK        (15<<16)
#define USBC_NUMCTLEPS_SHIFT       (16)
#define USBC_IDDIGFLTR             (1<<20)
#define USBC_IDDIGFLTR_MASK        (1<<20)
#define USBC_IDDIGFLTR_SHIFT       (20)
#define USBC_VBUSVALIDFLTR         (1<<21)
#define USBC_VBUSVALIDFLTR_MASK    (1<<21)
#define USBC_VBUSVALIDFLTR_SHIFT   (21)
#define USBC_AVALIDFLTR            (1<<22)
#define USBC_AVALIDFLTR_MASK       (1<<22)
#define USBC_AVALIDFLTR_SHIFT      (22)
#define USBC_BVALIDFLTR            (1<<23)
#define USBC_BVALIDFLTR_MASK       (1<<23)
#define USBC_BVALIDFLTR_SHIFT      (23)
#define USBC_SESSENDFLTR           (1<<24)
#define USBC_SESSENDFLTR_MASK      (1<<24)
#define USBC_SESSENDFLTR_SHIFT     (24)
#define USBC_DEFIFOMODE            (1<<25)
#define USBC_DEFIFOMODE_MASK       (1<<25)
#define USBC_DEFIFOMODE_SHIFT      (25)
#define USBC_INEPS(n)              (((n)&15)<<26)
#define USBC_INEPS_MASK            (15<<26)
#define USBC_INEPS_SHIFT           (26)

//DIEnPTXF
#define USBC_IENPNTXFSTADDR(n)     (((n)&0xFFFF)<<0)
#define USBC_IENPNTXFSTADDR_MASK   (0xFFFF<<0)
#define USBC_IENPNTXFSTADDR_SHIFT  (0)
#define USBC_INEPNTXFDEP(n)        (((n)&0xFFFF)<<16)
#define USBC_INEPNTXFDEP_MASK      (0xFFFF<<16)
#define USBC_INEPNTXFDEP_SHIFT     (16)

//DCFG
#define USBC_DEVSPD(n)             (((n)&3)<<0)
#define USBC_DEVSPD_MASK           (3<<0)
#define USBC_DEVSPD_SHIFT          (0)
#define USBC_NZSTSOUTHSHK          (1<<2)
#define USBC_NZSTSOUTHSHK_MASK     (1<<2)
#define USBC_NZSTSOUTHSHK_SHIFT    (2)
#define USBC_DEVADDR(n)            (((n)&0x7F)<<4)
#define USBC_DEVADDR_MASK          (0x7F<<4)
#define USBC_DEVADDR_SHIFT         (4)
#define USBC_PERFRINT(n)           (((n)&3)<<11)
#define USBC_PERFRINT_MASK         (3<<11)
#define USBC_PERFRINT_SHIFT        (11)
#define USBC_EPMISCNT(n)           (((n)&31)<<18)
#define USBC_EPMISCNT_MASK         (31<<18)
#define USBC_EPMISCNT_SHIFT        (18)

//DCTL
#define USBC_RMTWKUPSIG            (1<<0)
#define USBC_RMTWKUPSIG_MASK       (1<<0)
#define USBC_RMTWKUPSIG_SHIFT      (0)
#define USBC_SFTDISCON             (1<<1)
#define USBC_SFTDISCON_MASK        (1<<1)
#define USBC_SFTDISCON_SHIFT       (1)
#define USBC_GNPINNAKSTS           (1<<2)
#define USBC_GNPINNAKSTS_MASK      (1<<2)
#define USBC_GNPINNAKSTS_SHIFT     (2)
#define USBC_GOUTNAKSTS            (1<<3)
#define USBC_GOUTNAKSTS_MASK       (1<<3)
#define USBC_GOUTNAKSTS_SHIFT      (3)
#define USBC_TSTCTL(n)             (((n)&7)<<4)
#define USBC_TSTCTL_MASK           (7<<4)
#define USBC_TSTCTL_SHIFT          (4)
#define USBC_SGNPINNAK             (1<<7)
#define USBC_SGNPINNAK_MASK        (1<<7)
#define USBC_SGNPINNAK_SHIFT       (7)
#define USBC_CGNPINNAK             (1<<8)
#define USBC_CGNPINNAK_MASK        (1<<8)
#define USBC_CGNPINNAK_SHIFT       (8)
#define USBC_SGOUTNAK              (1<<9)
#define USBC_SGOUTNAK_MASK         (1<<9)
#define USBC_SGOUTNAK_SHIFT        (9)
#define USBC_CGOUTNAK              (1<<10)
#define USBC_CGOUTNAK_MASK         (1<<10)
#define USBC_CGOUTNAK_SHIFT        (10)
#define USBC_PWRONPRGDONE          (1<<11)
#define USBC_PWRONPRGDONE_MASK     (1<<11)
#define USBC_PWRONPRGDONE_SHIFT    (11)

//DSTS
#define USBC_SUSPSTS               (1<<0)
#define USBC_SUSPSTS_MASK          (1<<0)
#define USBC_SUSPSTS_SHIFT         (0)
#define USBC_ENUMSPD(n)            (((n)&3)<<1)
#define USBC_ENUMSPD_MASK          (3<<1)
#define USBC_ENUMSPD_SHIFT         (1)
#define USBC_ERRTICERR             (1<<3)
#define USBC_ERRTICERR_MASK        (1<<3)
#define USBC_ERRTICERR_SHIFT       (3)
#define USBC_SOFFN(n)              (((n)&0x3FFF)<<8)
#define USBC_SOFFN_MASK            (0x3FFF<<8)
#define USBC_SOFFN_SHIFT           (8)

//DIEPMSK
#define USBC_XFERCOMPLMSK          (1<<0)
#define USBC_XFERCOMPLMSK_MASK     (1<<0)
#define USBC_XFERCOMPLMSK_SHIFT    (0)
#define USBC_EPDISBLDMSK           (1<<1)
#define USBC_EPDISBLDMSK_MASK      (1<<1)
#define USBC_EPDISBLDMSK_SHIFT     (1)
#define USBC_AHBERRMSK             (1<<2)
#define USBC_AHBERRMSK_MASK        (1<<2)
#define USBC_AHBERRMSK_SHIFT       (2)
#define USBC_TIMEOUTMSK            (1<<3)
#define USBC_TIMEOUTMSK_MASK       (1<<3)
#define USBC_TIMEOUTMSK_SHIFT      (3)
#define USBC_INTKNTXFEMPMSK        (1<<4)
#define USBC_INTKNTXFEMPMSK_MASK   (1<<4)
#define USBC_INTKNTXFEMPMSK_SHIFT  (4)
#define USBC_INTKNEPMISMSK         (1<<5)
#define USBC_INTKNEPMISMSK_MASK    (1<<5)
#define USBC_INTKNEPMISMSK_SHIFT   (5)
#define USBC_INEPNAKEFFMSK         (1<<6)
#define USBC_INEPNAKEFFMSK_MASK    (1<<6)
#define USBC_INEPNAKEFFMSK_SHIFT   (6)
#define USBC_TXFIFOUNDRNMSK        (1<<8)
#define USBC_TXFIFOUNDRNMSK_MASK   (1<<8)
#define USBC_TXFIFOUNDRNMSK_SHIFT  (8)

//DOEPMSK
//#define USBC_XFERCOMPLMSK        (1<<0)
//#define USBC_XFERCOMPLMSK_MASK   (1<<0)
//#define USBC_XFERCOMPLMSK_SHIFT  (0)
//#define USBC_EPDISBLDMSK         (1<<1)
//#define USBC_EPDISBLDMSK_MASK    (1<<1)
//#define USBC_EPDISBLDMSK_SHIFT   (1)
//#define USBC_AHBERRMSK           (1<<2)
//#define USBC_AHBERRMSK_MASK      (1<<2)
//#define USBC_AHBERRMSK_SHIFT     (2)
#define USBC_SETUPMK               (1<<3)
#define USBC_SETUPMK_MASK          (1<<3)
#define USBC_SETUPMK_SHIFT         (3)
#define USBC_OUTTKNEPDISMSK        (1<<4)
#define USBC_OUTTKNEPDISMSK_MASK   (1<<4)
#define USBC_OUTTKNEPDISMSK_SHIFT  (4)
#define USBC_BACK2BACKSETUP        (1<<6)
#define USBC_BACK2BACKSETUP_MASK   (1<<6)
#define USBC_BACK2BACKSETUP_SHIFT  (6)
#define USBC_OUTPKTERRMSK          (1<<8)
#define USBC_OUTPKTERRMSK_MASK     (1<<8)
#define USBC_OUTPKTERRMSK_SHIFT    (8)

//DAINT
#define USBC_INEPINT(n)            (((n)&0xFFFF)<<0)
#define USBC_INEPINT_MASK          (0xFFFF<<0)
#define USBC_INEPINT_SHIFT         (0)
#define USBC_OUTEPINT(n)           (((n)&0xFFFF)<<16)
#define USBC_OUTEPINT_MASK         (0xFFFF<<16)
#define USBC_OUTEPINT_SHIFT        (16)

//DAINTMSK
#define USBC_INEPMSK(n)            (((n)&0xFFFF)<<0)
#define USBC_INEPMSK_MASK          (0xFFFF<<0)
#define USBC_INEPMSK_SHIFT         (0)
#define USBC_OUTEPMSK(n)           (((n)&0xFFFF)<<16)
#define USBC_OUTEPMSK_MASK         (0xFFFF<<16)
#define USBC_OUTEPMSK_SHIFT        (16)

//DVBUSDIS
#define USBC_DVBUSDIS(n)           (((n)&0xFFFF)<<0)
#define USBC_DVBUSDIS_MASK         (0xFFFF<<0)
#define USBC_DVBUSDIS_SHIFT        (0)

//DVBUSPULSE
#define USBC_DVBUSPULSE(n)         (((n)&0xFFF)<<0)
#define USBC_DVBUSPULSE_MASK       (0xFFF<<0)
#define USBC_DVBUSPULSE_SHIFT      (0)

//DTHRCTL
#define USBC_NONISOTHREN           (1<<0)
#define USBC_NONISOTHREN_MASK      (1<<0)
#define USBC_NONISOTHREN_SHIFT     (0)
#define USBC_ISOTHREN              (1<<1)
#define USBC_ISOTHREN_MASK         (1<<1)
#define USBC_ISOTHREN_SHIFT        (1)
#define USBC_TXTHRLEN(n)           (((n)&0x1FF)<<2)
#define USBC_TXTHRLEN_MASK         (0x1FF<<2)
#define USBC_TXTHRLEN_SHIFT        (2)
#define USBC_RXTHREN               (1<<16)
#define USBC_RXTHREN_MASK          (1<<16)
#define USBC_RXTHREN_SHIFT         (16)
#define USBC_RXTHRLEN(n)           (((n)&0x1FF)<<17)
#define USBC_RXTHRLEN_MASK         (0x1FF<<17)
#define USBC_RXTHRLEN_SHIFT        (17)
#define USBC_ARBPRKEN              (1<<27)
#define USBC_ARBPRKEN_MASK         (1<<27)
#define USBC_ARBPRKEN_SHIFT        (27)

//DIEPEMPMSK
#define USBC_INEPTXFEMPMSK(n)      (((n)&0xFFFF)<<0)
#define USBC_INEPTXFEMPMSK_MASK    (0xFFFF<<0)
#define USBC_INEPTXFEMPMSK_SHIFT   (0)

//DIEPCTL0
#define USBC_EP0_MPS(n)            (((n)&3)<<0)
#define USBC_EP0_MPS_MASK          (3<<0)
#define USBC_EP0_MPS_SHIFT         (0)
#define USBC_NEXTEP(n)             (((n)&15)<<11)
#define USBC_NEXTEP_MASK           (15<<11)
#define USBC_NEXTEP_SHIFT          (11)
#define USBC_USBACTEP              (1<<15)
#define USBC_USBACTEP_MASK         (1<<15)
#define USBC_USBACTEP_SHIFT        (15)
#define USBC_NAKSTS                (1<<17)
#define USBC_NAKSTS_MASK           (1<<17)
#define USBC_NAKSTS_SHIFT          (17)
#define USBC_EPTYPE(n)             (((n)&3)<<18)
#define USBC_EPTYPE_MASK           (3<<18)
#define USBC_EPTYPE_SHIFT          (18)
#define USBC_STALL                 (1<<21)
#define USBC_STALL_MASK            (1<<21)
#define USBC_STALL_SHIFT           (21)
#define USBC_EPTXFNUM(n)           (((n)&15)<<22)
#define USBC_EPTXFNUM_MASK         (15<<22)
#define USBC_EPTXFNUM_SHIFT        (22)
#define USBC_CNAK                  (1<<26)
#define USBC_CNAK_MASK             (1<<26)
#define USBC_CNAK_SHIFT            (26)
#define USBC_SNAK                  (1<<27)
#define USBC_SNAK_MASK             (1<<27)
#define USBC_SNAK_SHIFT            (27)
#define USBC_EPDIS                 (1<<30)
#define USBC_EPDIS_MASK            (1<<30)
#define USBC_EPDIS_SHIFT           (30)
#define USBC_EPENA                 (1<<31)
#define USBC_EPENA_MASK            (1<<31)
#define USBC_EPENA_SHIFT           (31)

//DIEPINT0
#define USBC_XFERCOMPL             (1<<0)
#define USBC_XFERCOMPL_MASK        (1<<0)
#define USBC_XFERCOMPL_SHIFT       (0)
#define USBC_EPDISBLD              (1<<1)
#define USBC_EPDISBLD_MASK         (1<<1)
#define USBC_EPDISBLD_SHIFT        (1)
#define USBC_AHBERR                (1<<2)
#define USBC_AHBERR_MASK           (1<<2)
#define USBC_AHBERR_SHIFT          (2)
#define USBC_TIMEOUT               (1<<3)
#define USBC_TIMEOUT_MASK          (1<<3)
#define USBC_TIMEOUT_SHIFT         (3)
#define USBC_INTKNTXFEMP           (1<<4)
#define USBC_INTKNTXFEMP_MASK      (1<<4)
#define USBC_INTKNTXFEMP_SHIFT     (4)
#define USBC_INTKNEPMIS            (1<<5)
#define USBC_INTKNEPMIS_MASK       (1<<5)
#define USBC_INTKNEPMIS_SHIFT      (5)
#define USBC_INEPNAKEFF            (1<<6)
#define USBC_INEPNAKEFF_MASK       (1<<6)
#define USBC_INEPNAKEFF_SHIFT      (6)
#define USBC_TXFEMP                (1<<7)
#define USBC_TXFEMP_MASK           (1<<7)
#define USBC_TXFEMP_SHIFT          (7)
#define USBC_TXFIFOUNDRN           (1<<8)
#define USBC_TXFIFOUNDRN_MASK      (1<<8)
#define USBC_TXFIFOUNDRN_SHIFT     (8)

//DIEPTSIZ0
#define USBC_IEPXFERSIZE0(n)       (((n)&0x7F)<<0)
#define USBC_IEPXFERSIZE0_MASK     (0x7F<<0)
#define USBC_IEPXFERSIZE0_SHIFT    (0)
#define USBC_IEPPKTCNT0(n)         (((n)&3)<<19)
#define USBC_IEPPKTCNT0_MASK       (3<<19)
#define USBC_IEPPKTCNT0_SHIFT      (19)

//DIEPDMA0
#define USBC_DMAADDR(n)            (((n)&0xFFFFFFFF)<<0)
#define USBC_DMAADDR_MASK          (0xFFFFFFFF<<0)
#define USBC_DMAADDR_SHIFT         (0)

//DIEPFSTS0
#define USBC_INEPTXFSPCAVAIL(n)    (((n)&0xFFFF)<<0)
#define USBC_INEPTXFSPCAVAIL_MASK  (0xFFFF<<0)
#define USBC_INEPTXFSPCAVAIL_SHIFT (0)

//DIEPCTL
#define USBC_EPN_MPS(n)            (((n)&0x7FF)<<0)
#define USBC_EPN_MPS_MASK          (0x7FF<<0)
#define USBC_EPN_MPS_SHIFT         (0)
//#define USBC_NEXTEP(n)           (((n)&15)<<11)
//#define USBC_NEXTEP_MASK         (15<<11)
//#define USBC_NEXTEP_SHIFT        (11)
//#define USBC_USBACTEP            (1<<15)
//#define USBC_USBACTEP_MASK       (1<<15)
//#define USBC_USBACTEP_SHIFT      (15)
#define USBC_IEP_DPID              (1<<16)
#define USBC_IEP_DPID_MASK         (1<<16)
#define USBC_IEP_DPID_SHIFT        (16)
//#define USBC_NAKSTS              (1<<17)
//#define USBC_NAKSTS_MASK         (1<<17)
//#define USBC_NAKSTS_SHIFT        (17)
//#define USBC_EPTYPE(n)           (((n)&3)<<18)
//#define USBC_EPTYPE_MASK         (3<<18)
//#define USBC_EPTYPE_SHIFT        (18)
#define USBC_SNP                   (1<<20)
#define USBC_SNP_MASK              (1<<20)
#define USBC_SNP_SHIFT             (20)
//#define USBC_STALL               (1<<21)
//#define USBC_STALL_MASK          (1<<21)
//#define USBC_STALL_SHIFT         (21)
//#define USBC_EPTXFNUM(n)         (((n)&15)<<22)
//#define USBC_EPTXFNUM_MASK       (15<<22)
//#define USBC_EPTXFNUM_SHIFT      (22)
//#define USBC_CNAK                (1<<26)
//#define USBC_CNAK_MASK           (1<<26)
//#define USBC_CNAK_SHIFT          (26)
//#define USBC_SNAK                (1<<27)
//#define USBC_SNAK_MASK           (1<<27)
//#define USBC_SNAK_SHIFT          (27)
#define USBC_SETD0PID              (1<<28)
#define USBC_SETD0PID_MASK         (1<<28)
#define USBC_SETD0PID_SHIFT        (28)
#define USBC_SETD1PID              (1<<29)
#define USBC_SETD1PID_MASK         (1<<29)
#define USBC_SETD1PID_SHIFT        (29)
//#define USBC_EPDIS               (1<<30)
//#define USBC_EPDIS_MASK          (1<<30)
//#define USBC_EPDIS_SHIFT         (30)
//#define USBC_EPENA               (1<<31)
//#define USBC_EPENA_MASK          (1<<31)
//#define USBC_EPENA_SHIFT         (31)

//DIEPINT
//#define USBC_XFERCOMPL           (1<<0)
//#define USBC_XFERCOMPL_MASK      (1<<0)
//#define USBC_XFERCOMPL_SHIFT     (0)
//#define USBC_EPDISBLD            (1<<1)
//#define USBC_EPDISBLD_MASK       (1<<1)
//#define USBC_EPDISBLD_SHIFT      (1)
//#define USBC_AHBERR              (1<<2)
//#define USBC_AHBERR_MASK         (1<<2)
//#define USBC_AHBERR_SHIFT        (2)
//#define USBC_TIMEOUT             (1<<3)
//#define USBC_TIMEOUT_MASK        (1<<3)
//#define USBC_TIMEOUT_SHIFT       (3)
//#define USBC_INTKNTXFEMP         (1<<4)
//#define USBC_INTKNTXFEMP_MASK    (1<<4)
//#define USBC_INTKNTXFEMP_SHIFT   (4)
//#define USBC_INTKNEPMIS          (1<<5)
//#define USBC_INTKNEPMIS_MASK     (1<<5)
//#define USBC_INTKNEPMIS_SHIFT    (5)
//#define USBC_INEPNAKEFF          (1<<6)
//#define USBC_INEPNAKEFF_MASK     (1<<6)
//#define USBC_INEPNAKEFF_SHIFT    (6)
//#define USBC_TXFEMP              (1<<7)
//#define USBC_TXFEMP_MASK         (1<<7)
//#define USBC_TXFEMP_SHIFT        (7)
//#define USBC_TXFIFOUNDRN         (1<<8)
//#define USBC_TXFIFOUNDRN_MASK    (1<<8)
//#define USBC_TXFIFOUNDRN_SHIFT   (8)

//DIEPTSIZ
#define USBC_IEPXFERSIZE(n)        (((n)&0x7FFFF)<<0)
#define USBC_IEPXFERSIZE_MASK      (0x7FFFF<<0)
#define USBC_IEPXFERSIZE_SHIFT     (0)
#define USBC_IEPPKTCNT(n)          (((n)&0x3FF)<<19)
#define USBC_IEPPKTCNT_MASK        (0x3FF<<19)
#define USBC_IEPPKTCNT_SHIFT       (19)
#define USBC_MC(n)                 (((n)&3)<<29)
#define USBC_MC_MASK               (3<<29)
#define USBC_MC_SHIFT              (29)

//DIEPDMA
//#define USBC_DMAADDR(n)          (((n)&0xFFFFFFFF)<<0)
//#define USBC_DMAADDR_MASK        (0xFFFFFFFF<<0)
//#define USBC_DMAADDR_SHIFT       (0)

//DIEPFSTS
//#define USBC_INEPTXFSPCAVAIL(n)  (((n)&0xFFFF)<<0)
//#define USBC_INEPTXFSPCAVAIL_MASK (0xFFFF<<0)
//#define USBC_INEPTXFSPCAVAIL_SHIFT (0)

//DOEPCTL0
//#define USBC_EP0_MPS(n)          (((n)&3)<<0)
//#define USBC_EP0_MPS_MASK        (3<<0)
//#define USBC_EP0_MPS_SHIFT       (0)
//#define USBC_USBACTEP            (1<<15)
//#define USBC_USBACTEP_MASK       (1<<15)
//#define USBC_USBACTEP_SHIFT      (15)
//#define USBC_NAKSTS              (1<<17)
//#define USBC_NAKSTS_MASK         (1<<17)
//#define USBC_NAKSTS_SHIFT        (17)
//#define USBC_EPTYPE(n)           (((n)&3)<<18)
//#define USBC_EPTYPE_MASK         (3<<18)
//#define USBC_EPTYPE_SHIFT        (18)
//#define USBC_SNP                 (1<<20)
//#define USBC_SNP_MASK            (1<<20)
//#define USBC_SNP_SHIFT           (20)
//#define USBC_STALL               (1<<21)
//#define USBC_STALL_MASK          (1<<21)
//#define USBC_STALL_SHIFT         (21)
//#define USBC_CNAK                (1<<26)
//#define USBC_CNAK_MASK           (1<<26)
//#define USBC_CNAK_SHIFT          (26)
//#define USBC_SNAK                (1<<27)
//#define USBC_SNAK_MASK           (1<<27)
//#define USBC_SNAK_SHIFT          (27)
//#define USBC_EPDIS               (1<<30)
//#define USBC_EPDIS_MASK          (1<<30)
//#define USBC_EPDIS_SHIFT         (30)
//#define USBC_EPENA               (1<<31)
//#define USBC_EPENA_MASK          (1<<31)
//#define USBC_EPENA_SHIFT         (31)

//DOEPINT0
//#define USBC_XFERCOMPL           (1<<0)
//#define USBC_XFERCOMPL_MASK      (1<<0)
//#define USBC_XFERCOMPL_SHIFT     (0)
//#define USBC_EPDISBLD            (1<<1)
//#define USBC_EPDISBLD_MASK       (1<<1)
//#define USBC_EPDISBLD_SHIFT      (1)
//#define USBC_AHBERR              (1<<2)
//#define USBC_AHBERR_MASK         (1<<2)
//#define USBC_AHBERR_SHIFT        (2)
#define USBC_SETUP                 (1<<3)
#define USBC_SETUP_MASK            (1<<3)
#define USBC_SETUP_SHIFT           (3)
//#define USBC_INTKNTXFEMP         (1<<4)
//#define USBC_INTKNTXFEMP_MASK    (1<<4)
//#define USBC_INTKNTXFEMP_SHIFT   (4)
//#define USBC_INTKNEPMIS          (1<<5)
//#define USBC_INTKNEPMIS_MASK     (1<<5)
//#define USBC_INTKNEPMIS_SHIFT    (5)
//#define USBC_INEPNAKEFF          (1<<6)
//#define USBC_INEPNAKEFF_MASK     (1<<6)
//#define USBC_INEPNAKEFF_SHIFT    (6)
//#define USBC_TXFEMP              (1<<7)
//#define USBC_TXFEMP_MASK         (1<<7)
//#define USBC_TXFEMP_SHIFT        (7)
//#define USBC_TXFIFOUNDRN         (1<<8)
//#define USBC_TXFIFOUNDRN_MASK    (1<<8)
//#define USBC_TXFIFOUNDRN_SHIFT   (8)

//DOEPTSIZ0
#define USBC_OEPXFERSIZE0(n)       (((n)&0x7F)<<0)
#define USBC_OEPXFERSIZE0_MASK     (0x7F<<0)
#define USBC_OEPXFERSIZE0_SHIFT    (0)
#define USBC_OEPPKTCNT0            (1<<19)
#define USBC_OEPPKTCNT0_MASK       (1<<19)
#define USBC_OEPPKTCNT0_SHIFT      (19)
#define USBC_SUPCNT(n)             (((n)&3)<<29)
#define USBC_SUPCNT_MASK           (3<<29)
#define USBC_SUPCNT_SHIFT          (29)

//DOEPDMA0
//#define USBC_DMAADDR(n)          (((n)&0xFFFFFFFF)<<0)
//#define USBC_DMAADDR_MASK        (0xFFFFFFFF<<0)
//#define USBC_DMAADDR_SHIFT       (0)

//DOEPCTL
//#define USBC_EPN_MPS(n)          (((n)&0x7FF)<<0)
//#define USBC_EPN_MPS_MASK        (0x7FF<<0)
//#define USBC_EPN_MPS_SHIFT       (0)
//#define USBC_NEXTEP(n)           (((n)&15)<<11)
//#define USBC_NEXTEP_MASK         (15<<11)
//#define USBC_NEXTEP_SHIFT        (11)
//#define USBC_USBACTEP            (1<<15)
//#define USBC_USBACTEP_MASK       (1<<15)
//#define USBC_USBACTEP_SHIFT      (15)
#define USBC_OEP_DPID              (1<<16)
#define USBC_OEP_DPID_MASK         (1<<16)
#define USBC_OEP_DPID_SHIFT        (16)
//#define USBC_NAKSTS              (1<<17)
//#define USBC_NAKSTS_MASK         (1<<17)
//#define USBC_NAKSTS_SHIFT        (17)
//#define USBC_EPTYPE(n)           (((n)&3)<<18)
//#define USBC_EPTYPE_MASK         (3<<18)
//#define USBC_EPTYPE_SHIFT        (18)
//#define USBC_SNP                 (1<<20)
//#define USBC_SNP_MASK            (1<<20)
//#define USBC_SNP_SHIFT           (20)
//#define USBC_STALL               (1<<21)
//#define USBC_STALL_MASK          (1<<21)
//#define USBC_STALL_SHIFT         (21)
//#define USBC_EPTXFNUM(n)         (((n)&15)<<22)
//#define USBC_EPTXFNUM_MASK       (15<<22)
//#define USBC_EPTXFNUM_SHIFT      (22)
//#define USBC_CNAK                (1<<26)
//#define USBC_CNAK_MASK           (1<<26)
//#define USBC_CNAK_SHIFT          (26)
//#define USBC_SNAK                (1<<27)
//#define USBC_SNAK_MASK           (1<<27)
//#define USBC_SNAK_SHIFT          (27)
//#define USBC_SETD0PID            (1<<28)
//#define USBC_SETD0PID_MASK       (1<<28)
//#define USBC_SETD0PID_SHIFT      (28)
//#define USBC_SETD1PID            (1<<29)
//#define USBC_SETD1PID_MASK       (1<<29)
//#define USBC_SETD1PID_SHIFT      (29)
//#define USBC_EPDIS               (1<<30)
//#define USBC_EPDIS_MASK          (1<<30)
//#define USBC_EPDIS_SHIFT         (30)
//#define USBC_EPENA               (1<<31)
//#define USBC_EPENA_MASK          (1<<31)
//#define USBC_EPENA_SHIFT         (31)

//DOEPINT
//#define USBC_XFERCOMPL           (1<<0)
//#define USBC_XFERCOMPL_MASK      (1<<0)
//#define USBC_XFERCOMPL_SHIFT     (0)
//#define USBC_EPDISBLD            (1<<1)
//#define USBC_EPDISBLD_MASK       (1<<1)
//#define USBC_EPDISBLD_SHIFT      (1)
//#define USBC_AHBERR              (1<<2)
//#define USBC_AHBERR_MASK         (1<<2)
//#define USBC_AHBERR_SHIFT        (2)
//#define USBC_SETUP               (1<<3)
//#define USBC_SETUP_MASK          (1<<3)
//#define USBC_SETUP_SHIFT         (3)
//#define USBC_INTKNTXFEMP         (1<<4)
//#define USBC_INTKNTXFEMP_MASK    (1<<4)
//#define USBC_INTKNTXFEMP_SHIFT   (4)
//#define USBC_INTKNEPMIS          (1<<5)
//#define USBC_INTKNEPMIS_MASK     (1<<5)
//#define USBC_INTKNEPMIS_SHIFT    (5)
//#define USBC_INEPNAKEFF          (1<<6)
//#define USBC_INEPNAKEFF_MASK     (1<<6)
//#define USBC_INEPNAKEFF_SHIFT    (6)
//#define USBC_TXFEMP              (1<<7)
//#define USBC_TXFEMP_MASK         (1<<7)
//#define USBC_TXFEMP_SHIFT        (7)
//#define USBC_TXFIFOUNDRN         (1<<8)
//#define USBC_TXFIFOUNDRN_MASK    (1<<8)
//#define USBC_TXFIFOUNDRN_SHIFT   (8)

//DOEPTSIZ
#define USBC_OEPXFERSIZE(n)        (((n)&0x7FFFF)<<0)
#define USBC_OEPXFERSIZE_MASK      (0x7FFFF<<0)
#define USBC_OEPXFERSIZE_SHIFT     (0)
#define USBC_OEPPKTCNT(n)          (((n)&0x3FF)<<19)
#define USBC_OEPPKTCNT_MASK        (0x3FF<<19)
#define USBC_OEPPKTCNT_SHIFT       (19)
//#define USBC_MC(n)               (((n)&3)<<29)
//#define USBC_MC_MASK             (3<<29)
//#define USBC_MC_SHIFT            (29)

//DOEPDMA
//#define USBC_DMAADDR(n)          (((n)&0xFFFFFFFF)<<0)
//#define USBC_DMAADDR_MASK        (0xFFFFFFFF<<0)
//#define USBC_DMAADDR_SHIFT       (0)

//PCGCCTL
#define USBC_STOPPCLK              (1<<0)
#define USBC_STOPPCLK_MASK         (1<<0)
#define USBC_STOPPCLK_SHIFT        (0)
#define USBC_GATEHCLK              (1<<1)
#define USBC_GATEHCLK_MASK         (1<<1)
#define USBC_GATEHCLK_SHIFT        (1)
#define USBC_PWRCLMP               (1<<2)
#define USBC_PWRCLMP_MASK          (1<<2)
#define USBC_PWRCLMP_SHIFT         (2)
#define USBC_RSTPDWNMODULE         (1<<3)
#define USBC_RSTPDWNMODULE_MASK    (1<<3)
#define USBC_RSTPDWNMODULE_SHIFT   (3)
#define USBC_PHYSUSPENDED          (1<<4)
#define USBC_PHYSUSPENDED_MASK     (1<<4)
#define USBC_PHYSUSPENDED_SHIFT    (4)

//TxRxData
#define USBC_TXDATA(n)             (((n)&0xFFFFFFFF)<<0)
#define USBC_TXDATA_MASK           (0xFFFFFFFF<<0)
#define USBC_TXDATA_SHIFT          (0)
#define USBC_RXDATA(n)             (((n)&0xFFFFFFFF)<<0)
#define USBC_RXDATA_MASK           (0xFFFFFFFF<<0)
#define USBC_RXDATA_SHIFT          (0)

//RAMData
#define USBC_DATA(n)               (((n)&0xFFFFFFFF)<<0)
#define USBC_DATA_MASK             (0xFFFFFFFF<<0)
#define USBC_DATA_SHIFT            (0)




#endif
