
NAME := board_cy8ckit_149

HOST_ARCH           := Cortex-M0
HOST_MCU_FAMILY     := cy8c4147

CONFIG_SYSINFO_PRODUCT_MODEL := ALI_AOS_CY8C4147
CONFIG_SYSINFO_DEVICE_NAME := CY8C4147
GLOBAL_CFLAGS += -DSYSINFO_PRODUCT_MODEL=\"$(CONFIG_SYSINFO_PRODUCT_MODEL)\"
GLOBAL_CFLAGS += -DSYSINFO_DEVICE_NAME=\"$(CONFIG_SYSINFO_DEVICE_NAME)\"
GLOBAL_CFLAGS += -DSYSINFO_ARCH=\"$(HOST_ARCH)\"
GLOBAL_CFLAGS += -DSYSINFO_MCU=\"$(HOST_MCU_FAMILY)\"
GLOBAL_CFLAGS += -DCONFIG_NO_TCPIP
GLOBAL_LDFLAGS += 

GLOBAL_INCLUDES += .

$(NAME)_SOURCES     :=
$(NAME)_SOURCES     += ./board.c

TEST_COMPONENTS += certificate
GLOBAL_CFLAGS += -DTEST_CONFIG_YLOOP_ENABLED=0

EXTRA_TARGET_MAKEFILES += $(SOURCE_ROOT)/platform/mcu/$(HOST_MCU_FAMILY)/gen_metadata.mk
