#ifndef _OS_CONFIG_H
#define _OS_CONFIG_H

#define os_debug printf

#define OS_DEBUG_ON 1
#define OS_DEBUG_OFF 0

//#define OS_TASK_DEBUG_INFO OS_DEBUG_ON
//#define OS_TASK_DEBUG_ERROR OS_DEBUG_ON

//#define OS_TIMER_DEBUG_INFO OS_DEBUG_ON
//#define OS_TIMER_DEBUG_ERROR OS_DEBUG_ON

//#define OS_MUTEX_DEBUG_ERROR OS_DEBUG_ON

//#define OS_SEM_DEBUG_INFO OS_DEBUG_ON
//#define OS_SEM_DEBUG_ERROR OS_DEBUG_ON

//#define OS_QUEUE_DEBUG_INFO OS_DEBUG_ON
//#define OS_QUEUE_DEBUG_ERROR OS_DEBUG_ON

//#define OS_EVENT_DEBUG_INFO OS_DEBUG_ON
//#define OS_EVENT_DEBUG_ERROR OS_DEBUG_ON
#endif