/*
 * Copyright 2009-2017 Alibaba Cloud All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

// version = (major << 16) + (minor << 8) + patch
#define ALIBABACLOUD_OSS_VERSION ((1 << 16) + (8 << 8) + 1)

#define ALIBABACLOUD_OSS_VERSION_STR "1.8.1"

// auto generated by cmake option
/* #undef OSS_DISABLE_BUCKET */
/* #undef OSS_DISABLE_LIVECHANNEL */
/* #undef OSS_DISABLE_RESUAMABLE */
/* #undef OSS_DISABLE_ENCRYPTION */
