TARGET = libulog.a
MODULE = ulog

MOD_SOURCES += \
		ulog.c \
		ulog_init.c \
		ulog_utility.c

MOD_INCLUDES := \
		../../adapter/include \
		../linkkit \
		../linkkit/infra \
		. \
		include \
		../../main

include $(TOOLS_DIR)/rules.mk
