/*
 * Copyright (C) 2015-2018 Alibaba Group Holding Limited
 */

#ifndef MBMASTER_DEFAULT_CONFIG_H
#define MBMASTER_DEFAULT_CONFIG_H

#ifndef MBMASTER_CONFIG_RTU_ENABLED
#define MBMASTER_CONFIG_RTU_ENABLED   1
#endif

#ifndef MBMASTER_CONFIG_ASCII_ENABLED
#define MBMASTER_CONFIG_ASCII_ENABLED 0
#endif

#ifndef MBMASTER_CONFIG_TCP_ENABLED
#define MBMASTER_CONFIG_TCP_ENABLED   0
#endif

#ifndef MBMASTER_CONFIG_HANDLER_MAX
#define MBMASTER_CONFIG_HANDLER_MAX   1
#endif

#endif /* MBMASTER_DEFAULT_CONFIG_H */
