/*
 * Copyright (C) 2015-2017 Alibaba Group Holding Limited
 */

#ifndef VFS_CONF_H
#define VFS_CONF_H

#ifndef CONFIG_VFS_DEVICE_NODES
#define VFS_DEVICE_NODES 25
#else
#define VFS_DEVICE_NODES CONFIG_VFS_DEVICE_NODES
#endif

#ifndef CONFIG_VFS_DEVICE_MEM_SIZE
#define VFS_DEVICE_MEM_SIZE 2000
#else
#define VFS_DEVICE_MEM_SIZE CONFIG_VFS_DEVICE_MEM_SIZE
#endif

#ifndef CONFIG_VFS_FD_OFFSET
#define VFS_FD_OFFSET 512
#else
#define VFS_FD_OFFSET CONFIG_VFS_FD_OFFSET
#endif

#ifndef CONFIG_VFS_PATH_MAX
#define VFS_PATH_MAX 256
#else
#define VFS_PATH_MAX CONFIG_VFS_PATH_MAX
#endif

#ifndef CONFIG_VFS_MAX_FILE_NUM
#define VFS_MAX_FILE_NUM (VFS_DEVICE_NODES * 2)
#else
#define VFS_MAX_FILE_NUM CONFIG_VFS_MAX_FILE_NUM
#endif

#ifndef CONFIG_VFS_STAT_INCLUDE_SIZE
#define VFS_STAT_INCLUDE_SIZE 1
#else
#define VFS_STAT_INCLUDE_SIZE CONFIG_VFS_STAT_INCLUDE_SIZE
#endif

#ifndef CONFIG_CURRENT_WORKING_DIRECTORY_ENBALE
#define CURRENT_WORKING_DIRECTORY_ENBALE 0
#else
#define CURRENT_WORKING_DIRECTORY_ENBALE CONFIG_CURRENT_WORKING_DIRECTORY_ENBALE
#endif

#endif /* VFS_CONF_H */
