NAME := pwr_test

$(NAME)_SOURCES := pwr_test.c

GLOBAL_DEFINES += AOS_NO_WIFI

$(NAME)_COMPONENTS := yloop cli rhino/pwrmgmt

GLOBAL_DEFINES += RHINO_CONFIG_CPU_PWR_MGMT=1

ifeq ($(BENCHMARKS),1)
$(NAME)_COMPONENTS  += benchmarks
GLOBAL_DEFINES      += CONFIG_CMD_BENCHMARKS
endif

GLOBAL_INCLUDES += ./