/*
 * Copyright (C) 2015-2019 Alibaba Group Holding Limited
 */

#ifndef HTTP_CLIENT_CONFIG_H
#define HTTP_CLIENT_CONFIG_H

#ifndef CONFIG_HTTPC_SESSION_NUM
#define CONFIG_HTTPC_SESSION_NUM 5
#endif

#ifndef CONFIG_HTTPC_SERVER_NAME_SIZE
#define CONFIG_HTTPC_SERVER_NAME_SIZE 32
#endif

#ifndef CONFIG_HTTPC_HEADER_SIZE
#define CONFIG_HTTPC_HEADER_SIZE 128
#endif

#ifndef CONFIG_HTTPC_DEFAULT_CLIENT
#define CONFIG_HTTPC_DEFAULT_CLIENT "AliOS Things/ 2.1"
#endif

#endif
