/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "SPI_1.h"
#include "SPI_1_SPI_UART.h"
#include "SPI_1_PINS.h"
#include "SPI_1_SPI_UART_PVT.h"
#include "SPI_1_PVT.h"
#include "SPI_1_BOOT.h"
#include "pin_wakeup.h"
#include "pin_wakeup_aliases.h"
#include "wakeup_irq.h"
#include "RTC.h"
#include "global_irq.h"
#include "dio1.h"
#include "dio1_aliases.h"
#include "nss.h"
#include "nss_aliases.h"
#include "SPI_BUSY.h"
#include "SPI_BUSY_aliases.h"
#include "SPI_NRESET.h"
#include "SPI_NRESET_aliases.h"
#include "antpow.h"
#include "antpow_aliases.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_rx_wake.h"
#include "UART_1_rx_wake_aliases.h"
#include "UART_1_RX_WAKEUP_IRQ.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_SCB_IRQ.h"
#include "SPI_1_SCBCLK.h"
#include "SPI_1_sclk_m.h"
#include "SPI_1_sclk_m_aliases.h"
#include "SPI_1_miso_m.h"
#include "SPI_1_miso_m_aliases.h"
#include "SPI_1_mosi_m.h"
#include "SPI_1_mosi_m_aliases.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

