
#define SAMP_FREQ 16000
#define MFCC_DEC_BITS 2
#define FRAME_SHIFT_MS 40
#define FRAME_SHIFT ((int16_t)(SAMP_FREQ * 0.001 * FRAME_SHIFT_MS))
#define NUM_FRAMES 25
#define NUM_MFCC_COEFFS 10
#define MFCC_BUFFER_SIZE (NUM_FRAMES * NUM_MFCC_COEFFS)
#define FRAME_LEN_MS 40
#define FRAME_LEN ((int16_t)(SAMP_FREQ * 0.001 * FRAME_LEN_MS))

#define IN_DIM (NUM_FRAMES * NUM_MFCC_COEFFS)
#define OUT_DIM 12
#define IP1_OUT_DIM 144 /* 144 */
#define IP2_OUT_DIM 144 /* 144 */
#define IP3_OUT_DIM 144 /* 144 */
#define IP1_WT_DIM (IP1_OUT_DIM * IN_DIM)
#define IP2_WT_DIM (IP2_OUT_DIM * IP1_OUT_DIM)
#define IP3_WT_DIM (IP3_OUT_DIM * IP2_OUT_DIM)
#define IP4_WT_DIM (OUT_DIM * IP3_OUT_DIM)

#define MAX_SRC_LEN 128