NAME := nutiny-evb-nano130

$(NAME)_TYPE         := kernel
MODULE               := 1062
HOST_ARCH            := Cortex-M0
HOST_MCU_FAMILY      := nano130ke3bn
SUPPORT_BINS         := no
ENABLE_VFP           := 1
CONFIG_SYSINFO_PRODUCT_MODEL := ALI_AOS_NUTINY_NANO130
CONFIG_SYSINFO_DEVICE_NAME := $(NAME)
CONFIG_SYSINFO_OS_VERSION := 100

$(NAME)_SOURCES += \
		            aos/board.c \
                    aos/soc_init.c \
                    aos/board_cli.c
                   
$(NAME)_SOURCES += startup_Nano100Series.c 

GLOBAL_INCLUDES += . \
                   hal/ \
                   aos/ \
                   inc/
				   
GLOBAL_CFLAGS += -DNUMICRO_NANO130
GLOBAL_DEFINES += TOOLCHAIN_GCC_ARM=1
GLOBAL_DEFINES += STDIO_UART=0
GLOBAL_DEFINES += STDIO_UART_BUADRATE=115200
#GLOBAL_DEFINES += CONFIG_AOS_CLI_BOARD
GLOBAL_DEFINES += CONFIG_AOS_CLI_STACK_SIZE=1024

sal ?= 0
no_tls ?= 1
GLOBAL_DEFINES += CONFIG_NO_TCPIP

ifeq ($(COMPILER),armcc)
$(NAME)_LINK_FILES := startup_Nano100Series.o
endif

GLOBAL_CFLAGS += -DSYSINFO_OS_VERSION=\"$(CONFIG_SYSINFO_OS_VERSION)\"
GLOBAL_CFLAGS += -DSYSINFO_PRODUCT_MODEL=\"$(CONFIG_SYSINFO_PRODUCT_MODEL)\"
GLOBAL_CFLAGS += -DSYSINFO_DEVICE_NAME=\"$(CONFIG_SYSINFO_DEVICE_NAME)\"
GLOBAL_CFLAGS += -DSYSINFO_ARCH=\"$(HOST_ARCH)\"
GLOBAL_CFLAGS += -DSYSINFO_MCU=\"$(HOST_MCU_FAMILY)\"
