// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.17"
#define MICROPY_GIT_HASH "7c54b6428-dirty"
#define MICROPY_BUILD_DATE "2021-07-01"
#define MICROPY_PY_SYS_PLATFORM "AliOS Things"

