target-samples:; @true
target-src/platform:; @true
target-src/protocol/alcs:; @true
target-src/protocol/coap:; @true
target-src/protocol/http:; @true
target-src/protocol/http2:; @true
target-src/protocol/mqtt:; @true
target-src/security/base:; @true
target-src/services/cota:; @true
target-src/services/file_upload:; @true
target-src/services/fota:; @true
target-src/services/linkkit:; @true
target-src/services/linkkit/cm:; @true
target-src/services/linkkit/dm:; @true
target-src/services/ota:; @true
target-src/services/shadow:; @true
target-src/services/subdev:; @true
target-src/thirdparty/tfs:; @true
target-src/thirdparty/tls:; @true
target-src/tools/linkkit_tsl_convert:; @true
target-src/utils:; @true
target-tests:; @true
