/*
 * Copyright (C) 2015-2017 Alibaba Group Holding Limited
 */

#ifndef CLI_CONF_H
#define CLI_CONF_H

#ifndef CLI_CONFIG_MINIMUM_MODE
#define CLI_MINIMUM_MODE 0
#else
#define CLI_MINIMUM_MODE CLI_CONFIG_MINIMUM_MODE
#endif

#ifndef CLI_CONFIG_INBUF_SIZE
#define CLI_INBUF_SIZE 256
#else
#define CLI_INBUF_SIZE CLI_CONFIG_INBUF_SIZE
#endif

#ifndef CLI_CONFIG_OUTBUF_SIZE
#define CLI_OUTBUF_SIZE 512
#else
#define CLI_OUTBUF_SIZE CLI_CONFIG_OUTBUF_SIZE
#endif

#ifndef CLI_CONFIG_MAX_COMMANDS
#define CLI_MAX_COMMANDS 64
#else
#define CLI_MAX_COMMANDS CLI_CONFIG_MAX_COMMANDS
#endif

#ifndef CLI_CONFIG_MAX_ARG_NUM
#define CLI_MAX_ARG_NUM 16
#else
#define CLI_MAX_ARG_NUM CLI_CONFIG_MAX_ARG_NUM
#endif

#ifndef CLI_CONFIG_MAX_ONCECMD_NUM
#define CLI_MAX_ONCECMD_NUM 4
#else
#define CLI_MAX_ONCECMD_NUM CLI_CONFIG_MAX_ONCECMD_NUM
#endif

#ifndef CLI_CONFIG_STACK_SIZE
#define CLI_STACK_SIZE 2048
#else
#define CLI_STACK_SIZE CLI_CONFIG_STACK_SIZE
#endif

#ifndef CLI_CONFIG_TASK_PRIORITY
#define CLI_TASK_PRIORITY 60 /* RHINO_CONFIG_PRI_MAX - 2 */
#else
#define CLI_TASK_PRIORITY CLI_CONFIG_TASK_PRIORITY
#endif

#ifndef CLI_CONFIG_TELNET_SUPPORT
#define CLI_TELNET_SUPPORT 0
#else
#define CLI_TELNET_SUPPORT CLI_CONFIG_TELNET_SUPPORT
#endif

#ifndef CLI_CONFIG_SUPPORT_BOARD_CMD
#define CLI_SUPPORT_BOARD_CMD 0
#else
#define CLI_SUPPORT_BOARD_CMD CLI_CONFIG_SUPPORT_BOARD_CMD
#endif

#endif /* CLI_CONF_H */
