CONFIG_ENV_CFLAGS   += \
    -Os -Wall \
    -D_PLATFORM_IS_HOST_ \
    -DCONFIG_HTTP_AUTH_TIMEOUT=500 \
    -DCONFIG_MID_HTTP_TIMEOUT=500 \
    -DCONFIG_GUIDER_AUTH_TIMEOUT=500 \
    -DUSING_UTILS_JSON \
    -DCM_VIA_CLOUD_CONN \
    -DCM_VIA_CLOUD_CONN_MQTT \
    -DCONFIG_DM_DEVTYPE_SINGLE

LDFLAGS             += -lpthread -lrt
