/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/bcpu/obj/debug/bcpu_rom_version.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/bcpu/obj/debug/bcpu_romstring.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/bcpu/obj/debug/spal_cholk.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/bcpu/obj/debug/spal_excor.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/bcpu/obj/debug/spc_main.o
