/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/patch/obj/debug/patch.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/patch/obj/debug/patch_open.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/patch/obj/debug/patch_spc_amr_rx.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/patch/obj/debug/patch_spc_irq_handler.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/patch/obj/debug/patch_spc_rx.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/patch/obj/debug/patch_spp_fcch_detect_asm.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/patch/obj/debug/patch_spp_gsm_equalizer.o
/home/rdyjshi/RDA8955/soft/build/8955_modem/_default_/bcpu/platform/chip/patch/obj/debug/patch_spp_gsm_rx.o
