// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "v1.15"
#define MICROPY_GIT_HASH "5429689-dirty"
#define MICROPY_BUILD_DATE "2021-05-07"
#define MICROPY_PY_SYS_PLATFORM "AliOS Things"

