#!/usr/bin/expect -f
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

source "tests/scripts/expect/_common.exp"

spawn_node 1

send "coex disable\n"
expect_line "Done"
send "coex\n"
expect "Disabled"
expect_line "Done"
send "coex enable\n"
expect_line "Done"
send "coex\n"
expect "Enabled"
expect_line "Done"
send "coex metrics\n"
expect -re {Stopped: (true|false)}
expect -re {Grant Glitch: \d+}
expect "Transmit metrics"
expect -re {    Request: \d+}
expect -re {    Grant Immediate: \d+}
expect -re {    Grant Wait: \d+}
expect -re {    Grant Wait Activated: \d+}
expect -re {    Grant Wait Timeout: \d+}
expect -re {    Grant Deactivated During Request: \d+}
expect -re {    Delayed Grant: \d+}
expect -re {    Average Request To Grant Time: \d+}
expect "Receive metrics"
expect -re {    Request: \d+}
expect -re {    Grant Immediate: \d+}
expect -re {    Grant Wait: \d+}
expect -re {    Grant Wait Activated: \d+}
expect -re {    Grant Wait Timeout: \d+}
expect -re {    Grant Deactivated During Request: \d+}
expect -re {    Delayed Grant: \d+}
expect -re {    Average Request To Grant Time: \d+}
expect -re {    Grant None: \d+}
expect_line "Done"
send "coex something_invalid\n"
expect "Error 7: InvalidArgs"

dispose_all
