#!/usr/bin/expect -f
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

# This script verifies multicast loop back.

#
#
# R1 -- R2 -- R3 -- E4
#

source "tests/scripts/expect/_common.exp"

spawn_node 1
setup_default_network

set timeout 1

send "panid 0xface\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

wait_for "state" "leader"
expect_line "Done"

set extaddr1 [get_extaddr]

get_rloc16

spawn_node 2 cli
setup_default_network

send "panid 0xface\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

wait_for "state" "router"
expect_line "Done"
sleep 3

get_rloc16

spawn_node 3 cli
setup_default_network

send "panid 0xface\n"
expect_line "Done"

send "macfilter addr add ${extaddr1}\n"
expect_line "Done"

send "macfilter addr denylist\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

wait_for "state" "router"
expect_line "Done"
sleep 4

set extaddr3 [get_extaddr]

get_rloc16

spawn_node 4 cli
setup_default_network

send "panid 0xface\n"
expect_line "Done"

send "mode rn\n"
expect_line "Done"

send "macfilter addr add ${extaddr3}\n"
expect_line "Done"

send "macfilter addr allowlist\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

wait_for "state" "child"
expect_line "Done"

get_rloc16

switch_node 1

set rloc(1) [get_ipaddr "rloc"]

send "networkdiagnostic get ff03::2 5 16\n"
expect "DIAG_GET.rsp/ans from $rloc(1)"
expect_line "Done"

sleep 5

dispose_all
