#!/usr/bin/expect -f
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

source "tests/scripts/expect/_common.exp"
source "tests/scripts/expect/_multinode.exp"

setup_two_nodes

switch_node 2
send "udp open\n"
expect_line "Done"
send "udp bind :: 11001\n"
expect_line "Done"
set addr_2 [get_ipaddr mleid]

switch_node 1
set addr_1 [get_ipaddr mleid]
send "udp open\n"
expect_line "Done"
send "udp bind :: 11002\n"
expect_line "Done"
send "udp connect $addr_2 11001\n"
expect_line "Done"
send "udp send -s 10\n"
expect_line "Done"
send "udp send -x a68656c6c6f\n"
expect_line "Done"
send "udp send -t there\n"
expect_line "Done"

switch_node 2
expect "10 bytes from $addr_1 11002 0123456789"
expect "6 bytes from $addr_1 11002"
expect "hello"
expect "5 bytes from $addr_1 11002 there"

switch_node 1
send "udp help\n"
expect_line "Done"
send "udp connect something_invalid\n"
expect "Error 6: Parse"
send "udp send -x something_invalid\n"
expect "Error 7: InvalidArgs"
send "udp\n"
expect "Error 7: InvalidArgs"

send "udp linksecurity\n"
expect "Enabled"
expect_line "Done"
send "udp linksecurity disable\n"
expect_line "Done"
send "udp linksecurity\n"
expect "Disabled"
expect_line "Done"
send "udp linksecurity enable\n"
expect_line "Done"
send "udp linksecurity\n"
expect "Enabled"
expect_line "Done"

send "udp linksecurity something_invalid\n"
expect "Error 35: InvalidCommand"

dispose_all
