#!/usr/bin/expect -f
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

# This script verifies UDP socket can connect and disconnect when platform UDP is enabled.

source "tests/scripts/expect/_common.exp"

spawn_node 1

set timeout 1

send "panid 0xface\n"
expect_line "Done"

send "ifconfig up\n"
expect_line "Done"

send "thread start\n"
expect_line "Done"

wait_for "state" "leader"
expect_line "Done"

send "udp open\n"
expect_line "Done"

send "udp bind :: 1234\n"
expect_line "Done"

send "dataset active\n"
expect -re {Mesh Local Prefix: ([0-9a-f:]*)::\/64}
set prefix $expect_out(1,string)
expect_line "Done"

send "udp connect $prefix:bb1:ebd6:ad10:f33 1234\n"
expect_line "Done"

send "udp connect $prefix:1:2:3:4 4321\n"
expect_line "Done"

send "udp close\n"
expect_line "Done"

dispose_all
