NAME := board_b_f769

$(NAME)_MBINS_TYPE := kernel
$(NAME)_VERSION    := 1.0.0
$(NAME)_SUMMARY    := configuration for board b_f769
MODULE             := 1062
HOST_ARCH          := Cortex-M7
HOST_MCU_FAMILY    := mcu_stm32f7xx
SUPPORT_MBINS      := no
HOST_MCU_NAME      := STM32F769I-Discovery

GLOBAL_INCLUDES += .

GLOBAL_DEFINES += STDIO_UART=0 CONFIG_NO_TCPIP

CONFIG_SYSINFO_PRODUCT_MODEL := ALI_AOS_F769-nucleo
CONFIG_SYSINFO_DEVICE_NAME   := f769-nucleo

GLOBAL_CFLAGS += -DSYSINFO_PRODUCT_MODEL=\"$(CONFIG_SYSINFO_PRODUCT_MODEL)\"
GLOBAL_CFLAGS += -DSYSINFO_DEVICE_NAME=\"$(CONFIG_SYSINFO_DEVICE_NAME)\"
