NAME := board_b_f769


$(NAME)_TYPE := kernel
MODULE               := 1062
HOST_ARCH            := Cortex-M7
HOST_MCU_FAMILY      := stm32f7xx.src.STM32F769I-Discovery
SUPPORT_BINS         := no
HOST_MCU_NAME        := STM32F769I-Discovery

GLOBAL_INCLUDES += .

GLOBAL_DEFINES += STDIO_UART=0 CONFIG_NO_TCPIP

CONFIG_SYSINFO_PRODUCT_MODEL := ALI_AOS_F769-nucleo
CONFIG_SYSINFO_DEVICE_NAME := f769-nucleo

GLOBAL_CFLAGS += -DSYSINFO_OS_VERSION=\"$(CONFIG_SYSINFO_OS_VERSION)\"
GLOBAL_CFLAGS += -DSYSINFO_PRODUCT_MODEL=\"$(CONFIG_SYSINFO_PRODUCT_MODEL)\"
GLOBAL_CFLAGS += -DSYSINFO_DEVICE_NAME=\"$(CONFIG_SYSINFO_DEVICE_NAME)\"
