--- instance0 ---
advertise
connected
written b'central0'
write
notify
written b'central1'
notify
written b'central2'
write
indicate
disconnected
--- instance1 ---
connect
service UUID('a5a5a5a5-ffff-9999-1111-5a5a5a5a5a5a')
characteristic UUID('00000000-1111-2222-3333-444444444444')
read b'periph0'
write
notified b'periph1'
read b'periph1'
write
notified b'periph2'
read b'central1'
write
indicated b'periph3'
read b'periph3'
disconnect
disconnected
