NAME := smpapp_4core

$(NAME)_MBINS_TYPE := app
$(NAME)_VERSION := 0.0.1
$(NAME)_SUMMARY :=
$(NAME)_SOURCES := smpapp_4core.c

GLOBAL_DEFINES += AOS_NO_WIFI  LOG_LOCAL_LEVEL=4 RHINO_CONFIG_CPU_NUM=4

GLOBAL_ASMFLAGS += -DRHINO_CONFIG_CPU_NUM=4

OS_MUTICORE_NUM := 4

$(NAME)_COMPONENTS := yloop cli

ifeq ($(BENCHMARKS),1)
$(NAME)_COMPONENTS  += benchmarks
GLOBAL_DEFINES      += CONFIG_CMD_BENCHMARKS
endif

GLOBAL_INCLUDES += ./